# Form implementation generated from reading ui file 'AnSinh\ansinh_fix.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 760)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 760))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 760))
        MainWindow.setStyleSheet("QMainWindow, QWidget {\n"
"    background: #FFF6FB;\n"
"    font-family: \"Arial\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1200, 760))
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    border: none;\n"
"    background: #FFF6FB;\n"
"}\n"
"QScrollBar:vertical {\n"
"    background: #FBE5F0;\n"
"    width: 12px;\n"
"    margin: 0px;\n"
"    border-radius: 6px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #E8B8D0;\n"
"    min-height: 30px;\n"
"    border-radius: 6px;\n"
"}\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1200, 1800))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(1200, 1800))
        self.scrollAreaWidgetContents.setStyleSheet("background: #FFF6FB;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.topBar = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.topBar.setGeometry(QtCore.QRect(0, 0, 1200, 90))
        self.topBar.setStyleSheet("QFrame#topBar {\n"
"    background: #FFF3F9;\n"
"    font-family: \"Segoe UI\";\n"
"    border: none;\n"
"}\n"
"\n"
"QFrame#navFrame {\n"
"    background: #F5DCE6;\n"
"    border: none;\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"QLabel#logoImage {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QLabel#brandTitle {\n"
"    color: #9C4F74;\n"
"    font-size: 18pt;\n"
"    font-weight: 800;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel#brandSubtitle {\n"
"    color: #9D8A93;\n"
"    font-size: 8pt;\n"
"    font-weight: 500;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QPushButton#btnHome,\n"
"QPushButton#btnCreate,\n"
"QPushButton#btnFollow,\n"
"QPushButton#btnPublic {\n"
"    background: transparent;\n"
"    border: none;\n"
"    border-radius: 18px;\n"
"    padding: 10px 18px;\n"
"    color: #2C2328;\n"
"    font-size: 11pt;\n"
"    font-weight: 600;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton#btnHome:hover,\n"
"QPushButton#btnCreate:hover,\n"
"QPushButton#btnFollow:hover,\n"
"QPushButton#btnPublic:hover {\n"
"    background: #EEC9D8;\n"
"}\n"
"\n"
"QPushButton#btnHome:pressed,\n"
"QPushButton#btnCreate:pressed,\n"
"QPushButton#btnFollow:pressed,\n"
"QPushButton#btnPublic:pressed {\n"
"    background: #E2B5C7;\n"
"}\n"
"\n"
"QPushButton#btnHome {\n"
"    background: #C98AA5;\n"
"    color: white;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"QToolButton#btnNotify,\n"
"QToolButton#btnSetting,\n"
"QToolButton#btnProfile {\n"
"    background: transparent;\n"
"    border: none;\n"
"    border-radius: 18px;\n"
"    color: #2C2328;\n"
"    font-size: 16pt;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QToolButton#btnNotify:hover,\n"
"QToolButton#btnSetting:hover,\n"
"QToolButton#btnProfile:hover {\n"
"    background: #EEC9D8;\n"
"}\n"
"\n"
"QLabel#notifyBadge {\n"
"    background: #E74C3C;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    font-size: 8pt;\n"
"    font-weight: 700;\n"
"    padding: 0px;\n"
"}")
        self.topBar.setObjectName("topBar")
        self.topBarLayout = QtWidgets.QVBoxLayout(self.topBar)
        self.topBarLayout.setContentsMargins(12, 10, 12, 10)
        self.topBarLayout.setObjectName("topBarLayout")
        self.navFrame = QtWidgets.QFrame(parent=self.topBar)
        self.navFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.navFrame.setObjectName("navFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.navFrame)
        self.horizontalLayout.setContentsMargins(18, 10, 18, 10)
        self.horizontalLayout.setSpacing(18)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logoLayout = QtWidgets.QHBoxLayout()
        self.logoLayout.setSpacing(8)
        self.logoLayout.setObjectName("logoLayout")
        self.logoImage = QtWidgets.QLabel(parent=self.navFrame)
        self.logoImage.setMinimumSize(QtCore.QSize(54, 54))
        self.logoImage.setMaximumSize(QtCore.QSize(54, 54))
        self.logoImage.setScaledContents(False)
        self.logoImage.setObjectName("logoImage")
        self.logoLayout.addWidget(self.logoImage)
        self.brandLayout = QtWidgets.QVBoxLayout()
        self.brandLayout.setSpacing(0)
        self.brandLayout.setObjectName("brandLayout")
        self.brandTitle = QtWidgets.QLabel(parent=self.navFrame)
        self.brandTitle.setObjectName("brandTitle")
        self.brandLayout.addWidget(self.brandTitle)
        self.brandSubtitle = QtWidgets.QLabel(parent=self.navFrame)
        self.brandSubtitle.setObjectName("brandSubtitle")
        self.brandLayout.addWidget(self.brandSubtitle)
        self.logoLayout.addLayout(self.brandLayout)
        self.horizontalLayout.addLayout(self.logoLayout)
        self.menuLayout = QtWidgets.QHBoxLayout()
        self.menuLayout.setSpacing(10)
        self.menuLayout.setObjectName("menuLayout")
        self.btnHome = QtWidgets.QPushButton(parent=self.navFrame)
        self.btnHome.setMinimumSize(QtCore.QSize(0, 42))
        self.btnHome.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnHome.setObjectName("btnHome")
        self.menuLayout.addWidget(self.btnHome)
        self.btnCreate = QtWidgets.QPushButton(parent=self.navFrame)
        self.btnCreate.setMinimumSize(QtCore.QSize(0, 42))
        self.btnCreate.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCreate.setObjectName("btnCreate")
        self.menuLayout.addWidget(self.btnCreate)
        self.btnFollow = QtWidgets.QPushButton(parent=self.navFrame)
        self.btnFollow.setMinimumSize(QtCore.QSize(0, 42))
        self.btnFollow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnFollow.setObjectName("btnFollow")
        self.menuLayout.addWidget(self.btnFollow)
        self.btnPublic = QtWidgets.QPushButton(parent=self.navFrame)
        self.btnPublic.setMinimumSize(QtCore.QSize(0, 42))
        self.btnPublic.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPublic.setObjectName("btnPublic")
        self.menuLayout.addWidget(self.btnPublic)
        self.horizontalLayout.addLayout(self.menuLayout)
        self.rightActionsWidget = QtWidgets.QWidget(parent=self.navFrame)
        self.rightActionsWidget.setMinimumSize(QtCore.QSize(150, 50))
        self.rightActionsWidget.setObjectName("rightActionsWidget")
        self.rightActionsLayout = QtWidgets.QHBoxLayout(self.rightActionsWidget)
        self.rightActionsLayout.setContentsMargins(0, 0, 0, 0)
        self.rightActionsLayout.setSpacing(8)
        self.rightActionsLayout.setObjectName("rightActionsLayout")
        self.notifyWrapper = QtWidgets.QWidget(parent=self.rightActionsWidget)
        self.notifyWrapper.setMinimumSize(QtCore.QSize(36, 36))
        self.notifyWrapper.setMaximumSize(QtCore.QSize(36, 36))
        self.notifyWrapper.setObjectName("notifyWrapper")
        self.btnNotify = QtWidgets.QToolButton(parent=self.notifyWrapper)
        self.btnNotify.setGeometry(QtCore.QRect(0, -7, 41, 41))
        self.btnNotify.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnNotify.setObjectName("btnNotify")
        self.notifyBadge = QtWidgets.QLabel(parent=self.notifyWrapper)
        self.notifyBadge.setGeometry(QtCore.QRect(20, 0, 16, 16))
        self.notifyBadge.setObjectName("notifyBadge")
        self.rightActionsLayout.addWidget(self.notifyWrapper)
        self.btnSetting = QtWidgets.QToolButton(parent=self.rightActionsWidget)
        self.btnSetting.setMinimumSize(QtCore.QSize(36, 36))
        self.btnSetting.setMaximumSize(QtCore.QSize(36, 36))
        self.btnSetting.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnSetting.setObjectName("btnSetting")
        self.rightActionsLayout.addWidget(self.btnSetting)
        self.btnProfile = QtWidgets.QToolButton(parent=self.rightActionsWidget)
        self.btnProfile.setMinimumSize(QtCore.QSize(40, 40))
        self.btnProfile.setMaximumSize(QtCore.QSize(40, 40))
        self.btnProfile.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnProfile.setObjectName("btnProfile")
        self.rightActionsLayout.addWidget(self.btnProfile)
        self.horizontalLayout.addWidget(self.rightActionsWidget)
        self.topBarLayout.addWidget(self.navFrame)
        self.titleIcon = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.titleIcon.setGeometry(QtCore.QRect(290, 89, 28, 28))
        self.titleIcon.setStyleSheet("QLabel{\n"
"    font-size:24px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.titleIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleIcon.setObjectName("titleIcon")
        self.mainTitle = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.mainTitle.setGeometry(QtCore.QRect(324, 83, 460, 40))
        self.mainTitle.setStyleSheet("QLabel{\n"
"    color:#7F4D7D;\n"
"    font-size:28px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.mainTitle.setObjectName("mainTitle")
        self.searchEdit = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.searchEdit.setGeometry(QtCore.QRect(291, 129, 474, 30))
        self.searchEdit.setStyleSheet("QLineEdit{\n"
"    background:white;\n"
"    border:1px solid #CFCFCF;\n"
"    padding-left:28px;\n"
"    color:#222;\n"
"    font-size:10px;\n"
"}")
        self.searchEdit.setObjectName("searchEdit")
        self.searchIcon = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.searchIcon.setGeometry(QtCore.QRect(300, 139, 14, 14))
        self.searchIcon.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:13px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.searchIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.searchIcon.setObjectName("searchIcon")
        self.categoryCombo = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.categoryCombo.setGeometry(QtCore.QRect(764, 129, 110, 30))
        self.categoryCombo.setStyleSheet("QComboBox{\n"
"    background:white;\n"
"    border:1px solid #CFCFCF;\n"
"    padding-left:8px;\n"
"    color:#222;\n"
"    font-size:10px;\n"
"}")
        self.categoryCombo.setObjectName("categoryCombo")
        self.categoryCombo.addItem("")
        self.searchButton = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.searchButton.setGeometry(QtCore.QRect(888, 129, 64, 30))
        self.searchButton.setStyleSheet("QPushButton{\n"
"    background:#FFF6FB;\n"
"    border:1px solid #7F4D7D;\n"
"    color:#222;\n"
"    font-size:10px;\n"
"    font-weight:700;\n"
"}")
        self.searchButton.setObjectName("searchButton")
        self.card1 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card1.setGeometry(QtCore.QRect(315, 185, 295, 261))
        self.card1.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card1.setObjectName("card1")
        self.card1Image = QtWidgets.QLabel(parent=self.card1)
        self.card1Image.setGeometry(QtCore.QRect(1, 1, 293, 126))
        self.card1Image.setStyleSheet("QLabel{\n"
"    background:#DADADA;\n"
"    color:#666;\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    font-size:14px;\n"
"    font-weight:600;\n"
"}")
        self.card1Image.setText("")
        self.card1Image.setPixmap(QtGui.QPixmap("AnSinh\\campaign30"))
        self.card1Image.setScaledContents(True)
        self.card1Image.setObjectName("card1Image")
        self.card1Title = QtWidgets.QLabel(parent=self.card1)
        self.card1Title.setGeometry(QtCore.QRect(7, 137, 279, 42))
        self.card1Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card1Title.setWordWrap(True)
        self.card1Title.setObjectName("card1Title")
        self.card1Date = QtWidgets.QLabel(parent=self.card1)
        self.card1Date.setGeometry(QtCore.QRect(11, 173, 170, 16))
        self.card1Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card1Date.setObjectName("card1Date")
        self.card1Owner = QtWidgets.QLabel(parent=self.card1)
        self.card1Owner.setGeometry(QtCore.QRect(11, 188, 180, 16))
        self.card1Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card1Owner.setObjectName("card1Owner")
        self.card1Money = QtWidgets.QLabel(parent=self.card1)
        self.card1Money.setGeometry(QtCore.QRect(12, 210, 220, 20))
        self.card1Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card1Money.setObjectName("card1Money")
        self.card1Progress = QtWidgets.QProgressBar(parent=self.card1)
        self.card1Progress.setGeometry(QtCore.QRect(14, 228, 242, 8))
        self.card1Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card1Progress.setProperty("value", 30)
        self.card1Progress.setTextVisible(False)
        self.card1Progress.setObjectName("card1Progress")
        self.card1More = QtWidgets.QLabel(parent=self.card1)
        self.card1More.setGeometry(QtCore.QRect(18, 236, 70, 16))
        self.card1More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card1More.setObjectName("card1More")
        self.card2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card2.setGeometry(QtCore.QRect(644, 185, 295, 261))
        self.card2.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card2.setObjectName("card2")
        self.card2Image = QtWidgets.QLabel(parent=self.card2)
        self.card2Image.setGeometry(QtCore.QRect(1, 1, 293, 126))
        self.card2Image.setStyleSheet("QLabel{\n"
"    background:#DADADA;\n"
"    color:#666;\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"}")
        self.card2Image.setPixmap(QtGui.QPixmap("AnSinh\\campaign31"))
        self.card2Image.setScaledContents(True)
        self.card2Image.setObjectName("card2Image")
        self.card2Title = QtWidgets.QLabel(parent=self.card2)
        self.card2Title.setGeometry(QtCore.QRect(7, 136, 279, 46))
        self.card2Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card2Title.setWordWrap(True)
        self.card2Title.setObjectName("card2Title")
        self.card2Date = QtWidgets.QLabel(parent=self.card2)
        self.card2Date.setGeometry(QtCore.QRect(11, 176, 170, 16))
        self.card2Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card2Date.setObjectName("card2Date")
        self.card2Owner = QtWidgets.QLabel(parent=self.card2)
        self.card2Owner.setGeometry(QtCore.QRect(11, 191, 190, 16))
        self.card2Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card2Owner.setObjectName("card2Owner")
        self.card2Money = QtWidgets.QLabel(parent=self.card2)
        self.card2Money.setGeometry(QtCore.QRect(12, 210, 220, 20))
        self.card2Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card2Money.setObjectName("card2Money")
        self.card2Progress = QtWidgets.QProgressBar(parent=self.card2)
        self.card2Progress.setGeometry(QtCore.QRect(14, 228, 242, 8))
        self.card2Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card2Progress.setProperty("value", 30)
        self.card2Progress.setTextVisible(False)
        self.card2Progress.setObjectName("card2Progress")
        self.card2More = QtWidgets.QLabel(parent=self.card2)
        self.card2More.setGeometry(QtCore.QRect(18, 236, 70, 16))
        self.card2More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card2More.setObjectName("card2More")
        self.card3 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card3.setGeometry(QtCore.QRect(315, 472, 295, 261))
        self.card3.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card3.setObjectName("card3")
        self.card3Image = QtWidgets.QLabel(parent=self.card3)
        self.card3Image.setGeometry(QtCore.QRect(1, 1, 293, 126))
        self.card3Image.setStyleSheet("QLabel{\n"
"    background:#DADADA;\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"}")
        self.card3Image.setPixmap(QtGui.QPixmap("AnSinh\\campaign32"))
        self.card3Image.setScaledContents(True)
        self.card3Image.setObjectName("card3Image")
        self.card3Title = QtWidgets.QLabel(parent=self.card3)
        self.card3Title.setGeometry(QtCore.QRect(7, 136, 279, 42))
        self.card3Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card3Title.setWordWrap(True)
        self.card3Title.setObjectName("card3Title")
        self.card3Date = QtWidgets.QLabel(parent=self.card3)
        self.card3Date.setGeometry(QtCore.QRect(11, 173, 170, 16))
        self.card3Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card3Date.setObjectName("card3Date")
        self.card3Owner = QtWidgets.QLabel(parent=self.card3)
        self.card3Owner.setGeometry(QtCore.QRect(11, 188, 180, 16))
        self.card3Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card3Owner.setObjectName("card3Owner")
        self.card3Money = QtWidgets.QLabel(parent=self.card3)
        self.card3Money.setGeometry(QtCore.QRect(12, 210, 220, 20))
        self.card3Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card3Money.setObjectName("card3Money")
        self.card3Progress = QtWidgets.QProgressBar(parent=self.card3)
        self.card3Progress.setGeometry(QtCore.QRect(14, 228, 242, 8))
        self.card3Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card3Progress.setProperty("value", 30)
        self.card3Progress.setTextVisible(False)
        self.card3Progress.setObjectName("card3Progress")
        self.card3More = QtWidgets.QLabel(parent=self.card3)
        self.card3More.setGeometry(QtCore.QRect(18, 236, 70, 16))
        self.card3More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card3More.setObjectName("card3More")
        self.card4 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card4.setGeometry(QtCore.QRect(644, 472, 295, 261))
        self.card4.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card4.setObjectName("card4")
        self.card4Image = QtWidgets.QLabel(parent=self.card4)
        self.card4Image.setGeometry(QtCore.QRect(1, 1, 293, 126))
        self.card4Image.setStyleSheet("QLabel{\n"
"    background:#DADADA;\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"}")
        self.card4Image.setPixmap(QtGui.QPixmap("AnSinh\\campaign33"))
        self.card4Image.setScaledContents(True)
        self.card4Image.setObjectName("card4Image")
        self.card4Title = QtWidgets.QLabel(parent=self.card4)
        self.card4Title.setGeometry(QtCore.QRect(7, 136, 279, 42))
        self.card4Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card4Title.setWordWrap(True)
        self.card4Title.setObjectName("card4Title")
        self.card4Date = QtWidgets.QLabel(parent=self.card4)
        self.card4Date.setGeometry(QtCore.QRect(11, 173, 170, 16))
        self.card4Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card4Date.setObjectName("card4Date")
        self.card4Owner = QtWidgets.QLabel(parent=self.card4)
        self.card4Owner.setGeometry(QtCore.QRect(11, 188, 180, 16))
        self.card4Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card4Owner.setObjectName("card4Owner")
        self.card4Money = QtWidgets.QLabel(parent=self.card4)
        self.card4Money.setGeometry(QtCore.QRect(12, 210, 220, 20))
        self.card4Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card4Money.setObjectName("card4Money")
        self.card4Progress = QtWidgets.QProgressBar(parent=self.card4)
        self.card4Progress.setGeometry(QtCore.QRect(14, 228, 242, 8))
        self.card4Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card4Progress.setProperty("value", 30)
        self.card4Progress.setTextVisible(False)
        self.card4Progress.setObjectName("card4Progress")
        self.card4More = QtWidgets.QLabel(parent=self.card4)
        self.card4More.setGeometry(QtCore.QRect(18, 236, 70, 16))
        self.card4More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card4More.setObjectName("card4More")
        self.card5 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card5.setGeometry(QtCore.QRect(315, 759, 295, 261))
        self.card5.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card5.setObjectName("card5")
        self.card5Image = QtWidgets.QLabel(parent=self.card5)
        self.card5Image.setGeometry(QtCore.QRect(1, 1, 293, 126))
        self.card5Image.setStyleSheet("QLabel{\n"
"    background:#DADADA;\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"}")
        self.card5Image.setPixmap(QtGui.QPixmap("AnSinh\\campaign34"))
        self.card5Image.setScaledContents(True)
        self.card5Image.setObjectName("card5Image")
        self.card5Title = QtWidgets.QLabel(parent=self.card5)
        self.card5Title.setGeometry(QtCore.QRect(7, 136, 279, 42))
        self.card5Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card5Title.setWordWrap(True)
        self.card5Title.setObjectName("card5Title")
        self.card5Date = QtWidgets.QLabel(parent=self.card5)
        self.card5Date.setGeometry(QtCore.QRect(11, 173, 170, 16))
        self.card5Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card5Date.setObjectName("card5Date")
        self.card5Owner = QtWidgets.QLabel(parent=self.card5)
        self.card5Owner.setGeometry(QtCore.QRect(11, 188, 180, 16))
        self.card5Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card5Owner.setObjectName("card5Owner")
        self.card5Money = QtWidgets.QLabel(parent=self.card5)
        self.card5Money.setGeometry(QtCore.QRect(12, 210, 220, 20))
        self.card5Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card5Money.setObjectName("card5Money")
        self.card5Progress = QtWidgets.QProgressBar(parent=self.card5)
        self.card5Progress.setGeometry(QtCore.QRect(14, 228, 242, 8))
        self.card5Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card5Progress.setProperty("value", 30)
        self.card5Progress.setTextVisible(False)
        self.card5Progress.setObjectName("card5Progress")
        self.card5More = QtWidgets.QLabel(parent=self.card5)
        self.card5More.setGeometry(QtCore.QRect(18, 236, 70, 16))
        self.card5More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card5More.setObjectName("card5More")
        self.card6 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card6.setGeometry(QtCore.QRect(644, 759, 295, 261))
        self.card6.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card6.setObjectName("card6")
        self.card6Image = QtWidgets.QLabel(parent=self.card6)
        self.card6Image.setGeometry(QtCore.QRect(1, 1, 293, 126))
        self.card6Image.setStyleSheet("QLabel{\n"
"    background:#DADADA;\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"}")
        self.card6Image.setPixmap(QtGui.QPixmap("AnSinh\\campaign35"))
        self.card6Image.setScaledContents(True)
        self.card6Image.setObjectName("card6Image")
        self.card6Title = QtWidgets.QLabel(parent=self.card6)
        self.card6Title.setGeometry(QtCore.QRect(7, 136, 279, 42))
        self.card6Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card6Title.setWordWrap(True)
        self.card6Title.setObjectName("card6Title")
        self.card6Date = QtWidgets.QLabel(parent=self.card6)
        self.card6Date.setGeometry(QtCore.QRect(11, 173, 170, 16))
        self.card6Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card6Date.setObjectName("card6Date")
        self.card6Owner = QtWidgets.QLabel(parent=self.card6)
        self.card6Owner.setGeometry(QtCore.QRect(11, 188, 180, 16))
        self.card6Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card6Owner.setObjectName("card6Owner")
        self.card6Money = QtWidgets.QLabel(parent=self.card6)
        self.card6Money.setGeometry(QtCore.QRect(12, 210, 220, 20))
        self.card6Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card6Money.setObjectName("card6Money")
        self.card6Progress = QtWidgets.QProgressBar(parent=self.card6)
        self.card6Progress.setGeometry(QtCore.QRect(14, 228, 242, 8))
        self.card6Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card6Progress.setProperty("value", 30)
        self.card6Progress.setTextVisible(False)
        self.card6Progress.setObjectName("card6Progress")
        self.card6More = QtWidgets.QLabel(parent=self.card6)
        self.card6More.setGeometry(QtCore.QRect(18, 236, 70, 16))
        self.card6More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card6More.setObjectName("card6More")
        self.card7 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card7.setGeometry(QtCore.QRect(315, 1046, 295, 261))
        self.card7.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card7.setObjectName("card7")
        self.card7Image = QtWidgets.QLabel(parent=self.card7)
        self.card7Image.setGeometry(QtCore.QRect(1, 1, 293, 126))
        self.card7Image.setStyleSheet("QLabel{\n"
"    background:#DADADA;\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"}")
        self.card7Image.setPixmap(QtGui.QPixmap("AnSinh\\campaign36"))
        self.card7Image.setScaledContents(True)
        self.card7Image.setObjectName("card7Image")
        self.card7Title = QtWidgets.QLabel(parent=self.card7)
        self.card7Title.setGeometry(QtCore.QRect(7, 136, 279, 42))
        self.card7Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card7Title.setWordWrap(True)
        self.card7Title.setObjectName("card7Title")
        self.card7Date = QtWidgets.QLabel(parent=self.card7)
        self.card7Date.setGeometry(QtCore.QRect(11, 173, 170, 16))
        self.card7Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card7Date.setObjectName("card7Date")
        self.card7Owner = QtWidgets.QLabel(parent=self.card7)
        self.card7Owner.setGeometry(QtCore.QRect(11, 188, 180, 16))
        self.card7Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card7Owner.setObjectName("card7Owner")
        self.card7Money = QtWidgets.QLabel(parent=self.card7)
        self.card7Money.setGeometry(QtCore.QRect(12, 210, 220, 20))
        self.card7Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card7Money.setObjectName("card7Money")
        self.card7Progress = QtWidgets.QProgressBar(parent=self.card7)
        self.card7Progress.setGeometry(QtCore.QRect(14, 228, 242, 8))
        self.card7Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card7Progress.setProperty("value", 30)
        self.card7Progress.setTextVisible(False)
        self.card7Progress.setObjectName("card7Progress")
        self.card7More = QtWidgets.QLabel(parent=self.card7)
        self.card7More.setGeometry(QtCore.QRect(18, 236, 70, 16))
        self.card7More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card7More.setObjectName("card7More")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chiến dịch của tôi"))
        self.logoImage.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:28pt; color:#9c4f74;\">🕊</span></p></body></html>"))
        self.brandTitle.setText(_translate("MainWindow", "Donarity"))
        self.brandSubtitle.setText(_translate("MainWindow", "by group 10"))
        self.btnHome.setText(_translate("MainWindow", "🏛 Trang chủ"))
        self.btnCreate.setText(_translate("MainWindow", "🎞 Thống kê"))
        self.btnFollow.setText(_translate("MainWindow", "📠 Chatbot"))
        self.btnPublic.setText(_translate("MainWindow", "👁 Công khai"))
        self.btnNotify.setText(_translate("MainWindow", "🔔"))
        self.notifyBadge.setText(_translate("MainWindow", " 0"))
        self.btnSetting.setText(_translate("MainWindow", "⚙"))
        self.btnProfile.setText(_translate("MainWindow", "👤"))
        self.titleIcon.setText(_translate("MainWindow", "🎀"))
        self.mainTitle.setText(_translate("MainWindow", "An sinh xã hội"))
        self.searchEdit.setPlaceholderText(_translate("MainWindow", "Search for..."))
        self.searchIcon.setText(_translate("MainWindow", "⌕"))
        self.categoryCombo.setItemText(0, _translate("MainWindow", "All Categories"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.card1Title.setText(_translate("MainWindow", "Hỗ trợ nạn nhân Chất độc Da cam (VAVA)"))
        self.card1Date.setText(_translate("MainWindow", "Date:     2004-01-10"))
        self.card1Owner.setText(_translate("MainWindow", "Owner: Nguyễn Văn Rinh"))
        self.card1Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card1More.setText(_translate("MainWindow", "Xem thêm"))
        self.card2Title.setText(_translate("MainWindow", "Nam Phương Foundation (Kiến tạo nhịp cầu)"))
        self.card2Date.setText(_translate("MainWindow", "Date:     2013-09-19"))
        self.card2Owner.setText(_translate("MainWindow", "Owner: Đinh Thị Nam Phương"))
        self.card2Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card2More.setText(_translate("MainWindow", "Xem thêm"))
        self.card3Title.setText(_translate("MainWindow", "Quỹ Charity 2000 (Quán cơm 2.000đ)"))
        self.card3Date.setText(_translate("MainWindow", "Date:     2021-03-15"))
        self.card3Owner.setText(_translate("MainWindow", "Owner: Nguyễn Minh Lộc"))
        self.card3Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card3More.setText(_translate("MainWindow", "Xem thêm"))
        self.card4Title.setText(_translate("MainWindow", "Cứu trợ lũ lụt Miền Trung (Phan Anh)"))
        self.card4Date.setText(_translate("MainWindow", "Date:     2020-10-20"))
        self.card4Owner.setText(_translate("MainWindow", "Owner: Hoàng Phan Anh"))
        self.card4Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card4More.setText(_translate("MainWindow", "Xem thêm"))
        self.card5Title.setText(_translate("MainWindow", "Chương trình Vì phụ nữ nghèo nông thôn"))
        self.card5Date.setText(_translate("MainWindow", "Date:     2021-08-08"))
        self.card5Owner.setText(_translate("MainWindow", "Owner: Hà Thị Nga"))
        self.card5Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card5More.setText(_translate("MainWindow", "Xem thêm"))
        self.card6Title.setText(_translate("MainWindow", "Chiến dịch Áo ấm mùa đông"))
        self.card6Date.setText(_translate("MainWindow", "Date:     2020-05-05"))
        self.card6Owner.setText(_translate("MainWindow", "Owner: Nguyễn Ngọc Lương"))
        self.card6Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card6More.setText(_translate("MainWindow", "Xem thêm"))
        self.card7Title.setText(_translate("MainWindow", "Quỹ Tết cho người nghèo"))
        self.card7Date.setText(_translate("MainWindow", "Date:     2022-12-15"))
        self.card7Owner.setText(_translate("MainWindow", "Owner: Phan Thu Hương"))
        self.card7Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card7More.setText(_translate("MainWindow", "Xem thêm"))
