# Form implementation generated from reading ui file 'AnSinh/ansinh.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(733, 1380)
        MainWindow.setMinimumSize(QtCore.QSize(733, 1380))
        MainWindow.setStyleSheet("QMainWindow, QWidget {\n"
"    background: #FFF6FB;\n"
"    font-family: \"Arial\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1200, 1380))
        self.scrollArea.setMinimumSize(QtCore.QSize(1200, 760))
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    border: none;\n"
"    background: #FFF6FB;\n"
"}\n"
"QScrollBar:vertical {\n"
"    background: #F8E8F0;\n"
"    width: 12px;\n"
"    border-radius: 6px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #D9AFC7;\n"
"    min-height: 40px;\n"
"    border-radius: 6px;\n"
"}\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: transparent;\n"
"}")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 733, 1560))
        self.scrollAreaWidgetContents.setStyleSheet("background: #FFF6FB;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.topBar = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.topBar.setGeometry(QtCore.QRect(-10, 0, 751, 36))
        self.topBar.setStyleSheet("QFrame{\n"
"    background:#F9DDE7;\n"
"    border:none;\n"
"    border-radius:0px;\n"
"}")
        self.topBar.setObjectName("topBar")
        self.logoIcon = QtWidgets.QLabel(parent=self.topBar)
        self.logoIcon.setGeometry(QtCore.QRect(18, 4, 26, 26))
        self.logoIcon.setStyleSheet("QLabel{\n"
"    font-size:18px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.logoIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoIcon.setObjectName("logoIcon")
        self.logoTitle = QtWidgets.QLabel(parent=self.topBar)
        self.logoTitle.setGeometry(QtCore.QRect(47, 3, 90, 18))
        self.logoTitle.setStyleSheet("QLabel{\n"
"    color:#7E3A79;\n"
"    font-size:14px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.logoTitle.setObjectName("logoTitle")
        self.logoSub = QtWidgets.QLabel(parent=self.topBar)
        self.logoSub.setGeometry(QtCore.QRect(49, 18, 54, 10))
        self.logoSub.setStyleSheet("QLabel{\n"
"    color:#7A6D75;\n"
"    font-size:7px;\n"
"    font-weight:600;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.logoSub.setObjectName("logoSub")
        self.navHome = QtWidgets.QLabel(parent=self.topBar)
        self.navHome.setGeometry(QtCore.QRect(165, 8, 80, 18))
        self.navHome.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:9px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.navHome.setObjectName("navHome")
        self.navStats = QtWidgets.QLabel(parent=self.topBar)
        self.navStats.setGeometry(QtCore.QRect(280, 8, 84, 18))
        self.navStats.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:9px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.navStats.setObjectName("navStats")
        self.navChatbot = QtWidgets.QLabel(parent=self.topBar)
        self.navChatbot.setGeometry(QtCore.QRect(375, 8, 84, 18))
        self.navChatbot.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:9px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.navChatbot.setObjectName("navChatbot")
        self.notifIcon = QtWidgets.QLabel(parent=self.topBar)
        self.notifIcon.setGeometry(QtCore.QRect(670, 7, 18, 18))
        self.notifIcon.setStyleSheet("QLabel{\n"
"    font-size:13px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.notifIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.notifIcon.setObjectName("notifIcon")
        self.notifBadge = QtWidgets.QLabel(parent=self.topBar)
        self.notifBadge.setGeometry(QtCore.QRect(682, 6, 12, 12))
        self.notifBadge.setStyleSheet("QLabel{\n"
"    background:#E53935;\n"
"    color:white;\n"
"    border-radius:6px;\n"
"    font-size:7px;\n"
"    font-weight:800;\n"
"}")
        self.notifBadge.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.notifBadge.setObjectName("notifBadge")
        self.settingsIcon = QtWidgets.QLabel(parent=self.topBar)
        self.settingsIcon.setGeometry(QtCore.QRect(700, 7, 16, 18))
        self.settingsIcon.setStyleSheet("QLabel{\n"
"    font-size:13px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.settingsIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.settingsIcon.setObjectName("settingsIcon")
        self.userIcon = QtWidgets.QLabel(parent=self.topBar)
        self.userIcon.setGeometry(QtCore.QRect(720, 5, 18, 22))
        self.userIcon.setStyleSheet("QLabel{\n"
"    color:#2A2A2A;\n"
"    font-size:18px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.userIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.userIcon.setObjectName("userIcon")
        self.backLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.backLabel.setGeometry(QtCore.QRect(16, 55, 80, 18))
        self.backLabel.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:10px;\n"
"    font-weight:600;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.backLabel.setObjectName("backLabel")
        self.titleIcon = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.titleIcon.setGeometry(QtCore.QRect(24, 86, 40, 40))
        self.titleIcon.setStyleSheet("QLabel{\n"
"    font-size:24px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.titleIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleIcon.setObjectName("titleIcon")
        self.mainTitle = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.mainTitle.setGeometry(QtCore.QRect(78, 82, 280, 46))
        self.mainTitle.setStyleSheet("QLabel{\n"
"    color:#8A4E82;\n"
"    font-size:28px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.mainTitle.setObjectName("mainTitle")
        self.searchEdit = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.searchEdit.setGeometry(QtCore.QRect(18, 140, 484, 30))
        self.searchEdit.setStyleSheet("QLineEdit{\n"
"    background:white;\n"
"    border:1px solid #CFCFCF;\n"
"    padding-left:30px;\n"
"    color:#222;\n"
"    font-size:10px;\n"
"}")
        self.searchEdit.setObjectName("searchEdit")
        self.searchIcon = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.searchIcon.setGeometry(QtCore.QRect(29, 147, 16, 16))
        self.searchIcon.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:13px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.searchIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.searchIcon.setObjectName("searchIcon")
        self.categoryCombo = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.categoryCombo.setGeometry(QtCore.QRect(500, 140, 110, 30))
        self.categoryCombo.setStyleSheet("QComboBox{\n"
"    background:white;\n"
"    border:1px solid #CFCFCF;\n"
"    padding-left:8px;\n"
"    color:#222;\n"
"    font-size:10px;\n"
"}")
        self.categoryCombo.setObjectName("categoryCombo")
        self.categoryCombo.addItem("")
        self.searchButton = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.searchButton.setGeometry(QtCore.QRect(625, 140, 66, 30))
        self.searchButton.setStyleSheet("QPushButton{\n"
"    background:#FFF6FB;\n"
"    border:1px solid #7F4D7D;\n"
"    color:#222;\n"
"    font-size:10px;\n"
"    font-weight:700;\n"
"}")
        self.searchButton.setObjectName("searchButton")
        self.card30 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card30.setGeometry(QtCore.QRect(38, 214, 301, 261))
        self.card30.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card30.setObjectName("card30")
        self.card30Image = QtWidgets.QLabel(parent=self.card30)
        self.card30Image.setGeometry(QtCore.QRect(1, 1, 299, 128))
        self.card30Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card30Image.setPixmap(QtGui.QPixmap("AnSinh\\campaign30.png"))
        self.card30Image.setScaledContents(True)
        self.card30Image.setObjectName("card30Image")
        self.card30Title = QtWidgets.QLabel(parent=self.card30)
        self.card30Title.setGeometry(QtCore.QRect(12, 140, 276, 38))
        self.card30Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card30Title.setWordWrap(True)
        self.card30Title.setObjectName("card30Title")
        self.card30Date = QtWidgets.QLabel(parent=self.card30)
        self.card30Date.setGeometry(QtCore.QRect(16, 177, 145, 16))
        self.card30Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card30Date.setObjectName("card30Date")
        self.card30Owner = QtWidgets.QLabel(parent=self.card30)
        self.card30Owner.setGeometry(QtCore.QRect(16, 193, 160, 16))
        self.card30Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card30Owner.setObjectName("card30Owner")
        self.card30Money = QtWidgets.QLabel(parent=self.card30)
        self.card30Money.setGeometry(QtCore.QRect(18, 214, 210, 20))
        self.card30Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card30Money.setObjectName("card30Money")
        self.card30Progress = QtWidgets.QProgressBar(parent=self.card30)
        self.card30Progress.setGeometry(QtCore.QRect(18, 236, 244, 8))
        self.card30Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card30Progress.setProperty("value", 30)
        self.card30Progress.setTextVisible(False)
        self.card30Progress.setObjectName("card30Progress")
        self.card30More = QtWidgets.QLabel(parent=self.card30)
        self.card30More.setGeometry(QtCore.QRect(24, 240, 80, 16))
        self.card30More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card30More.setObjectName("card30More")
        self.card31 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card31.setGeometry(QtCore.QRect(382, 214, 301, 261))
        self.card31.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card31.setObjectName("card31")
        self.card31Image = QtWidgets.QLabel(parent=self.card31)
        self.card31Image.setGeometry(QtCore.QRect(1, 1, 299, 128))
        self.card31Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card31Image.setPixmap(QtGui.QPixmap("AnSinh\\campaign31.png"))
        self.card31Image.setScaledContents(True)
        self.card31Image.setObjectName("card31Image")
        self.card31Title = QtWidgets.QLabel(parent=self.card31)
        self.card31Title.setGeometry(QtCore.QRect(12, 136, 276, 42))
        self.card31Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card31Title.setWordWrap(True)
        self.card31Title.setObjectName("card31Title")
        self.card31Date = QtWidgets.QLabel(parent=self.card31)
        self.card31Date.setGeometry(QtCore.QRect(16, 177, 145, 16))
        self.card31Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card31Date.setObjectName("card31Date")
        self.card31Owner = QtWidgets.QLabel(parent=self.card31)
        self.card31Owner.setGeometry(QtCore.QRect(16, 193, 170, 16))
        self.card31Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card31Owner.setObjectName("card31Owner")
        self.card31Money = QtWidgets.QLabel(parent=self.card31)
        self.card31Money.setGeometry(QtCore.QRect(18, 214, 210, 20))
        self.card31Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card31Money.setObjectName("card31Money")
        self.card31Progress = QtWidgets.QProgressBar(parent=self.card31)
        self.card31Progress.setGeometry(QtCore.QRect(18, 236, 244, 8))
        self.card31Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card31Progress.setProperty("value", 30)
        self.card31Progress.setTextVisible(False)
        self.card31Progress.setObjectName("card31Progress")
        self.card31More = QtWidgets.QLabel(parent=self.card31)
        self.card31More.setGeometry(QtCore.QRect(24, 240, 80, 16))
        self.card31More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card31More.setObjectName("card31More")
        self.card32 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card32.setGeometry(QtCore.QRect(36, 508, 301, 261))
        self.card32.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card32.setObjectName("card32")
        self.card32Image = QtWidgets.QLabel(parent=self.card32)
        self.card32Image.setGeometry(QtCore.QRect(1, 1, 299, 128))
        self.card32Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card32Image.setPixmap(QtGui.QPixmap("AnSinh\\campaign32.png"))
        self.card32Image.setScaledContents(True)
        self.card32Image.setObjectName("card32Image")
        self.card32Title = QtWidgets.QLabel(parent=self.card32)
        self.card32Title.setGeometry(QtCore.QRect(12, 140, 276, 38))
        self.card32Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card32Title.setWordWrap(True)
        self.card32Title.setObjectName("card32Title")
        self.card32Date = QtWidgets.QLabel(parent=self.card32)
        self.card32Date.setGeometry(QtCore.QRect(16, 177, 145, 16))
        self.card32Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card32Date.setObjectName("card32Date")
        self.card32Owner = QtWidgets.QLabel(parent=self.card32)
        self.card32Owner.setGeometry(QtCore.QRect(16, 193, 160, 16))
        self.card32Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card32Owner.setObjectName("card32Owner")
        self.card32Money = QtWidgets.QLabel(parent=self.card32)
        self.card32Money.setGeometry(QtCore.QRect(18, 214, 210, 20))
        self.card32Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card32Money.setObjectName("card32Money")
        self.card32Progress = QtWidgets.QProgressBar(parent=self.card32)
        self.card32Progress.setGeometry(QtCore.QRect(18, 236, 244, 8))
        self.card32Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card32Progress.setProperty("value", 30)
        self.card32Progress.setTextVisible(False)
        self.card32Progress.setObjectName("card32Progress")
        self.card32More = QtWidgets.QLabel(parent=self.card32)
        self.card32More.setGeometry(QtCore.QRect(24, 240, 80, 16))
        self.card32More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card32More.setObjectName("card32More")
        self.card33 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card33.setGeometry(QtCore.QRect(380, 508, 301, 261))
        self.card33.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card33.setObjectName("card33")
        self.card33Image = QtWidgets.QLabel(parent=self.card33)
        self.card33Image.setGeometry(QtCore.QRect(1, 1, 299, 128))
        self.card33Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card33Image.setPixmap(QtGui.QPixmap("AnSinh\\campaign33.png"))
        self.card33Image.setScaledContents(True)
        self.card33Image.setObjectName("card33Image")
        self.card33Title = QtWidgets.QLabel(parent=self.card33)
        self.card33Title.setGeometry(QtCore.QRect(12, 140, 276, 38))
        self.card33Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card33Title.setWordWrap(True)
        self.card33Title.setObjectName("card33Title")
        self.card33Date = QtWidgets.QLabel(parent=self.card33)
        self.card33Date.setGeometry(QtCore.QRect(16, 177, 145, 16))
        self.card33Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card33Date.setObjectName("card33Date")
        self.card33Owner = QtWidgets.QLabel(parent=self.card33)
        self.card33Owner.setGeometry(QtCore.QRect(16, 193, 160, 16))
        self.card33Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card33Owner.setObjectName("card33Owner")
        self.card33Money = QtWidgets.QLabel(parent=self.card33)
        self.card33Money.setGeometry(QtCore.QRect(18, 214, 210, 20))
        self.card33Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card33Money.setObjectName("card33Money")
        self.card33Progress = QtWidgets.QProgressBar(parent=self.card33)
        self.card33Progress.setGeometry(QtCore.QRect(18, 236, 244, 8))
        self.card33Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card33Progress.setProperty("value", 30)
        self.card33Progress.setTextVisible(False)
        self.card33Progress.setObjectName("card33Progress")
        self.card33More = QtWidgets.QLabel(parent=self.card33)
        self.card33More.setGeometry(QtCore.QRect(24, 240, 80, 16))
        self.card33More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card33More.setObjectName("card33More")
        self.card34 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card34.setGeometry(QtCore.QRect(38, 800, 301, 261))
        self.card34.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card34.setObjectName("card34")
        self.card34Image = QtWidgets.QLabel(parent=self.card34)
        self.card34Image.setGeometry(QtCore.QRect(1, 1, 299, 128))
        self.card34Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card34Image.setPixmap(QtGui.QPixmap("AnSinh\\campaign34.png"))
        self.card34Image.setScaledContents(True)
        self.card34Image.setObjectName("card34Image")
        self.card34Title = QtWidgets.QLabel(parent=self.card34)
        self.card34Title.setGeometry(QtCore.QRect(12, 140, 276, 38))
        self.card34Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card34Title.setWordWrap(True)
        self.card34Title.setObjectName("card34Title")
        self.card34Date = QtWidgets.QLabel(parent=self.card34)
        self.card34Date.setGeometry(QtCore.QRect(16, 177, 145, 16))
        self.card34Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card34Date.setObjectName("card34Date")
        self.card34Owner = QtWidgets.QLabel(parent=self.card34)
        self.card34Owner.setGeometry(QtCore.QRect(16, 193, 140, 16))
        self.card34Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card34Owner.setObjectName("card34Owner")
        self.card34Money = QtWidgets.QLabel(parent=self.card34)
        self.card34Money.setGeometry(QtCore.QRect(18, 214, 210, 20))
        self.card34Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card34Money.setObjectName("card34Money")
        self.card34Progress = QtWidgets.QProgressBar(parent=self.card34)
        self.card34Progress.setGeometry(QtCore.QRect(18, 236, 244, 8))
        self.card34Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card34Progress.setProperty("value", 30)
        self.card34Progress.setTextVisible(False)
        self.card34Progress.setObjectName("card34Progress")
        self.card34More = QtWidgets.QLabel(parent=self.card34)
        self.card34More.setGeometry(QtCore.QRect(24, 240, 80, 16))
        self.card34More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card34More.setObjectName("card34More")
        self.card35 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card35.setGeometry(QtCore.QRect(382, 800, 301, 261))
        self.card35.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card35.setObjectName("card35")
        self.card35Image = QtWidgets.QLabel(parent=self.card35)
        self.card35Image.setGeometry(QtCore.QRect(1, 1, 299, 128))
        self.card35Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card35Image.setPixmap(QtGui.QPixmap("AnSinh\\campaign35.png"))
        self.card35Image.setScaledContents(True)
        self.card35Image.setObjectName("card35Image")
        self.card35Title = QtWidgets.QLabel(parent=self.card35)
        self.card35Title.setGeometry(QtCore.QRect(12, 140, 276, 38))
        self.card35Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card35Title.setWordWrap(True)
        self.card35Title.setObjectName("card35Title")
        self.card35Date = QtWidgets.QLabel(parent=self.card35)
        self.card35Date.setGeometry(QtCore.QRect(16, 177, 145, 16))
        self.card35Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card35Date.setObjectName("card35Date")
        self.card35Owner = QtWidgets.QLabel(parent=self.card35)
        self.card35Owner.setGeometry(QtCore.QRect(16, 193, 160, 16))
        self.card35Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card35Owner.setObjectName("card35Owner")
        self.card35Money = QtWidgets.QLabel(parent=self.card35)
        self.card35Money.setGeometry(QtCore.QRect(18, 214, 210, 20))
        self.card35Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card35Money.setObjectName("card35Money")
        self.card35Progress = QtWidgets.QProgressBar(parent=self.card35)
        self.card35Progress.setGeometry(QtCore.QRect(18, 236, 244, 8))
        self.card35Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card35Progress.setProperty("value", 30)
        self.card35Progress.setTextVisible(False)
        self.card35Progress.setObjectName("card35Progress")
        self.card35More = QtWidgets.QLabel(parent=self.card35)
        self.card35More.setGeometry(QtCore.QRect(24, 240, 80, 16))
        self.card35More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card35More.setObjectName("card35More")
        self.card36 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card36.setGeometry(QtCore.QRect(38, 1094, 301, 261))
        self.card36.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card36.setObjectName("card36")
        self.card36Image = QtWidgets.QLabel(parent=self.card36)
        self.card36Image.setGeometry(QtCore.QRect(1, 1, 299, 128))
        self.card36Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card36Image.setPixmap(QtGui.QPixmap("AnSinh\\campaign36.png"))
        self.card36Image.setScaledContents(True)
        self.card36Image.setObjectName("card36Image")
        self.card36Title = QtWidgets.QLabel(parent=self.card36)
        self.card36Title.setGeometry(QtCore.QRect(12, 140, 276, 38))
        self.card36Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card36Title.setWordWrap(True)
        self.card36Title.setObjectName("card36Title")
        self.card36Date = QtWidgets.QLabel(parent=self.card36)
        self.card36Date.setGeometry(QtCore.QRect(16, 177, 145, 16))
        self.card36Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card36Date.setObjectName("card36Date")
        self.card36Owner = QtWidgets.QLabel(parent=self.card36)
        self.card36Owner.setGeometry(QtCore.QRect(16, 193, 140, 16))
        self.card36Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card36Owner.setObjectName("card36Owner")
        self.card36Money = QtWidgets.QLabel(parent=self.card36)
        self.card36Money.setGeometry(QtCore.QRect(18, 214, 210, 20))
        self.card36Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card36Money.setObjectName("card36Money")
        self.card36Progress = QtWidgets.QProgressBar(parent=self.card36)
        self.card36Progress.setGeometry(QtCore.QRect(18, 236, 244, 8))
        self.card36Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card36Progress.setProperty("value", 30)
        self.card36Progress.setTextVisible(False)
        self.card36Progress.setObjectName("card36Progress")
        self.card36More = QtWidgets.QLabel(parent=self.card36)
        self.card36More.setGeometry(QtCore.QRect(24, 240, 80, 16))
        self.card36More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card36More.setObjectName("card36More")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "An sinh xã hội"))
        self.logoIcon.setText(_translate("MainWindow", "🕊"))
        self.logoTitle.setText(_translate("MainWindow", "Donarity"))
        self.logoSub.setText(_translate("MainWindow", "by group 10"))
        self.navHome.setText(_translate("MainWindow", "⌂ Trang chủ"))
        self.navStats.setText(_translate("MainWindow", "⌛ Thống kê"))
        self.navChatbot.setText(_translate("MainWindow", "◕Chatbot"))
        self.notifIcon.setText(_translate("MainWindow", "🔔"))
        self.notifBadge.setText(_translate("MainWindow", "0"))
        self.settingsIcon.setText(_translate("MainWindow", "⚙"))
        self.userIcon.setText(_translate("MainWindow", "◉"))
        self.backLabel.setText(_translate("MainWindow", "← Quay lại"))
        self.titleIcon.setText(_translate("MainWindow", "🤝"))
        self.mainTitle.setText(_translate("MainWindow", "An sinh xã hội"))
        self.searchEdit.setPlaceholderText(_translate("MainWindow", "Search for..."))
        self.searchIcon.setText(_translate("MainWindow", "⌕"))
        self.categoryCombo.setItemText(0, _translate("MainWindow", "All Categories"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.card30Title.setText(_translate("MainWindow", "Hỗ trợ nạn nhân Chất độc Da cam (VAVA)"))
        self.card30Date.setText(_translate("MainWindow", "Date:      2004-01-10"))
        self.card30Owner.setText(_translate("MainWindow", "Owner:   Nguyễn Văn Rinh"))
        self.card30Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card30More.setText(_translate("MainWindow", "Xem thêm"))
        self.card31Title.setText(_translate("MainWindow", "Nam Phương Foundation (Kiến tạo nhịp cầu)"))
        self.card31Date.setText(_translate("MainWindow", "Date:      2013-09-19"))
        self.card31Owner.setText(_translate("MainWindow", "Owner:   Đinh Thị Nam Phương"))
        self.card31Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card31More.setText(_translate("MainWindow", "Xem thêm"))
        self.card32Title.setText(_translate("MainWindow", "Quỹ Charity 2000 (Quán cơm 2.000đ)"))
        self.card32Date.setText(_translate("MainWindow", "Date:      2021-03-15"))
        self.card32Owner.setText(_translate("MainWindow", "Owner:   Nguyễn Minh Lộc"))
        self.card32Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card32More.setText(_translate("MainWindow", "Xem thêm"))
        self.card33Title.setText(_translate("MainWindow", "Cứu trợ lũ lụt Miền Trung (Phan Anh)"))
        self.card33Date.setText(_translate("MainWindow", "Date:      2020-10-20"))
        self.card33Owner.setText(_translate("MainWindow", "Owner:   Hoàng Phan Anh"))
        self.card33Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card33More.setText(_translate("MainWindow", "Xem thêm"))
        self.card34Title.setText(_translate("MainWindow", "Chương trình Vì phụ nữ nghèo nông thôn"))
        self.card34Date.setText(_translate("MainWindow", "Date:      2021-08-08"))
        self.card34Owner.setText(_translate("MainWindow", "Owner:   Hà Thị Nga"))
        self.card34Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card34More.setText(_translate("MainWindow", "Xem thêm"))
        self.card35Title.setText(_translate("MainWindow", "Chiến dịch Áo ấm mùa đông"))
        self.card35Date.setText(_translate("MainWindow", "Date:      2020-05-05"))
        self.card35Owner.setText(_translate("MainWindow", "Owner:   Nguyễn Ngọc Lương"))
        self.card35Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card35More.setText(_translate("MainWindow", "Xem thêm"))
        self.card36Title.setText(_translate("MainWindow", "Quỹ Tết cho người nghèo"))
        self.card36Date.setText(_translate("MainWindow", "Date:      2022-12-15"))
        self.card36Owner.setText(_translate("MainWindow", "Owner:   Phan Thu Hương"))
        self.card36Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card36More.setText(_translate("MainWindow", "Xem thêm"))
