# Form implementation generated from reading ui file 'C:\Users\ADMIN\PycharmProjects\DoAnKTLT\bao_cao.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 760)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 760))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 760))
        MainWindow.setStyleSheet("QMainWindow, QWidget {\n"
"    background: #FCF1F6;\n"
"    font-family: \"Segoe UI\";\n"
"    color: #2F2A2E;\n"
"    border: none;\n"
"}\n"
"\n"
"QWidget#centralwidget {\n"
"    background: #FCF1F6;\n"
"}\n"
"\n"
"QLabel#logoIcon {\n"
"    background: transparent;\n"
"    color: #94406F;\n"
"    font-size: 16pt;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"QLabel#logoText {\n"
"    background: transparent;\n"
"    color: #94406F;\n"
"    font-size: 17pt;\n"
"    font-weight: 800;\n"
"}\n"
"\n"
"QLabel#logoSubText {\n"
"    background: transparent;\n"
"    color: #A58A98;\n"
"    font-size: 7pt;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton#backButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #111111;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"    text-align: left;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QPushButton#backButton:hover {\n"
"    color: #7A4A64;\n"
"}\n"
"\n"
"QLabel#titleLabel {\n"
"    background: transparent;\n"
"    color: #2F2A2E;\n"
"    font-size: 25pt;\n"
"    font-weight: 800;\n"
"}\n"
"\n"
"QLabel#cloud1, QLabel#cloud2, QLabel#cloud3, QLabel#cloud4 {\n"
"    background: transparent;\n"
"    color: #FBE9EF;\n"
"    border-radius: 999px;\n"
"}\n"
"\n"
"QLabel#cloud1 {\n"
"    background: qradialgradient(cx:0.4, cy:0.35, radius:0.9, fx:0.35, fy:0.3,\n"
"                                stop:0 #FFFDFE, stop:0.55 #FCECF2, stop:1 #F7D5E1);\n"
"}\n"
"QLabel#cloud2 {\n"
"    background: qradialgradient(cx:0.45, cy:0.35, radius:0.95, fx:0.38, fy:0.28,\n"
"                                stop:0 #FFFDFE, stop:0.58 #FCEAF1, stop:1 #F7D2DE);\n"
"}\n"
"QLabel#cloud3 {\n"
"    background: qradialgradient(cx:0.45, cy:0.35, radius:0.95, fx:0.38, fy:0.28,\n"
"                                stop:0 #FFFDFE, stop:0.58 #FCEAF1, stop:1 #F7D2DE);\n"
"}\n"
"QLabel#cloud4 {\n"
"    background: qradialgradient(cx:0.45, cy:0.35, radius:0.95, fx:0.38, fy:0.28,\n"
"                                stop:0 #FFFDFE, stop:0.58 #FCEAF1, stop:1 #F7D2DE);\n"
"}\n"
"\n"
"QLabel#spark1, QLabel#spark2, QLabel#spark3 {\n"
"    background: transparent;\n"
"    color: #F4B5C8;\n"
"    font-size: 12pt;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"QLabel#dot1, QLabel#dot2, QLabel#dot3 {\n"
"    background: #FCE7EF;\n"
"    border-radius: 4px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logoGroup = QtWidgets.QWidget(parent=self.centralwidget)
        self.logoGroup.setGeometry(QtCore.QRect(28, 10, 165, 40))
        self.logoGroup.setObjectName("logoGroup")
        self.logoIcon = QtWidgets.QLabel(parent=self.logoGroup)
        self.logoIcon.setGeometry(QtCore.QRect(0, 1, 24, 22))
        self.logoIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoIcon.setObjectName("logoIcon")
        self.logoText = QtWidgets.QLabel(parent=self.logoGroup)
        self.logoText.setGeometry(QtCore.QRect(20, 0, 95, 22))
        self.logoText.setObjectName("logoText")
        self.logoSubText = QtWidgets.QLabel(parent=self.logoGroup)
        self.logoSubText.setGeometry(QtCore.QRect(23, 16, 50, 12))
        self.logoSubText.setObjectName("logoSubText")
        self.backButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(25, 58, 80, 20))
        self.backButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.backButton.setObjectName("backButton")
        self.titleLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(0, 92, 1200, 46))
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.cloud1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.cloud1.setGeometry(QtCore.QRect(1010, 624, 145, 88))
        self.cloud1.setText("")
        self.cloud1.setObjectName("cloud1")
        self.cloud2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.cloud2.setGeometry(QtCore.QRect(935, 654, 130, 78))
        self.cloud2.setText("")
        self.cloud2.setObjectName("cloud2")
        self.cloud3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.cloud3.setGeometry(QtCore.QRect(1065, 668, 118, 70))
        self.cloud3.setText("")
        self.cloud3.setObjectName("cloud3")
        self.cloud4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.cloud4.setGeometry(QtCore.QRect(860, 686, 150, 78))
        self.cloud4.setText("")
        self.cloud4.setObjectName("cloud4")
        self.spark1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.spark1.setGeometry(QtCore.QRect(1002, 610, 16, 16))
        self.spark1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spark1.setObjectName("spark1")
        self.spark2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.spark2.setGeometry(QtCore.QRect(1078, 596, 10, 10))
        self.spark2.setStyleSheet("background: transparent; color: #F9D5E1; font-size: 8pt; font-weight: 700;")
        self.spark2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spark2.setObjectName("spark2")
        self.spark3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.spark3.setGeometry(QtCore.QRect(1125, 618, 10, 10))
        self.spark3.setStyleSheet("background: transparent; color: #F9D5E1; font-size: 8pt; font-weight: 700;")
        self.spark3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spark3.setObjectName("spark3")
        self.dot1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.dot1.setGeometry(QtCore.QRect(1100, 702, 8, 8))
        self.dot1.setText("")
        self.dot1.setObjectName("dot1")
        self.dot2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.dot2.setGeometry(QtCore.QRect(1040, 724, 8, 8))
        self.dot2.setText("")
        self.dot2.setObjectName("dot2")
        self.dot3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.dot3.setGeometry(QtCore.QRect(1160, 690, 8, 8))
        self.dot3.setText("")
        self.dot3.setObjectName("dot3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Donarity - Báo cáo"))
        self.logoIcon.setText(_translate("MainWindow", "🕊"))
        self.logoText.setText(_translate("MainWindow", "Donarity"))
        self.logoSubText.setText(_translate("MainWindow", "by group 10"))
        self.backButton.setText(_translate("MainWindow", "← Quay lại"))
        self.titleLabel.setText(_translate("MainWindow", "Bạn muốn báo cáo ?"))
        self.spark1.setText(_translate("MainWindow", "✦"))
        self.spark2.setText(_translate("MainWindow", "•"))
        self.spark3.setText(_translate("MainWindow", "•"))
