# Form implementation generated from reading ui file 'c:\Users\ADMIN\OneDrive\Documents\UEL.ktlt\BaiDuAn\dangki.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 900)
        MainWindow.setMaximumSize(QtCore.QSize(1200, 900))
        MainWindow.setStyleSheet("QMainWindow, QWidget{\n"
"    background: #FFF3F9;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background: #FFF3F9;")
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1200, 760))
        self.scrollArea.setStyleSheet("QScrollArea{\n"
"    selection-color: rgb(255, 0, 127);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    background: #FFF3F9;\n"
"}\n"
"QScrollBar:vertical {\n"
"    background: #FBE5F0;\n"
"    width: 12px;\n"
"    margin: 0px;\n"
"    border-radius: 6px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #E8B8D0;\n"
"    min-height: 30px;\n"
"    border-radius: 6px;\n"
"}\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -360, 1183, 1120))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(1180, 1120))
        self.scrollAreaWidgetContents.setStyleSheet("background: #FFF3F9;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.logo_icon = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.logo_icon.setGeometry(QtCore.QRect(8, 10, 62, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.logo_icon.setFont(font)
        self.logo_icon.setStyleSheet("QLabel{\n"
"background: transparent;\n"
"color: #7A2D6A;\n"
"border: none;\n"
"}")
        self.logo_icon.setObjectName("logo_icon")
        self.logo_title = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.logo_title.setGeometry(QtCore.QRect(54, 10, 180, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.logo_title.setFont(font)
        self.logo_title.setStyleSheet("QLabel{\n"
"color: #7A2D6A;\n"
"background: transparent;\n"
"border: none;\n"
"}")
        self.logo_title.setObjectName("logo_title")
        self.logo_subtitle = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.logo_subtitle.setGeometry(QtCore.QRect(96, 42, 90, 14))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        self.logo_subtitle.setFont(font)
        self.logo_subtitle.setStyleSheet("QLabel{\n"
"color: #A08A96;\n"
"background: transparent;\n"
"border: none;\n"
"}")
        self.logo_subtitle.setObjectName("logo_subtitle")
        self.back = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.back.setGeometry(QtCore.QRect(16, 84, 121, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.back.setFont(font)
        self.back.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.back.setStyleSheet("QPushButton{\n"
"background: transparent;\n"
"border: none;\n"
"color: #111111;\n"
"text-align: left;\n"
"padding-left: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"color: #7A2D6A;\n"
"}")
        self.back.setObjectName("back")
        self.title_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.title_label.setGeometry(QtCore.QRect(286, 68, 440, 56))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("QLabel{\n"
"color: #232323;\n"
"background: transparent;\n"
"border: none;\n"
"}")
        self.title_label.setObjectName("title_label")
        self.form_card = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.form_card.setGeometry(QtCore.QRect(235, 145, 560, 691))
        self.form_card.setStyleSheet("QFrame{\n"
"background: #FBE2EE;\n"
"border: none;\n"
"border-radius: 38px;\n"
"}")
        self.form_card.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.form_card.setObjectName("form_card")
        self.label_name = QtWidgets.QLabel(parent=self.form_card)
        self.label_name.setGeometry(QtCore.QRect(95, 28, 120, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_name.setFont(font)
        self.label_name.setStyleSheet("QLabel{\n"
"color: #5C4D55;\n"
"background: transparent;\n"
"}")
        self.label_name.setObjectName("label_name")
        self.NhapHoVaTen = QtWidgets.QLineEdit(parent=self.form_card)
        self.NhapHoVaTen.setGeometry(QtCore.QRect(95, 53, 380, 42))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.NhapHoVaTen.setFont(font)
        self.NhapHoVaTen.setStyleSheet("QLineEdit{\n"
"background: #F5F5F5;\n"
"border: none;\n"
"border-radius: 3px;\n"
"padding-left: 12px;\n"
"color: #555555;\n"
"}\n"
"QLineEdit::placeholder{\n"
"color: #999999;\n"
"}")
        self.NhapHoVaTen.setObjectName("NhapHoVaTen")
        self.label_cccd = QtWidgets.QLabel(parent=self.form_card)
        self.label_cccd.setGeometry(QtCore.QRect(95, 110, 150, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_cccd.setFont(font)
        self.label_cccd.setStyleSheet("QLabel{\n"
"color: #5C4D55;\n"
"background: transparent;\n"
"}")
        self.label_cccd.setObjectName("label_cccd")
        self.NhapCCCD = QtWidgets.QLineEdit(parent=self.form_card)
        self.NhapCCCD.setGeometry(QtCore.QRect(95, 135, 380, 42))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.NhapCCCD.setFont(font)
        self.NhapCCCD.setStyleSheet("QLineEdit{\n"
"background: #F5F5F5;\n"
"border: none;\n"
"border-radius: 3px;\n"
"padding-left: 12px;\n"
"color: #555555;\n"
"}\n"
"QLineEdit::placeholder{\n"
"color: #999999;\n"
"}")
        self.NhapCCCD.setObjectName("NhapCCCD")
        self.label_email = QtWidgets.QLabel(parent=self.form_card)
        self.label_email.setGeometry(QtCore.QRect(95, 192, 80, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_email.setFont(font)
        self.label_email.setStyleSheet("QLabel{\n"
"color: #5C4D55;\n"
"background: transparent;\n"
"}")
        self.label_email.setObjectName("label_email")
        self.NhapEmail = QtWidgets.QLineEdit(parent=self.form_card)
        self.NhapEmail.setGeometry(QtCore.QRect(95, 217, 380, 42))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.NhapEmail.setFont(font)
        self.NhapEmail.setStyleSheet("QLineEdit{\n"
"background: #F5F5F5;\n"
"border: none;\n"
"border-radius: 3px;\n"
"padding-left: 12px;\n"
"color: #555555;\n"
"}\n"
"QLineEdit::placeholder{\n"
"color: #999999;\n"
"}")
        self.NhapEmail.setObjectName("NhapEmail")
        self.label_phone = QtWidgets.QLabel(parent=self.form_card)
        self.label_phone.setGeometry(QtCore.QRect(95, 274, 100, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_phone.setFont(font)
        self.label_phone.setStyleSheet("QLabel{\n"
"color: #5C4D55;\n"
"background: transparent;\n"
"}")
        self.label_phone.setObjectName("label_phone")
        self.NhapSdt = QtWidgets.QLineEdit(parent=self.form_card)
        self.NhapSdt.setGeometry(QtCore.QRect(95, 299, 380, 42))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.NhapSdt.setFont(font)
        self.NhapSdt.setStyleSheet("QLineEdit{\n"
"background: #F5F5F5;\n"
"border: none;\n"
"border-radius: 3px;\n"
"padding-left: 12px;\n"
"color: #555555;\n"
"}\n"
"QLineEdit::placeholder{\n"
"color: #999999;\n"
"}")
        self.NhapSdt.setObjectName("NhapSdt")
        self.label_gender = QtWidgets.QLabel(parent=self.form_card)
        self.label_gender.setGeometry(QtCore.QRect(95, 355, 70, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_gender.setFont(font)
        self.label_gender.setStyleSheet("QLabel{\n"
"color: #5C4D55;\n"
"background: transparent;\n"
"}")
        self.label_gender.setObjectName("label_gender")
        self.radNam = QtWidgets.QRadioButton(parent=self.form_card)
        self.radNam.setGeometry(QtCore.QRect(205, 382, 70, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.radNam.setFont(font)
        self.radNam.setStyleSheet("QRadioButton{\n"
"background: transparent;\n"
"color: #6A5B63;\n"
"spacing: 6px;\n"
"}\n"
"QRadioButton::indicator{\n"
"width: 14px;\n"
"height: 14px;\n"
"border-radius: 7px;\n"
"background: #FFFFFF;\n"
"border: 1px solid #FFFFFF;\n"
"}\n"
"QRadioButton::indicator:checked{\n"
"background: #F29AC4;\n"
"border: 1px solid #FFFFFF;\n"
"}")
        self.radNam.setObjectName("radNam")
        self.radNu = QtWidgets.QRadioButton(parent=self.form_card)
        self.radNu.setGeometry(QtCore.QRect(285, 382, 70, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.radNu.setFont(font)
        self.radNu.setStyleSheet("QRadioButton{\n"
"background: transparent;\n"
"color: #6A5B63;\n"
"spacing: 6px;\n"
"}\n"
"QRadioButton::indicator{\n"
"width: 14px;\n"
"height: 14px;\n"
"border-radius: 7px;\n"
"background: #FFFFFF;\n"
"border: 1px solid #FFFFFF;\n"
"}\n"
"QRadioButton::indicator:checked{\n"
"background: #F29AC4;\n"
"border: 1px solid #FFFFFF;\n"
"}")
        self.radNu.setObjectName("radNu")
        self.label_address = QtWidgets.QLabel(parent=self.form_card)
        self.label_address.setGeometry(QtCore.QRect(95, 438, 60, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_address.setFont(font)
        self.label_address.setStyleSheet("QLabel{\n"
"color: #5C4D55;\n"
"background: transparent;\n"
"}")
        self.label_address.setObjectName("label_address")
        self.NhapAddress = QtWidgets.QLineEdit(parent=self.form_card)
        self.NhapAddress.setGeometry(QtCore.QRect(95, 463, 380, 42))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.NhapAddress.setFont(font)
        self.NhapAddress.setStyleSheet("QLineEdit{\n"
"background: #F5F5F5;\n"
"border: none;\n"
"border-radius: 3px;\n"
"padding-left: 12px;\n"
"color: #555555;\n"
"}\n"
"QLineEdit::placeholder{\n"
"color: #999999;\n"
"}")
        self.NhapAddress.setObjectName("NhapAddress")
        self.label_birth = QtWidgets.QLabel(parent=self.form_card)
        self.label_birth.setGeometry(QtCore.QRect(95, 520, 70, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_birth.setFont(font)
        self.label_birth.setStyleSheet("QLabel{\n"
"color: #5C4D55;\n"
"background: transparent;\n"
"}")
        self.label_birth.setObjectName("label_birth")
        self.label_day = QtWidgets.QLabel(parent=self.form_card)
        self.label_day.setGeometry(QtCore.QRect(150, 551, 32, 20))
        self.label_day.setStyleSheet("QLabel{\n"
"background: transparent;\n"
"color: #7B6A73;\n"
"}")
        self.label_day.setObjectName("label_day")
        self.NhapDay = QtWidgets.QLineEdit(parent=self.form_card)
        self.NhapDay.setGeometry(QtCore.QRect(190, 548, 48, 26))
        self.NhapDay.setStyleSheet("QLineEdit{\n"
"background: #F5F5F5;\n"
"border: none;\n"
"border-radius: 3px;\n"
"padding-left: 6px;\n"
"}")
        self.NhapDay.setObjectName("NhapDay")
        self.label_month = QtWidgets.QLabel(parent=self.form_card)
        self.label_month.setGeometry(QtCore.QRect(247, 551, 42, 20))
        self.label_month.setStyleSheet("QLabel{\n"
"background: transparent;\n"
"color: #7B6A73;\n"
"}")
        self.label_month.setObjectName("label_month")
        self.NhapMonth = QtWidgets.QLineEdit(parent=self.form_card)
        self.NhapMonth.setGeometry(QtCore.QRect(298, 548, 48, 26))
        self.NhapMonth.setStyleSheet("QLineEdit{\n"
"background: #F5F5F5;\n"
"border: none;\n"
"border-radius: 3px;\n"
"padding-left: 6px;\n"
"}")
        self.NhapMonth.setObjectName("NhapMonth")
        self.label_year = QtWidgets.QLabel(parent=self.form_card)
        self.label_year.setGeometry(QtCore.QRect(358, 551, 32, 20))
        self.label_year.setStyleSheet("QLabel{\n"
"background: transparent;\n"
"color: #7B6A73;\n"
"}")
        self.label_year.setObjectName("label_year")
        self.NhapYear = QtWidgets.QLineEdit(parent=self.form_card)
        self.NhapYear.setGeometry(QtCore.QRect(400, 548, 70, 26))
        self.NhapYear.setStyleSheet("QLineEdit{\n"
"background: #F5F5F5;\n"
"border: none;\n"
"border-radius: 3px;\n"
"padding-left: 6px;\n"
"}")
        self.NhapYear.setObjectName("NhapYear")
        self.label_password_1 = QtWidgets.QLabel(parent=self.form_card)
        self.label_password_1.setGeometry(QtCore.QRect(95, 610, 90, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_password_1.setFont(font)
        self.label_password_1.setStyleSheet("QLabel{\n"
"color: #5C4D55;\n"
"background: transparent;\n"
"}")
        self.label_password_1.setObjectName("label_password_1")
        self.NhapMatKhau = QtWidgets.QLineEdit(parent=self.form_card)
        self.NhapMatKhau.setGeometry(QtCore.QRect(95, 635, 380, 42))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.NhapMatKhau.setFont(font)
        self.NhapMatKhau.setStyleSheet("QLineEdit{\n"
"background: #F5F5F5;\n"
"border: none;\n"
"border-radius: 3px;\n"
"padding-left: 12px;\n"
"color: #555555;\n"
"}\n"
"QLineEdit::placeholder{\n"
"color: #999999;\n"
"}")
        self.NhapMatKhau.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.NhapMatKhau.setObjectName("NhapMatKhau")
        self.label_password_2 = QtWidgets.QLabel(parent=self.form_card)
        self.label_password_2.setGeometry(QtCore.QRect(95, 690, 100, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_password_2.setFont(font)
        self.label_password_2.setStyleSheet("QLabel{\n"
"color: #5C4D55;\n"
"background: transparent;\n"
"}")
        self.label_password_2.setObjectName("label_password_2")
        self.txt_repassword = QtWidgets.QLineEdit(parent=self.form_card)
        self.txt_repassword.setGeometry(QtCore.QRect(95, 715, 380, 42))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.txt_repassword.setFont(font)
        self.txt_repassword.setStyleSheet("QLineEdit{\n"
"background: #F5F5F5;\n"
"border: none;\n"
"border-radius: 3px;\n"
"padding-left: 12px;\n"
"color: #555555;\n"
"}\n"
"QLineEdit::placeholder{\n"
"color: #999999;\n"
"}")
        self.txt_repassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.txt_repassword.setObjectName("txt_repassword")
        self.bottom_pink = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.bottom_pink.setGeometry(QtCore.QRect(0, 845, 1185, 275))
        self.bottom_pink.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.bottom_pink.setStyleSheet("QFrame{\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #FBE4EF, stop:1 #FFE5F2);\n"
"border: none;\n"
"}\n"
"    background-color: rgb(255, 0, 127);")
        self.bottom_pink.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.bottom_pink.setObjectName("bottom_pink")
        self.cloud1 = QtWidgets.QFrame(parent=self.bottom_pink)
        self.cloud1.setGeometry(QtCore.QRect(-20, 120, 220, 120))
        self.cloud1.setStyleSheet("QFrame{\n"
"background: rgba(255, 236, 245, 190);\n"
"border-radius: 60px;\n"
"}")
        self.cloud1.setObjectName("cloud1")
        self.cloud2 = QtWidgets.QFrame(parent=self.bottom_pink)
        self.cloud2.setGeometry(QtCore.QRect(130, 140, 260, 120))
        self.cloud2.setStyleSheet("QFrame{\n"
"background: rgba(255, 236, 245, 180);\n"
"border-radius: 60px;\n"
"}")
        self.cloud2.setObjectName("cloud2")
        self.cloud3 = QtWidgets.QFrame(parent=self.bottom_pink)
        self.cloud3.setGeometry(QtCore.QRect(340, 150, 300, 120))
        self.cloud3.setStyleSheet("QFrame{\n"
"background: rgba(255, 238, 247, 180);\n"
"border-radius: 60px;\n"
"}")
        self.cloud3.setObjectName("cloud3")
        self.cloud4 = QtWidgets.QFrame(parent=self.bottom_pink)
        self.cloud4.setGeometry(QtCore.QRect(610, 135, 270, 130))
        self.cloud4.setStyleSheet("QFrame{\n"
"background: rgba(255, 240, 248, 175);\n"
"border-radius: 65px;\n"
"}")
        self.cloud4.setObjectName("cloud4")
        self.cloud5 = QtWidgets.QFrame(parent=self.bottom_pink)
        self.cloud5.setGeometry(QtCore.QRect(850, 145, 250, 120))
        self.cloud5.setStyleSheet("QFrame{\n"
"background: rgba(255, 238, 247, 185);\n"
"border-radius: 60px;\n"
"}")
        self.cloud5.setObjectName("cloud5")
        self.NutDangKi = QtWidgets.QPushButton(parent=self.bottom_pink)
        self.NutDangKi.setGeometry(QtCore.QRect(420, 10, 160, 46))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.NutDangKi.setFont(font)
        self.NutDangKi.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.NutDangKi.setStyleSheet("QPushButton{\n"
"background: #FFF1F8;\n"
"color: #E08AB8;\n"
"border: none;\n"
"border-radius: 23px;\n"
"}\n"
"QPushButton:hover{\n"
"background: #FFE9F4;\n"
"}\n"
"QPushButton:pressed{\n"
"background: #F8DCEA;\n"
"}")
        self.NutDangKi.setObjectName("NutDangKi")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Đăng kí tài khoản"))
        self.logo_icon.setText(_translate("MainWindow", "🕊"))
        self.logo_title.setText(_translate("MainWindow", "Donarity"))
        self.logo_subtitle.setText(_translate("MainWindow", "by group 10"))
        self.back.setText(_translate("MainWindow", "← Quay lại"))
        self.title_label.setText(_translate("MainWindow", "Đăng kí tài khoản"))
        self.label_name.setText(_translate("MainWindow", "Họ và tên"))
        self.NhapHoVaTen.setPlaceholderText(_translate("MainWindow", "Nhập họ và tên"))
        self.label_cccd.setText(_translate("MainWindow", "Căn cước công dân"))
        self.NhapCCCD.setPlaceholderText(_translate("MainWindow", "Nhập số căn cước"))
        self.label_email.setText(_translate("MainWindow", "Email"))
        self.NhapEmail.setPlaceholderText(_translate("MainWindow", "Nhập email"))
        self.label_phone.setText(_translate("MainWindow", "Số điện thoại"))
        self.NhapSdt.setPlaceholderText(_translate("MainWindow", "Nhập số điện thoại"))
        self.label_gender.setText(_translate("MainWindow", "Giới tính"))
        self.radNam.setText(_translate("MainWindow", "Nam"))
        self.radNu.setText(_translate("MainWindow", "Nữ"))
        self.label_address.setText(_translate("MainWindow", "Địa chỉ"))
        self.NhapAddress.setPlaceholderText(_translate("MainWindow", "Nhập địa chỉ"))
        self.label_birth.setText(_translate("MainWindow", "Ngày sinh"))
        self.label_day.setText(_translate("MainWindow", "Day"))
        self.label_month.setText(_translate("MainWindow", "Month"))
        self.label_year.setText(_translate("MainWindow", "Year"))
        self.label_password_1.setText(_translate("MainWindow", "Mật khẩu"))
        self.NhapMatKhau.setPlaceholderText(_translate("MainWindow", "Nhập mật khẩu"))
        self.label_password_2.setText(_translate("MainWindow", "Mật khẩu"))
        self.txt_repassword.setPlaceholderText(_translate("MainWindow", "Nhập lại mật khẩu"))
        self.NutDangKi.setText(_translate("MainWindow", "Đăng kí ngay"))
