# Form implementation generated from reading ui file 'c:\Users\ADMIN\OneDrive\Documents\UEL.ktlt\BaiDuAn\dangnhap.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 536)
        MainWindow.setMinimumSize(QtCore.QSize(796, 536))
        MainWindow.setMaximumSize(QtCore.QSize(796, 536))
        MainWindow.setStyleSheet("background-color: rgb(255, 243, 249);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 243, 249);")
        self.centralwidget.setObjectName("centralwidget")
        self.main_bg = QtWidgets.QFrame(parent=self.centralwidget)
        self.main_bg.setGeometry(QtCore.QRect(0, -10, 1200, 900))
        self.main_bg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.main_bg.setStyleSheet("QFrame{\n"
"    background-color: #FFF3F9;\n"
"    border: none;\n"
"}")
        self.main_bg.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.main_bg.setObjectName("main_bg")
        self.left_card = QtWidgets.QFrame(parent=self.main_bg)
        self.left_card.setGeometry(QtCore.QRect(16, 12, 440, 494))
        self.left_card.setStyleSheet("QFrame{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"}")
        self.left_card.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.left_card.setObjectName("left_card")
        self.label_image = QtWidgets.QLabel(parent=self.left_card)
        self.label_image.setGeometry(QtCore.QRect(0, 0, 401, 494))
        self.label_image.setStyleSheet("QLabel{\n"
"    border-radius: 20px;\n"
"    background-color: #d8c7d1;\n"
"}")
        self.label_image.setText("")
        self.label_image.setPixmap(QtGui.QPixmap("c:\\Users\\ADMIN\\OneDrive\\Documents\\UEL.ktlt\\BaiDuAn\\welcome_children.png"))
        self.label_image.setScaledContents(True)
        self.label_image.setObjectName("label_image")
        self.overlay = QtWidgets.QFrame(parent=self.left_card)
        self.overlay.setGeometry(QtCore.QRect(0, 0, 401, 494))
        self.overlay.setStyleSheet("QFrame{\n"
"    background-color: rgba(116, 79, 102, 85);\n"
"    border-radius: 20px;\n"
"}")
        self.overlay.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.overlay.setObjectName("overlay")
        self.label_2 = QtWidgets.QLabel(parent=self.overlay)
        self.label_2.setGeometry(QtCore.QRect(-10, -10, 551, 521))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("c:\\Users\\ADMIN\\OneDrive\\Documents\\UEL.ktlt\\BaiDuAn\\../../../../Downloads/19b4d4f6540ada54831b.jpg"))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(parent=self.left_card)
        self.label.setGeometry(QtCore.QRect(160, 370, 47, 13))
        self.label.setText("")
        self.label.setObjectName("label")
        self.logo_icon = QtWidgets.QLabel(parent=self.main_bg)
        self.logo_icon.setGeometry(QtCore.QRect(515, 18, 42, 34))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.logo_icon.setFont(font)
        self.logo_icon.setStyleSheet("QLabel{\n"
"    background: transparent;\n"
"    color: #7D2B6E;\n"
"    border: none;\n"
"}")
        self.logo_icon.setObjectName("logo_icon")
        self.logo_title = QtWidgets.QLabel(parent=self.main_bg)
        self.logo_title.setGeometry(QtCore.QRect(552, 10, 170, 42))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.logo_title.setFont(font)
        self.logo_title.setStyleSheet("QLabel{\n"
"    color: #7D2B6E;\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.logo_title.setObjectName("logo_title")
        self.logo_subtitle = QtWidgets.QLabel(parent=self.main_bg)
        self.logo_subtitle.setGeometry(QtCore.QRect(633, 40, 80, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.logo_subtitle.setFont(font)
        self.logo_subtitle.setStyleSheet("QLabel{\n"
"    color: #8F7B87;\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.logo_subtitle.setObjectName("logo_subtitle")
        self.welcome_label = QtWidgets.QLabel(parent=self.main_bg)
        self.welcome_label.setGeometry(QtCore.QRect(500, 108, 240, 68))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.welcome_label.setFont(font)
        self.welcome_label.setStyleSheet("QLabel{\n"
"    color: #111111;\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.welcome_label.setObjectName("welcome_label")
        self.label_login = QtWidgets.QLabel(parent=self.main_bg)
        self.label_login.setGeometry(QtCore.QRect(490, 196, 80, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_login.setFont(font)
        self.label_login.setStyleSheet("QLabel{\n"
"    color: #2C2026;\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.label_login.setObjectName("label_login")
        self.NhapSoDt = QtWidgets.QLineEdit(parent=self.main_bg)
        self.NhapSoDt.setGeometry(QtCore.QRect(490, 219, 264, 46))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.NhapSoDt.setFont(font)
        self.NhapSoDt.setStyleSheet("QLineEdit{\n"
"    background-color: #F4F4F4;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding-left: 10px;\n"
"    color: #444444;\n"
"}\n"
"QLineEdit::placeholder{\n"
"    color: #919191;\n"
"}")
        self.NhapSoDt.setObjectName("NhapSoDt")
        self.label_password = QtWidgets.QLabel(parent=self.main_bg)
        self.label_password.setGeometry(QtCore.QRect(490, 286, 70, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_password.setFont(font)
        self.label_password.setStyleSheet("QLabel{\n"
"    color: #2C2026;\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.label_password.setObjectName("label_password")
        self.NhapMatKhau = QtWidgets.QLineEdit(parent=self.main_bg)
        self.NhapMatKhau.setGeometry(QtCore.QRect(490, 311, 264, 46))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.NhapMatKhau.setFont(font)
        self.NhapMatKhau.setStyleSheet("QLineEdit{\n"
"    background-color: #F4F4F4;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding-left: 10px;\n"
"    color: #444444;\n"
"}\n"
"QLineEdit::placeholder{\n"
"    color: #919191;\n"
"}")
        self.NhapMatKhau.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.NhapMatKhau.setObjectName("NhapMatKhau")
        self.radQuyenGop = QtWidgets.QRadioButton(parent=self.main_bg)
        self.radQuyenGop.setGeometry(QtCore.QRect(492, 370, 100, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.radQuyenGop.setFont(font)
        self.radQuyenGop.setStyleSheet("QRadioButton{\n"
"    color: #3B2B34;\n"
"    background: transparent;\n"
"    spacing: 8px;\n"
"}\n"
"QRadioButton::indicator{\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 8px;\n"
"    background-color: #FFFDFE;\n"
"    border: 1px solid #FFFDFE;\n"
"}\n"
"QRadioButton::indicator:checked{\n"
"    background-color: #F2A0C6;\n"
"    border: 1px solid #FFFDFE;\n"
"}")
        self.radQuyenGop.setObjectName("radQuyenGop")
        self.radChuChienDich = QtWidgets.QRadioButton(parent=self.main_bg)
        self.radChuChienDich.setGeometry(QtCore.QRect(627, 370, 120, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.radChuChienDich.setFont(font)
        self.radChuChienDich.setStyleSheet("QRadioButton{\n"
"    color: #3B2B34;\n"
"    background: transparent;\n"
"    spacing: 8px;\n"
"}\n"
"QRadioButton::indicator{\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 8px;\n"
"    background-color: #FFFDFE;\n"
"    border: 1px solid #FFFDFE;\n"
"}\n"
"QRadioButton::indicator:checked{\n"
"    background-color: #F2A0C6;\n"
"    border: 1px solid #FFFDFE;\n"
"}")
        self.radChuChienDich.setChecked(False)
        self.radChuChienDich.setObjectName("radChuChienDich")
        self.label_no_account = QtWidgets.QLabel(parent=self.main_bg)
        self.label_no_account.setGeometry(QtCore.QRect(490, 418, 142, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_no_account.setFont(font)
        self.label_no_account.setStyleSheet("QLabel{\n"
"    color: #2D2328;\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.label_no_account.setObjectName("label_no_account")
        self.NutDangKi = QtWidgets.QLabel(parent=self.main_bg)
        self.NutDangKi.setGeometry(QtCore.QRect(664, 418, 92, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.NutDangKi.setFont(font)
        self.NutDangKi.setStyleSheet("QLabel{\n"
"    color: #D98DB8;\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.NutDangKi.setObjectName("NutDangKi")
        self.NutDangNhap = QtWidgets.QPushButton(parent=self.main_bg)
        self.NutDangNhap.setGeometry(QtCore.QRect(558, 462, 128, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.NutDangNhap.setFont(font)
        self.NutDangNhap.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.NutDangNhap.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"    color: #D88DB8;\n"
"    border: 1.5px solid #B76A98;\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(216, 141, 184, 20);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgba(216, 141, 184, 35);\n"
"}")
        self.NutDangNhap.setObjectName("NutDangNhap")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Donarity"))
        self.logo_icon.setText(_translate("MainWindow", "🕊"))
        self.logo_title.setText(_translate("MainWindow", "Donarity"))
        self.logo_subtitle.setText(_translate("MainWindow", "by group 10"))
        self.welcome_label.setText(_translate("MainWindow", "WELCOME"))
        self.label_login.setText(_translate("MainWindow", "Đăng nhập"))
        self.NhapSoDt.setPlaceholderText(_translate("MainWindow", "Nhập số điện thoại"))
        self.label_password.setText(_translate("MainWindow", "Mật khẩu"))
        self.NhapMatKhau.setPlaceholderText(_translate("MainWindow", "Nhập mật khẩu"))
        self.radQuyenGop.setText(_translate("MainWindow", "Quyên góp"))
        self.radChuChienDich.setText(_translate("MainWindow", "Chủ chiến dịch"))
        self.label_no_account.setText(_translate("MainWindow", "Bạn chưa có tài khoản ?"))
        self.NutDangKi.setText(_translate("MainWindow", "Đăng kí ngay"))
        self.NutDangNhap.setText(_translate("MainWindow", "Đăng nhập"))
