# Form implementation generated from reading ui file 'c:\Users\ADMIN\OneDrive\Documents\UEL.ktlt\BaiDuAn\donarity_campaign_detail_2.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 760)
        MainWindow.setMaximumSize(QtCore.QSize(1200, 900))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("\n"
"QWidget#centralwidget{\n"
"    background:#FFF3F9;\n"
"    font-family:\"Segoe UI\";\n"
"}\n"
"\n"
"/* top */\n"
"QFrame#topBar{\n"
"    background:#F5D8E4;\n"
"    border:none;\n"
"}\n"
"QLabel#logoText{\n"
"    color:#9E4E7F;\n"
"    font-size:28px;\n"
"    font-weight:900;\n"
"}\n"
"QLabel#logoSub{\n"
"    color:#A6929D;\n"
"    font-size:10px;\n"
"    font-weight:600;\n"
"}\n"
"QPushButton#navHome,\n"
"QPushButton#navCreate,\n"
"QPushButton#navPublic{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:#2B2B2B;\n"
"    font-size:14px;\n"
"    font-weight:600;\n"
"    padding:6px 10px;\n"
"}\n"
"QPushButton#navFollow{\n"
"    background:#D5A7C1;\n"
"    border:none;\n"
"    border-radius:17px;\n"
"    color:#2B2B2B;\n"
"    font-size:14px;\n"
"    font-weight:700;\n"
"    padding:7px 16px;\n"
"}\n"
"QLabel#topIconRed{\n"
"    color:#D62C49;\n"
"    font-size:18px;\n"
"    font-weight:700;\n"
"}\n"
"QLabel#topIconDark{\n"
"    color:#1D1D1D;\n"
"    font-size:18px;\n"
"    font-weight:700;\n"
"}\n"
"QLabel#topUser{\n"
"    color:#1D1D1D;\n"
"    font-size:24px;\n"
"    font-weight:700;\n"
"}\n"
"\n"
"/* back */\n"
"QPushButton#backBtn{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:#242424;\n"
"    font-size:18px;\n"
"    font-weight:700;\n"
"    text-align:left;\n"
"}\n"
"\n"
"/* card */\n"
"QFrame#mainPinkCard{\n"
"    background:#F8E2EB;\n"
"    border:none;\n"
"    border-radius:24px;\n"
"}\n"
"QLabel#campaignImage{\n"
"    background:#FFFFFF;\n"
"    border:none;\n"
"    border-radius:24px;\n"
"    color:#A7A7A7;\n"
"    font-size:17px;\n"
"    font-weight:700;\n"
"}\n"
"QLabel#titleLabel{\n"
"    color:#7B4C6B;\n"
"    font-size:31px;\n"
"    font-weight:900;\n"
"}\n"
"QLabel#descLabel{\n"
"    color:#403B40;\n"
"    font-size:16px;\n"
"    font-weight:500;\n"
"}\n"
"QLabel#tagCode,\n"
"QLabel#tagCate{\n"
"    background:#F0CDDD;\n"
"    color:#B1849C;\n"
"    border-radius:11px;\n"
"    padding:4px 12px;\n"
"    font-size:12px;\n"
"    font-weight:700;\n"
"}\n"
"QLabel#tagStatus{\n"
"    background:#D9F4D8;\n"
"    color:#49A45F;\n"
"    border-radius:11px;\n"
"    padding:4px 12px;\n"
"    font-size:12px;\n"
"    font-weight:700;\n"
"}\n"
"QLabel#metaIconPink{\n"
"    color:#F1A2C5;\n"
"    font-size:17px;\n"
"    font-weight:700;\n"
"}\n"
"QLabel#metaIconPurple{\n"
"    color:#C9C7F7;\n"
"    font-size:17px;\n"
"    font-weight:700;\n"
"}\n"
"QLabel#metaText{\n"
"    color:#6C616A;\n"
"    font-size:15px;\n"
"    font-weight:500;\n"
"}\n"
"\n"
"/* progress */\n"
"QFrame#progressCard{\n"
"    background:#FFFFFF;\n"
"    border:none;\n"
"    border-radius:22px;\n"
"}\n"
"QLabel#amountMain{\n"
"    color:#754C68;\n"
"    font-size:20px;\n"
"    font-weight:900;\n"
"}\n"
"QLabel#amountSub{\n"
"    color:#9E8798;\n"
"    font-size:20px;\n"
"    font-weight:800;\n"
"}\n"
"QLabel#percentLabel{\n"
"    color:#754C68;\n"
"    font-size:20px;\n"
"    font-weight:900;\n"
"}\n"
"QProgressBar#progressBar{\n"
"    border:none;\n"
"    border-radius:11px;\n"
"    background:#F5DCE7;\n"
"    min-height:24px;\n"
"    max-height:24px;\n"
"}\n"
"QProgressBar#progressBar::chunk{\n"
"    background:#EDA4CB;\n"
"    border-radius:11px;\n"
"}\n"
"QLabel#statTitle{\n"
"    color:#272727;\n"
"    font-size:17px;\n"
"    font-weight:800;\n"
"}\n"
"QLabel#statValueLeft{\n"
"    color:#AF9BAA;\n"
"    font-size:20px;\n"
"    font-weight:900;\n"
"}\n"
"QLabel#statValueRight{\n"
"    color:#A06D8F;\n"
"    font-size:20px;\n"
"    font-weight:900;\n"
"}\n"
"QLabel#miniLogo{\n"
"    color:#9E4E7F;\n"
"    font-size:18px;\n"
"    font-weight:900;\n"
"}\n"
"QLabel#miniLogoSub{\n"
"    color:#A6929D;\n"
"    font-size:10px;\n"
"    font-weight:600;\n"
"}\n"
"    ")
        self.centralwidget.setObjectName("centralwidget")
        self.mainPinkCard = QtWidgets.QFrame(parent=self.centralwidget)
        self.mainPinkCard.setGeometry(QtCore.QRect(10, 122, 1170, 770))
        self.mainPinkCard.setObjectName("mainPinkCard")
        self.titleLabel = QtWidgets.QLabel(parent=self.mainPinkCard)
        self.titleLabel.setGeometry(QtCore.QRect(360, -12, 741, 84))
        self.titleLabel.setWordWrap(True)
        self.titleLabel.setObjectName("titleLabel")
        self.descLabel = QtWidgets.QLabel(parent=self.mainPinkCard)
        self.descLabel.setGeometry(QtCore.QRect(360, 74, 700, 56))
        self.descLabel.setWordWrap(True)
        self.descLabel.setObjectName("descLabel")
        self.tagCode = QtWidgets.QLabel(parent=self.mainPinkCard)
        self.tagCode.setGeometry(QtCore.QRect(360, 136, 82, 28))
        self.tagCode.setObjectName("tagCode")
        self.tagCate = QtWidgets.QLabel(parent=self.mainPinkCard)
        self.tagCate.setGeometry(QtCore.QRect(450, 136, 135, 28))
        self.tagCate.setObjectName("tagCate")
        self.tagStatus = QtWidgets.QLabel(parent=self.mainPinkCard)
        self.tagStatus.setGeometry(QtCore.QRect(1002, 136, 138, 28))
        self.tagStatus.setObjectName("tagStatus")
        self.scopeIcon = QtWidgets.QLabel(parent=self.mainPinkCard)
        self.scopeIcon.setGeometry(QtCore.QRect(364, 188, 22, 22))
        self.scopeIcon.setStyleSheet("color:#F1A2C5;font-size:17px;font-weight:700;")
        self.scopeIcon.setObjectName("scopeIcon")
        self.scopeText = QtWidgets.QLabel(parent=self.mainPinkCard)
        self.scopeText.setGeometry(QtCore.QRect(396, 186, 230, 25))
        self.scopeText.setStyleSheet("color:#6C616A;font-size:15px;font-weight:500;")
        self.scopeText.setObjectName("scopeText")
        self.dateIcon = QtWidgets.QLabel(parent=self.mainPinkCard)
        self.dateIcon.setGeometry(QtCore.QRect(364, 234, 22, 22))
        self.dateIcon.setStyleSheet("color:#F1A2C5;font-size:17px;font-weight:700;")
        self.dateIcon.setObjectName("dateIcon")
        self.dateText = QtWidgets.QLabel(parent=self.mainPinkCard)
        self.dateText.setGeometry(QtCore.QRect(396, 232, 280, 25))
        self.dateText.setStyleSheet("color:#6C616A;font-size:15px;font-weight:500;")
        self.dateText.setObjectName("dateText")
        self.activityIcon = QtWidgets.QLabel(parent=self.mainPinkCard)
        self.activityIcon.setGeometry(QtCore.QRect(364, 280, 22, 22))
        self.activityIcon.setStyleSheet("color:#C9C7F7;font-size:17px;font-weight:700;")
        self.activityIcon.setObjectName("activityIcon")
        self.activityText = QtWidgets.QLabel(parent=self.mainPinkCard)
        self.activityText.setGeometry(QtCore.QRect(396, 260, 620, 92))
        self.activityText.setStyleSheet("color:#6C616A;font-size:15px;font-weight:500;")
        self.activityText.setWordWrap(True)
        self.activityText.setObjectName("activityText")
        self.progressCard = QtWidgets.QFrame(parent=self.mainPinkCard)
        self.progressCard.setGeometry(QtCore.QRect(22, 342, 1124, 241))
        self.progressCard.setObjectName("progressCard")
        self.top = QtWidgets.QLabel(parent=self.progressCard)
        self.top.setGeometry(QtCore.QRect(18, 22, 190, 32))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.top.setFont(font)
        self.top.setObjectName("top")
        self.bottom = QtWidgets.QLabel(parent=self.progressCard)
        self.bottom.setGeometry(QtCore.QRect(160, 22, 220, 32))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bottom.setFont(font)
        self.bottom.setObjectName("bottom")
        self.PhanTram = QtWidgets.QLabel(parent=self.progressCard)
        self.PhanTram.setGeometry(QtCore.QRect(1018, 22, 82, 32))
        self.PhanTram.setObjectName("PhanTram")
        self.statTitleLeft = QtWidgets.QLabel(parent=self.progressCard)
        self.statTitleLeft.setGeometry(QtCore.QRect(32, 148, 220, 28))
        self.statTitleLeft.setStyleSheet("color:#272727;font-size:17px;font-weight:800;")
        self.statTitleLeft.setObjectName("statTitleLeft")
        self.SoTienDaNhan = QtWidgets.QLabel(parent=self.progressCard)
        self.SoTienDaNhan.setGeometry(QtCore.QRect(100, 184, 220, 34))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.SoTienDaNhan.setFont(font)
        self.SoTienDaNhan.setObjectName("SoTienDaNhan")
        self.statTitleRight = QtWidgets.QLabel(parent=self.progressCard)
        self.statTitleRight.setGeometry(QtCore.QRect(400, 148, 150, 28))
        self.statTitleRight.setStyleSheet("color:#272727;font-size:17px;font-weight:800;")
        self.statTitleRight.setObjectName("statTitleRight")
        self.statValueRight = QtWidgets.QLabel(parent=self.progressCard)
        self.statValueRight.setGeometry(QtCore.QRect(430, 184, 280, 34))
        self.statValueRight.setObjectName("statValueRight")
        self.miniLogo = QtWidgets.QLabel(parent=self.progressCard)
        self.miniLogo.setGeometry(QtCore.QRect(1004, 180, 96, 26))
        self.miniLogo.setObjectName("miniLogo")
        self.miniLogoSub = QtWidgets.QLabel(parent=self.progressCard)
        self.miniLogoSub.setGeometry(QtCore.QRect(1032, 204, 62, 14))
        self.miniLogoSub.setObjectName("miniLogoSub")
        self.statTitleRight_2 = QtWidgets.QLabel(parent=self.progressCard)
        self.statTitleRight_2.setGeometry(QtCore.QRect(960, 170, 51, 51))
        self.statTitleRight_2.setStyleSheet("color:#2C2C2C;font-size:18px;font-weight:800;")
        self.statTitleRight_2.setObjectName("statTitleRight_2")
        self.Thanh = QtWidgets.QProgressBar(parent=self.progressCard)
        self.Thanh.setGeometry(QtCore.QRect(20, 90, 1051, 31))
        self.Thanh.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.Thanh.setProperty("value", 30)
        self.Thanh.setTextVisible(False)
        self.Thanh.setObjectName("Thanh")
        self.label = QtWidgets.QLabel(parent=self.mainPinkCard)
        self.label.setGeometry(QtCore.QRect(50, 18, 341, 321))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\ADMIN\\OneDrive\\Documents\\UEL.ktlt\\BaiDuAn\\../../../../Downloads/avt_camdetail1.jpg"))
        self.label.setObjectName("label")
        self.back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back.setGeometry(QtCore.QRect(10, 80, 121, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.back.setFont(font)
        self.back.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.back.setStyleSheet("QPushButton{\n"
"background: transparent;\n"
"border: none;\n"
"color: #111111;\n"
"text-align: left;\n"
"padding-left: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"color: #7A2D6A;\n"
"}")
        self.back.setObjectName("back")
        self.topBar = QtWidgets.QFrame(parent=self.centralwidget)
        self.topBar.setGeometry(QtCore.QRect(0, 0, 1200, 72))
        self.topBar.setObjectName("topBar")
        self.logoSub = QtWidgets.QLabel(parent=self.topBar)
        self.logoSub.setGeometry(QtCore.QRect(82, 38, 80, 14))
        self.logoSub.setObjectName("logoSub")
        self.ThongBao = QtWidgets.QLabel(parent=self.topBar)
        self.ThongBao.setGeometry(QtCore.QRect(1040, 20, 28, 28))
        self.ThongBao.setStyleSheet("color:#E53958;font-size:18px;font-weight:700;")
        self.ThongBao.setObjectName("ThongBao")
        self.CaiDat = QtWidgets.QLabel(parent=self.topBar)
        self.CaiDat.setGeometry(QtCore.QRect(1084, 20, 28, 28))
        self.CaiDat.setStyleSheet("color:#1E1E1E;font-size:18px;font-weight:700;")
        self.CaiDat.setObjectName("CaiDat")
        self.TaiKhoan = QtWidgets.QLabel(parent=self.topBar)
        self.TaiKhoan.setGeometry(QtCore.QRect(1126, 15, 34, 34))
        self.TaiKhoan.setStyleSheet("color:#1E1E1E;font-size:24px;font-weight:700;")
        self.TaiKhoan.setObjectName("TaiKhoan")
        self.logo_icon = QtWidgets.QLabel(parent=self.topBar)
        self.logo_icon.setGeometry(QtCore.QRect(33, 18, 42, 34))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.logo_icon.setFont(font)
        self.logo_icon.setStyleSheet("QLabel{\n"
"    background: transparent;\n"
"    color: #7D2B6E;\n"
"    border: none;\n"
"}")
        self.logo_icon.setObjectName("logo_icon")
        self.logo_title = QtWidgets.QLabel(parent=self.topBar)
        self.logo_title.setGeometry(QtCore.QRect(70, 10, 170, 42))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.logo_title.setFont(font)
        self.logo_title.setStyleSheet("QLabel{\n"
"    color: #7D2B6E;\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.logo_title.setObjectName("logo_title")
        self.NutTrangChu = QtWidgets.QPushButton(parent=self.topBar)
        self.NutTrangChu.setGeometry(QtCore.QRect(250, 20, 131, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.NutTrangChu.setFont(font)
        self.NutTrangChu.setStyleSheet("background-color: rgb(255, 164, 196);")
        self.NutTrangChu.setObjectName("NutTrangChu")
        self.NutTaoChienDich = QtWidgets.QPushButton(parent=self.topBar)
        self.NutTaoChienDich.setGeometry(QtCore.QRect(390, 20, 145, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.NutTaoChienDich.setFont(font)
        self.NutTaoChienDich.setStyleSheet("background-color: rgb(255, 164, 196);")
        self.NutTaoChienDich.setObjectName("NutTaoChienDich")
        self.NutTheoDoiChienDich = QtWidgets.QPushButton(parent=self.topBar)
        self.NutTheoDoiChienDich.setGeometry(QtCore.QRect(550, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.NutTheoDoiChienDich.setFont(font)
        self.NutTheoDoiChienDich.setStyleSheet("background-color: rgb(255, 164, 196);")
        self.NutTheoDoiChienDich.setObjectName("NutTheoDoiChienDich")
        self.NutCongKhai = QtWidgets.QPushButton(parent=self.topBar)
        self.NutCongKhai.setGeometry(QtCore.QRect(730, 20, 131, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.NutCongKhai.setFont(font)
        self.NutCongKhai.setStyleSheet("background-color: rgb(255, 164, 196);")
        self.NutCongKhai.setObjectName("NutCongKhai")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Donarity - Theo dõi chiến dịch"))
        self.titleLabel.setText(_translate("MainWindow", "Operation Smile Vietnam (Phẫu thuật nụ cười)"))
        self.descLabel.setText(_translate("MainWindow", "Cung cấp các ca phẫu thuật miễn phí cho trẻ em bị dị tật hàm mặt, chủ yếu là sứt môi và hở hàm ếch, giúp các em tự tin hòa nhập cộng đồng."))
        self.tagCode.setText(_translate("MainWindow", "CD0002"))
        self.tagCate.setText(_translate("MainWindow", "Y tế & sức khỏe"))
        self.tagStatus.setText(_translate("MainWindow", "🟢 Đang diễn ra"))
        self.scopeIcon.setText(_translate("MainWindow", "📍"))
        self.scopeText.setText(_translate("MainWindow", "Phạm vi : Toàn quốc"))
        self.dateIcon.setText(_translate("MainWindow", "🗓"))
        self.dateText.setText(_translate("MainWindow", "Ngày thành lập : 1989-02-06"))
        self.activityIcon.setText(_translate("MainWindow", "👥"))
        self.activityText.setText(_translate("MainWindow", "Hoạt động :  • Phẫu thuật hàm mặt miễn phí cho trẻ em\n"
"             • Điều trị nha khoa và trị liệu ngôn ngữ\n"
"             • Đào tạo chuyên môn y khoa cho bác sĩ địa phương"))
        self.top.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#a06d8f;\">0</span></p></body></html>"))
        self.bottom.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#a06d8f;\">/12000000000</span></p></body></html>"))
        self.PhanTram.setText(_translate("MainWindow", "..."))
        self.statTitleLeft.setText(_translate("MainWindow", "💰 Số tiền đã nhận"))
        self.SoTienDaNhan.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#a06d8f;\">0</span></p></body></html>"))
        self.statTitleRight.setText(_translate("MainWindow", "🎯 Mục tiêu"))
        self.statValueRight.setText(_translate("MainWindow", "12,000,000,000"))
        self.miniLogo.setText(_translate("MainWindow", "Donarity"))
        self.miniLogoSub.setText(_translate("MainWindow", "by group 10"))
        self.statTitleRight_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; color:#98015e;\">🕊</span></p></body></html>"))
        self.back.setText(_translate("MainWindow", "← Quay lại"))
        self.logoSub.setText(_translate("MainWindow", "by group 10"))
        self.ThongBao.setText(_translate("MainWindow", "🔔"))
        self.CaiDat.setText(_translate("MainWindow", "⚙"))
        self.TaiKhoan.setText(_translate("MainWindow", "👤"))
        self.logo_icon.setText(_translate("MainWindow", "🕊"))
        self.logo_title.setText(_translate("MainWindow", "Donarity"))
        self.NutTrangChu.setText(_translate("MainWindow", "🏠  Trang chủ"))
        self.NutTaoChienDich.setText(_translate("MainWindow", "➕  Tạo chiến dịch"))
        self.NutTheoDoiChienDich.setText(_translate("MainWindow", "🗂  Theo dõi chiến dịch"))
        self.NutCongKhai.setText(_translate("MainWindow", "👁  Công khai"))
