# Form implementation generated from reading ui file 'C:\Users\ADMIN\PycharmProjects\DoAnKTLT\home_page_user.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 760)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 760))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 760))
        MainWindow.setStyleSheet("QMainWindow, QWidget {\n"
"    background: #F7EEF2;\n"
"    font-family: \"Segoe UI\";\n"
"    color: #2F2A2E;\n"
"}\n"
"\n"
"QFrame#topBar {\n"
"    background: #F2D6DF;\n"
"    border: none;\n"
"}\n"
"\n"
"QLabel#brandLabel {\n"
"    color: #8B3D73;\n"
"    font-size: 16pt;\n"
"    font-weight: 800;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel#subBrandLabel {\n"
"    color: #8B3D73;\n"
"    font-size: 7pt;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QPushButton#navHome {\n"
"    background: #E6B7CA;\n"
"    border: none;\n"
"    border-radius: 18px;\n"
"    padding: 8px 16px;\n"
"    font-size: 10pt;\n"
"    font-weight: 700;\n"
"    color: #2F2A2E;\n"
"}\n"
"\n"
"QPushButton#navStats,\n"
"QPushButton#navChatbot,\n"
"QPushButton#navPublic {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 8px 10px;\n"
"    font-size: 10pt;\n"
"    font-weight: 700;\n"
"    color: #2F2A2E;\n"
"}\n"
"\n"
"QPushButton#navHome:hover,\n"
"QPushButton#navStats:hover,\n"
"QPushButton#navChatbot:hover,\n"
"QPushButton#navPublic:hover {\n"
"    color: #7A2F62;\n"
"}\n"
"\n"
"QPushButton#btnNotify,\n"
"QPushButton#btnSetting,\n"
"QPushButton#btnUser {\n"
"    background: transparent;\n"
"    border: none;\n"
"    font-size: 16pt;\n"
"    color: #2F2A2E;\n"
"}\n"
"\n"
"QFrame#heroFrame {\n"
"    background: #E9DADF;\n"
"    border: none;\n"
"}\n"
"\n"
"QLabel#heroImage {\n"
"    border: none;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel#heroTitle {\n"
"    background: transparent;\n"
"    color: #111111;\n"
"    font-size: 44pt;\n"
"    font-weight: 900;\n"
"}\n"
"\n"
"QLabel#heroSubtitle {\n"
"    background: transparent;\n"
"    color: #1C1C1C;\n"
"    font-size: 18pt;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"QWidget#categoryArea {\n"
"    background: #F7EEF2;\n"
"}\n"
"\n"
"QFrame#cat1, QFrame#cat2, QFrame#cat3, QFrame#cat4, QFrame#cat5, QFrame#cat6 {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QLabel#icon1, QLabel#icon2, QLabel#icon3, QLabel#icon4, QLabel#icon5, QLabel#icon6 {\n"
"    color: #8B3D73;\n"
"    font-size: 27pt;\n"
"    font-weight: 700;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"\n"
"QLabel#text1, QLabel#text2, QLabel#text3, QLabel#text4, QLabel#text5, QLabel#text6 {\n"
"    color: #8B3D73;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"    qproperty-alignment: AlignCenter;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QFrame#bottomBar {\n"
"    background: #F2D6DF;\n"
"    border: none;\n"
"}\n"
"\n"
"QLabel#reportLabel {\n"
"    background: transparent;\n"
"    color: #2F2A2E;\n"
"    font-size: 10pt;\n"
"    font-weight: 500;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_main.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_main.setSpacing(0)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.topBar = QtWidgets.QFrame(parent=self.centralwidget)
        self.topBar.setMinimumSize(QtCore.QSize(0, 52))
        self.topBar.setMaximumSize(QtCore.QSize(16777215, 52))
        self.topBar.setObjectName("topBar")
        self.horizontalLayout_top = QtWidgets.QHBoxLayout(self.topBar)
        self.horizontalLayout_top.setContentsMargins(18, 6, 18, 6)
        self.horizontalLayout_top.setSpacing(8)
        self.horizontalLayout_top.setObjectName("horizontalLayout_top")
        self.logoIcon = QtWidgets.QLabel(parent=self.topBar)
        self.logoIcon.setGeometry(QtCore.QRect(16, 6, 34, 34))
        self.logoIcon.setStyleSheet("background: transparent; color: #8A3E72; font: 700 18pt \"Segoe UI Symbol\";")
        self.logoIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoIcon.setObjectName("logoIcon")
        self.horizontalLayout_top.addWidget(self.logoIcon)
        self.verticalLayout_brand = QtWidgets.QVBoxLayout()
        self.verticalLayout_brand.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_brand.setSpacing(0)
        self.verticalLayout_brand.setObjectName("verticalLayout_brand")
        self.brandLabel = QtWidgets.QLabel(parent=self.topBar)
        self.brandLabel.setObjectName("brandLabel")
        self.verticalLayout_brand.addWidget(self.brandLabel)
        self.subBrandLabel = QtWidgets.QLabel(parent=self.topBar)
        self.subBrandLabel.setObjectName("subBrandLabel")
        self.verticalLayout_brand.addWidget(self.subBrandLabel)
        self.horizontalLayout_top.addLayout(self.verticalLayout_brand)
        spacerItem = QtWidgets.QSpacerItem(24, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_top.addItem(spacerItem)
        self.navHome = QtWidgets.QPushButton(parent=self.topBar)
        self.navHome.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.navHome.setObjectName("navHome")
        self.horizontalLayout_top.addWidget(self.navHome)
        self.navStats = QtWidgets.QPushButton(parent=self.topBar)
        self.navStats.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.navStats.setObjectName("navStats")
        self.horizontalLayout_top.addWidget(self.navStats)
        self.navChatbot = QtWidgets.QPushButton(parent=self.topBar)
        self.navChatbot.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.navChatbot.setObjectName("navChatbot")
        self.horizontalLayout_top.addWidget(self.navChatbot)
        self.navPublic = QtWidgets.QPushButton(parent=self.topBar)
        self.navPublic.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.navPublic.setObjectName("navPublic")
        self.horizontalLayout_top.addWidget(self.navPublic)
        spacerItem1 = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_top.addItem(spacerItem1)
        self.btnNotify = QtWidgets.QPushButton(parent=self.topBar)
        self.btnNotify.setMinimumSize(QtCore.QSize(30, 30))
        self.btnNotify.setMaximumSize(QtCore.QSize(30, 30))
        self.btnNotify.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnNotify.setObjectName("btnNotify")
        self.horizontalLayout_top.addWidget(self.btnNotify)
        self.btnSetting = QtWidgets.QPushButton(parent=self.topBar)
        self.btnSetting.setMinimumSize(QtCore.QSize(30, 30))
        self.btnSetting.setMaximumSize(QtCore.QSize(30, 30))
        self.btnSetting.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnSetting.setObjectName("btnSetting")
        self.horizontalLayout_top.addWidget(self.btnSetting)
        self.btnUser = QtWidgets.QPushButton(parent=self.topBar)
        self.btnUser.setMinimumSize(QtCore.QSize(34, 34))
        self.btnUser.setMaximumSize(QtCore.QSize(34, 34))
        self.btnUser.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnUser.setObjectName("btnUser")
        self.horizontalLayout_top.addWidget(self.btnUser)
        self.verticalLayout_main.addWidget(self.topBar)
        self.heroFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.heroFrame.setMinimumSize(QtCore.QSize(0, 420))
        self.heroFrame.setMaximumSize(QtCore.QSize(16777215, 420))
        self.heroFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.heroFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.heroFrame.setObjectName("heroFrame")
        self.heroImage = QtWidgets.QLabel(parent=self.heroFrame)
        self.heroImage.setGeometry(QtCore.QRect(0, 0, 1200, 420))
        self.heroImage.setText("")
        self.heroImage.setPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\DoAnKTLT\\anh.png"))
        self.heroImage.setScaledContents(True)
        self.heroImage.setObjectName("heroImage")
        self.heroTitle = QtWidgets.QLabel(parent=self.heroFrame)
        self.heroTitle.setGeometry(QtCore.QRect(62, 78, 470, 86))
        self.heroTitle.setObjectName("heroTitle")
        self.overlayFrame = QtWidgets.QFrame(parent=self.heroFrame)
        self.overlayFrame.setGeometry(QtCore.QRect(0, 0, 1200, 420))
        self.overlayFrame.setStyleSheet("background-color: rgba(255, 245, 248, 120); border: none;")
        self.overlayFrame.setObjectName("overlayFrame")
        self.heroSubtitle = QtWidgets.QLabel(parent=self.heroFrame)
        self.heroSubtitle.setGeometry(QtCore.QRect(68, 165, 560, 42))
        self.heroSubtitle.setObjectName("heroSubtitle")
        self.verticalLayout_main.addWidget(self.heroFrame)
        self.categoryArea = QtWidgets.QWidget(parent=self.centralwidget)
        self.categoryArea.setMinimumSize(QtCore.QSize(0, 250))
        self.categoryArea.setObjectName("categoryArea")
        self.horizontalLayout_categories = QtWidgets.QHBoxLayout(self.categoryArea)
        self.horizontalLayout_categories.setContentsMargins(34, 22, 34, 12)
        self.horizontalLayout_categories.setSpacing(6)
        self.horizontalLayout_categories.setObjectName("horizontalLayout_categories")
        self.cat1 = QtWidgets.QFrame(parent=self.categoryArea)
        self.cat1.setObjectName("cat1")
        self.verticalLayout_cat1 = QtWidgets.QVBoxLayout(self.cat1)
        self.verticalLayout_cat1.setSpacing(8)
        self.verticalLayout_cat1.setObjectName("verticalLayout_cat1")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_cat1.addItem(spacerItem2)
        self.icon1 = QtWidgets.QLabel(parent=self.cat1)
        self.icon1.setObjectName("icon1")
        self.verticalLayout_cat1.addWidget(self.icon1)
        self.text1 = QtWidgets.QLabel(parent=self.cat1)
        self.text1.setObjectName("text1")
        self.verticalLayout_cat1.addWidget(self.text1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_cat1.addItem(spacerItem3)
        self.horizontalLayout_categories.addWidget(self.cat1)
        self.cat2 = QtWidgets.QFrame(parent=self.categoryArea)
        self.cat2.setObjectName("cat2")
        self.verticalLayout_cat2 = QtWidgets.QVBoxLayout(self.cat2)
        self.verticalLayout_cat2.setSpacing(8)
        self.verticalLayout_cat2.setObjectName("verticalLayout_cat2")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_cat2.addItem(spacerItem4)
        self.icon2 = QtWidgets.QLabel(parent=self.cat2)
        self.icon2.setObjectName("icon2")
        self.verticalLayout_cat2.addWidget(self.icon2)
        self.text2 = QtWidgets.QLabel(parent=self.cat2)
        self.text2.setObjectName("text2")
        self.verticalLayout_cat2.addWidget(self.text2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_cat2.addItem(spacerItem5)
        self.horizontalLayout_categories.addWidget(self.cat2)
        self.cat3 = QtWidgets.QFrame(parent=self.categoryArea)
        self.cat3.setObjectName("cat3")
        self.verticalLayout_cat3 = QtWidgets.QVBoxLayout(self.cat3)
        self.verticalLayout_cat3.setSpacing(8)
        self.verticalLayout_cat3.setObjectName("verticalLayout_cat3")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_cat3.addItem(spacerItem6)
        self.icon3 = QtWidgets.QLabel(parent=self.cat3)
        self.icon3.setObjectName("icon3")
        self.verticalLayout_cat3.addWidget(self.icon3)
        self.text3 = QtWidgets.QLabel(parent=self.cat3)
        self.text3.setObjectName("text3")
        self.verticalLayout_cat3.addWidget(self.text3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_cat3.addItem(spacerItem7)
        self.horizontalLayout_categories.addWidget(self.cat3)
        self.cat4 = QtWidgets.QFrame(parent=self.categoryArea)
        self.cat4.setObjectName("cat4")
        self.verticalLayout_cat4 = QtWidgets.QVBoxLayout(self.cat4)
        self.verticalLayout_cat4.setSpacing(8)
        self.verticalLayout_cat4.setObjectName("verticalLayout_cat4")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_cat4.addItem(spacerItem8)
        self.icon4 = QtWidgets.QLabel(parent=self.cat4)
        self.icon4.setObjectName("icon4")
        self.verticalLayout_cat4.addWidget(self.icon4)
        self.text4 = QtWidgets.QLabel(parent=self.cat4)
        self.text4.setObjectName("text4")
        self.verticalLayout_cat4.addWidget(self.text4)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_cat4.addItem(spacerItem9)
        self.horizontalLayout_categories.addWidget(self.cat4)
        self.cat5 = QtWidgets.QFrame(parent=self.categoryArea)
        self.cat5.setObjectName("cat5")
        self.verticalLayout_cat5 = QtWidgets.QVBoxLayout(self.cat5)
        self.verticalLayout_cat5.setSpacing(8)
        self.verticalLayout_cat5.setObjectName("verticalLayout_cat5")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_cat5.addItem(spacerItem10)
        self.icon5 = QtWidgets.QLabel(parent=self.cat5)
        self.icon5.setObjectName("icon5")
        self.verticalLayout_cat5.addWidget(self.icon5)
        self.text5 = QtWidgets.QLabel(parent=self.cat5)
        self.text5.setObjectName("text5")
        self.verticalLayout_cat5.addWidget(self.text5)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_cat5.addItem(spacerItem11)
        self.horizontalLayout_categories.addWidget(self.cat5)
        self.cat6 = QtWidgets.QFrame(parent=self.categoryArea)
        self.cat6.setObjectName("cat6")
        self.verticalLayout_cat6 = QtWidgets.QVBoxLayout(self.cat6)
        self.verticalLayout_cat6.setSpacing(8)
        self.verticalLayout_cat6.setObjectName("verticalLayout_cat6")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_cat6.addItem(spacerItem12)
        self.icon6 = QtWidgets.QLabel(parent=self.cat6)
        self.icon6.setObjectName("icon6")
        self.verticalLayout_cat6.addWidget(self.icon6)
        self.text6 = QtWidgets.QLabel(parent=self.cat6)
        self.text6.setObjectName("text6")
        self.verticalLayout_cat6.addWidget(self.text6)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_cat6.addItem(spacerItem13)
        self.horizontalLayout_categories.addWidget(self.cat6)
        self.verticalLayout_main.addWidget(self.categoryArea)
        spacerItem14 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_main.addItem(spacerItem14)
        self.bottomBar = QtWidgets.QFrame(parent=self.centralwidget)
        self.bottomBar.setMinimumSize(QtCore.QSize(0, 48))
        self.bottomBar.setMaximumSize(QtCore.QSize(16777215, 48))
        self.bottomBar.setObjectName("bottomBar")
        self.horizontalLayout_bottom = QtWidgets.QHBoxLayout(self.bottomBar)
        self.horizontalLayout_bottom.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_bottom.setObjectName("horizontalLayout_bottom")
        spacerItem15 = QtWidgets.QSpacerItem(1000, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_bottom.addItem(spacerItem15)
        self.reportLabel = QtWidgets.QLabel(parent=self.bottomBar)
        self.reportLabel.setObjectName("reportLabel")
        self.horizontalLayout_bottom.addWidget(self.reportLabel)
        self.verticalLayout_main.addWidget(self.bottomBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Donarity - Chatbot"))
        self.logoIcon.setText(_translate("MainWindow", "🕊"))
        self.brandLabel.setText(_translate("MainWindow", "Donarity"))
        self.subBrandLabel.setText(_translate("MainWindow", "by group 10"))
        self.navHome.setText(_translate("MainWindow", "🏠 Trang chủ"))
        self.navStats.setText(_translate("MainWindow", "⌛ Thống kê"))
        self.navChatbot.setText(_translate("MainWindow", "🗨 Chatbot"))
        self.navPublic.setText(_translate("MainWindow", "👁 Công khai"))
        self.btnNotify.setText(_translate("MainWindow", "🔔"))
        self.btnSetting.setText(_translate("MainWindow", "⚙"))
        self.btnUser.setText(_translate("MainWindow", "👤"))
        self.heroTitle.setText(_translate("MainWindow", "Donarity"))
        self.heroSubtitle.setText(_translate("MainWindow", "Lan tỏa giá trị - Kiến tạo hy vọng"))
        self.icon1.setText(_translate("MainWindow", "⚕"))
        self.text1.setText(_translate("MainWindow", "Y tế & Sức khỏe"))
        self.icon2.setText(_translate("MainWindow", "▣"))
        self.text2.setText(_translate("MainWindow", "Giáo dục và khởi nghiệp"))
        self.icon3.setText(_translate("MainWindow", "☺"))
        self.text3.setText(_translate("MainWindow", "Trẻ em & Người yếu thế"))
        self.icon4.setText(_translate("MainWindow", "🧍"))
        self.text4.setText(_translate("MainWindow", "An sinh xã hội"))
        self.icon5.setText(_translate("MainWindow", "☁"))
        self.text5.setText(_translate("MainWindow", "Môi trường & Động vật"))
        self.icon6.setText(_translate("MainWindow", "👥"))
        self.text6.setText(_translate("MainWindow", "Văn hóa & Cộng đồng"))
        self.reportLabel.setText(_translate("MainWindow", "Báo cáo ⚑"))
