# Form implementation generated from reading ui file 'MoiTruong-DongVat/moitruong_dongvat.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 1131)
        MainWindow.setMinimumSize(QtCore.QSize(730, 1131))
        MainWindow.setStyleSheet("QMainWindow, QWidget {\n"
"    background: #FFF6FB;\n"
"    font-family: \"Arial\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1200, 1131))
        self.scrollArea.setMinimumSize(QtCore.QSize(1200, 760))
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    border: none;\n"
"    background: #FFF6FB;\n"
"}\n"
"QScrollBar:vertical {\n"
"    background: #F8E8F0;\n"
"    width: 12px;\n"
"    border-radius: 6px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #D9AFC7;\n"
"    min-height: 40px;\n"
"    border-radius: 6px;\n"
"}\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: transparent;\n"
"}")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 730, 1230))
        self.scrollAreaWidgetContents.setStyleSheet("background: #FFF6FB;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.topBar = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.topBar.setGeometry(QtCore.QRect(0, 3, 730, 40))
        self.topBar.setStyleSheet("QFrame{\n"
"    background:#F9DDE7;\n"
"    border:none;\n"
"    border-radius:0px;\n"
"}")
        self.topBar.setObjectName("topBar")
        self.logoIcon = QtWidgets.QLabel(parent=self.topBar)
        self.logoIcon.setGeometry(QtCore.QRect(18, 5, 28, 28))
        self.logoIcon.setStyleSheet("QLabel{\n"
"    font-size:18px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.logoIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoIcon.setObjectName("logoIcon")
        self.logoTitle = QtWidgets.QLabel(parent=self.topBar)
        self.logoTitle.setGeometry(QtCore.QRect(44, 4, 90, 20))
        self.logoTitle.setStyleSheet("QLabel{\n"
"    color:#7E3A79;\n"
"    font-size:14px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.logoTitle.setObjectName("logoTitle")
        self.logoSub = QtWidgets.QLabel(parent=self.topBar)
        self.logoSub.setGeometry(QtCore.QRect(46, 20, 56, 12))
        self.logoSub.setStyleSheet("QLabel{\n"
"    color:#7A6D75;\n"
"    font-size:7px;\n"
"    font-weight:600;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.logoSub.setObjectName("logoSub")
        self.navHome = QtWidgets.QLabel(parent=self.topBar)
        self.navHome.setGeometry(QtCore.QRect(168, 9, 84, 18))
        self.navHome.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:9px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.navHome.setObjectName("navHome")
        self.navStats = QtWidgets.QLabel(parent=self.topBar)
        self.navStats.setGeometry(QtCore.QRect(280, 9, 84, 18))
        self.navStats.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:9px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.navStats.setObjectName("navStats")
        self.navChatbot = QtWidgets.QLabel(parent=self.topBar)
        self.navChatbot.setGeometry(QtCore.QRect(350, 9, 90, 18))
        self.navChatbot.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:9px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.navChatbot.setObjectName("navChatbot")
        self.notifIcon = QtWidgets.QLabel(parent=self.topBar)
        self.notifIcon.setGeometry(QtCore.QRect(646, 8, 18, 18))
        self.notifIcon.setStyleSheet("QLabel{\n"
"    font-size:13px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.notifIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.notifIcon.setObjectName("notifIcon")
        self.notifBadge = QtWidgets.QLabel(parent=self.topBar)
        self.notifBadge.setGeometry(QtCore.QRect(658, 7, 12, 12))
        self.notifBadge.setStyleSheet("QLabel{\n"
"    background:#E53935;\n"
"    color:white;\n"
"    border-radius:6px;\n"
"    font-size:7px;\n"
"    font-weight:800;\n"
"}")
        self.notifBadge.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.notifBadge.setObjectName("notifBadge")
        self.settingsIcon = QtWidgets.QLabel(parent=self.topBar)
        self.settingsIcon.setGeometry(QtCore.QRect(678, 8, 16, 18))
        self.settingsIcon.setStyleSheet("QLabel{\n"
"    font-size:13px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.settingsIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.settingsIcon.setObjectName("settingsIcon")
        self.userIcon = QtWidgets.QLabel(parent=self.topBar)
        self.userIcon.setGeometry(QtCore.QRect(702, 6, 22, 22))
        self.userIcon.setStyleSheet("QLabel{\n"
"    color:#2A2A2A;\n"
"    font-size:18px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.userIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.userIcon.setObjectName("userIcon")
        self.backLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.backLabel.setGeometry(QtCore.QRect(7, 53, 90, 18))
        self.backLabel.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:10px;\n"
"    font-weight:600;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.backLabel.setObjectName("backLabel")
        self.titleIcon = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.titleIcon.setGeometry(QtCore.QRect(24, 88, 40, 40))
        self.titleIcon.setStyleSheet("QLabel{\n"
"    font-size:26px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.titleIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleIcon.setObjectName("titleIcon")
        self.mainTitle = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.mainTitle.setGeometry(QtCore.QRect(76, 82, 360, 48))
        self.mainTitle.setStyleSheet("QLabel{\n"
"    color:#8A4E82;\n"
"    font-size:28px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.mainTitle.setObjectName("mainTitle")
        self.searchEdit = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.searchEdit.setGeometry(QtCore.QRect(22, 141, 484, 30))
        self.searchEdit.setStyleSheet("QLineEdit{\n"
"    background:white;\n"
"    border:1px solid #CFCFCF;\n"
"    padding-left:30px;\n"
"    color:#222;\n"
"    font-size:10px;\n"
"}")
        self.searchEdit.setObjectName("searchEdit")
        self.searchIcon = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.searchIcon.setGeometry(QtCore.QRect(33, 148, 16, 16))
        self.searchIcon.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:13px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.searchIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.searchIcon.setObjectName("searchIcon")
        self.categoryCombo = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.categoryCombo.setGeometry(QtCore.QRect(504, 141, 110, 30))
        self.categoryCombo.setStyleSheet("QComboBox{\n"
"    background:white;\n"
"    border:1px solid #CFCFCF;\n"
"    padding-left:8px;\n"
"    color:#222;\n"
"    font-size:10px;\n"
"}")
        self.categoryCombo.setObjectName("categoryCombo")
        self.categoryCombo.addItem("")
        self.searchButton = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.searchButton.setGeometry(QtCore.QRect(629, 141, 66, 30))
        self.searchButton.setStyleSheet("QPushButton{\n"
"    background:#FFF6FB;\n"
"    border:1px solid #7F4D7D;\n"
"    color:#222;\n"
"    font-size:10px;\n"
"    font-weight:700;\n"
"}")
        self.searchButton.setObjectName("searchButton")
        self.card21 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card21.setGeometry(QtCore.QRect(50, 213, 300, 261))
        self.card21.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card21.setObjectName("card21")
        self.card21Image = QtWidgets.QLabel(parent=self.card21)
        self.card21Image.setGeometry(QtCore.QRect(1, 1, 298, 128))
        self.card21Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card21Image.setPixmap(QtGui.QPixmap("MoiTruong-DongVat\\campaign21.png"))
        self.card21Image.setScaledContents(True)
        self.card21Image.setObjectName("card21Image")
        self.card21Title = QtWidgets.QLabel(parent=self.card21)
        self.card21Title.setGeometry(QtCore.QRect(14, 142, 270, 34))
        self.card21Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card21Title.setWordWrap(True)
        self.card21Title.setObjectName("card21Title")
        self.card21Date = QtWidgets.QLabel(parent=self.card21)
        self.card21Date.setGeometry(QtCore.QRect(16, 177, 140, 16))
        self.card21Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card21Date.setObjectName("card21Date")
        self.card21Owner = QtWidgets.QLabel(parent=self.card21)
        self.card21Owner.setGeometry(QtCore.QRect(16, 193, 160, 16))
        self.card21Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card21Owner.setObjectName("card21Owner")
        self.card21Money = QtWidgets.QLabel(parent=self.card21)
        self.card21Money.setGeometry(QtCore.QRect(18, 214, 210, 20))
        self.card21Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card21Money.setObjectName("card21Money")
        self.card21Progress = QtWidgets.QProgressBar(parent=self.card21)
        self.card21Progress.setGeometry(QtCore.QRect(18, 236, 246, 8))
        self.card21Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card21Progress.setProperty("value", 30)
        self.card21Progress.setTextVisible(False)
        self.card21Progress.setObjectName("card21Progress")
        self.card21More = QtWidgets.QLabel(parent=self.card21)
        self.card21More.setGeometry(QtCore.QRect(30, 240, 80, 16))
        self.card21More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card21More.setObjectName("card21More")
        self.card22 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card22.setGeometry(QtCore.QRect(394, 213, 300, 261))
        self.card22.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card22.setObjectName("card22")
        self.card22Image = QtWidgets.QLabel(parent=self.card22)
        self.card22Image.setGeometry(QtCore.QRect(1, 1, 298, 128))
        self.card22Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card22Image.setPixmap(QtGui.QPixmap("MoiTruong-DongVat\\campaign22.png"))
        self.card22Image.setScaledContents(True)
        self.card22Image.setObjectName("card22Image")
        self.card22Title = QtWidgets.QLabel(parent=self.card22)
        self.card22Title.setGeometry(QtCore.QRect(14, 142, 270, 34))
        self.card22Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card22Title.setWordWrap(True)
        self.card22Title.setObjectName("card22Title")
        self.card22Date = QtWidgets.QLabel(parent=self.card22)
        self.card22Date.setGeometry(QtCore.QRect(16, 177, 140, 16))
        self.card22Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card22Date.setObjectName("card22Date")
        self.card22Owner = QtWidgets.QLabel(parent=self.card22)
        self.card22Owner.setGeometry(QtCore.QRect(16, 193, 140, 16))
        self.card22Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card22Owner.setObjectName("card22Owner")
        self.card22Money = QtWidgets.QLabel(parent=self.card22)
        self.card22Money.setGeometry(QtCore.QRect(18, 214, 210, 20))
        self.card22Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card22Money.setObjectName("card22Money")
        self.card22Progress = QtWidgets.QProgressBar(parent=self.card22)
        self.card22Progress.setGeometry(QtCore.QRect(18, 236, 246, 8))
        self.card22Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card22Progress.setProperty("value", 30)
        self.card22Progress.setTextVisible(False)
        self.card22Progress.setObjectName("card22Progress")
        self.card22More = QtWidgets.QLabel(parent=self.card22)
        self.card22More.setGeometry(QtCore.QRect(26, 240, 80, 16))
        self.card22More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card22More.setObjectName("card22More")
        self.card23 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card23.setGeometry(QtCore.QRect(50, 508, 300, 261))
        self.card23.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card23.setObjectName("card23")
        self.card23Image = QtWidgets.QLabel(parent=self.card23)
        self.card23Image.setGeometry(QtCore.QRect(1, 1, 298, 128))
        self.card23Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card23Image.setPixmap(QtGui.QPixmap("MoiTruong-DongVat\\campaign23.png"))
        self.card23Image.setScaledContents(True)
        self.card23Image.setObjectName("card23Image")
        self.card23Title = QtWidgets.QLabel(parent=self.card23)
        self.card23Title.setGeometry(QtCore.QRect(14, 142, 270, 34))
        self.card23Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card23Title.setWordWrap(True)
        self.card23Title.setObjectName("card23Title")
        self.card23Date = QtWidgets.QLabel(parent=self.card23)
        self.card23Date.setGeometry(QtCore.QRect(16, 177, 140, 16))
        self.card23Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card23Date.setObjectName("card23Date")
        self.card23Owner = QtWidgets.QLabel(parent=self.card23)
        self.card23Owner.setGeometry(QtCore.QRect(16, 193, 160, 16))
        self.card23Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card23Owner.setObjectName("card23Owner")
        self.card23Money = QtWidgets.QLabel(parent=self.card23)
        self.card23Money.setGeometry(QtCore.QRect(18, 214, 210, 20))
        self.card23Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card23Money.setObjectName("card23Money")
        self.card23Progress = QtWidgets.QProgressBar(parent=self.card23)
        self.card23Progress.setGeometry(QtCore.QRect(18, 236, 246, 8))
        self.card23Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card23Progress.setProperty("value", 30)
        self.card23Progress.setTextVisible(False)
        self.card23Progress.setObjectName("card23Progress")
        self.card23More = QtWidgets.QLabel(parent=self.card23)
        self.card23More.setGeometry(QtCore.QRect(26, 240, 80, 16))
        self.card23More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card23More.setObjectName("card23More")
        self.card24 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card24.setGeometry(QtCore.QRect(394, 508, 300, 261))
        self.card24.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card24.setObjectName("card24")
        self.card24Image = QtWidgets.QLabel(parent=self.card24)
        self.card24Image.setGeometry(QtCore.QRect(1, 1, 298, 128))
        self.card24Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card24Image.setPixmap(QtGui.QPixmap("MoiTruong-DongVat\\campaign24.png"))
        self.card24Image.setScaledContents(True)
        self.card24Image.setObjectName("card24Image")
        self.card24Title = QtWidgets.QLabel(parent=self.card24)
        self.card24Title.setGeometry(QtCore.QRect(14, 142, 270, 34))
        self.card24Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card24Title.setWordWrap(True)
        self.card24Title.setObjectName("card24Title")
        self.card24Date = QtWidgets.QLabel(parent=self.card24)
        self.card24Date.setGeometry(QtCore.QRect(16, 177, 140, 16))
        self.card24Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card24Date.setObjectName("card24Date")
        self.card24Owner = QtWidgets.QLabel(parent=self.card24)
        self.card24Owner.setGeometry(QtCore.QRect(16, 193, 160, 16))
        self.card24Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card24Owner.setObjectName("card24Owner")
        self.card24Money = QtWidgets.QLabel(parent=self.card24)
        self.card24Money.setGeometry(QtCore.QRect(18, 214, 210, 20))
        self.card24Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card24Money.setObjectName("card24Money")
        self.card24Progress = QtWidgets.QProgressBar(parent=self.card24)
        self.card24Progress.setGeometry(QtCore.QRect(18, 236, 246, 8))
        self.card24Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card24Progress.setProperty("value", 30)
        self.card24Progress.setTextVisible(False)
        self.card24Progress.setObjectName("card24Progress")
        self.card24More = QtWidgets.QLabel(parent=self.card24)
        self.card24More.setGeometry(QtCore.QRect(26, 240, 80, 16))
        self.card24More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card24More.setObjectName("card24More")
        self.card25 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card25.setGeometry(QtCore.QRect(50, 805, 300, 261))
        self.card25.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card25.setObjectName("card25")
        self.card25Image = QtWidgets.QLabel(parent=self.card25)
        self.card25Image.setGeometry(QtCore.QRect(1, 1, 298, 128))
        self.card25Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card25Image.setPixmap(QtGui.QPixmap("MoiTruong-DongVat\\campaign25.png"))
        self.card25Image.setScaledContents(True)
        self.card25Image.setObjectName("card25Image")
        self.card25Title = QtWidgets.QLabel(parent=self.card25)
        self.card25Title.setGeometry(QtCore.QRect(14, 142, 270, 34))
        self.card25Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card25Title.setWordWrap(True)
        self.card25Title.setObjectName("card25Title")
        self.card25Date = QtWidgets.QLabel(parent=self.card25)
        self.card25Date.setGeometry(QtCore.QRect(16, 177, 140, 16))
        self.card25Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card25Date.setObjectName("card25Date")
        self.card25Owner = QtWidgets.QLabel(parent=self.card25)
        self.card25Owner.setGeometry(QtCore.QRect(16, 193, 160, 16))
        self.card25Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card25Owner.setObjectName("card25Owner")
        self.card25Money = QtWidgets.QLabel(parent=self.card25)
        self.card25Money.setGeometry(QtCore.QRect(18, 214, 210, 20))
        self.card25Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card25Money.setObjectName("card25Money")
        self.card25Progress = QtWidgets.QProgressBar(parent=self.card25)
        self.card25Progress.setGeometry(QtCore.QRect(18, 236, 246, 8))
        self.card25Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card25Progress.setProperty("value", 30)
        self.card25Progress.setTextVisible(False)
        self.card25Progress.setObjectName("card25Progress")
        self.card25More = QtWidgets.QLabel(parent=self.card25)
        self.card25More.setGeometry(QtCore.QRect(26, 240, 80, 16))
        self.card25More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card25More.setObjectName("card25More")
        self.card26 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card26.setGeometry(QtCore.QRect(394, 805, 300, 261))
        self.card26.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card26.setObjectName("card26")
        self.card26Image = QtWidgets.QLabel(parent=self.card26)
        self.card26Image.setGeometry(QtCore.QRect(1, 1, 298, 128))
        self.card26Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card26Image.setPixmap(QtGui.QPixmap("MoiTruong-DongVat\\campaign26.png"))
        self.card26Image.setScaledContents(True)
        self.card26Image.setObjectName("card26Image")
        self.card26Title = QtWidgets.QLabel(parent=self.card26)
        self.card26Title.setGeometry(QtCore.QRect(14, 142, 270, 34))
        self.card26Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card26Title.setWordWrap(True)
        self.card26Title.setObjectName("card26Title")
        self.card26Date = QtWidgets.QLabel(parent=self.card26)
        self.card26Date.setGeometry(QtCore.QRect(16, 177, 140, 16))
        self.card26Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card26Date.setObjectName("card26Date")
        self.card26Owner = QtWidgets.QLabel(parent=self.card26)
        self.card26Owner.setGeometry(QtCore.QRect(16, 193, 140, 16))
        self.card26Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card26Owner.setObjectName("card26Owner")
        self.card26Money = QtWidgets.QLabel(parent=self.card26)
        self.card26Money.setGeometry(QtCore.QRect(18, 214, 210, 20))
        self.card26Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card26Money.setObjectName("card26Money")
        self.card26Progress = QtWidgets.QProgressBar(parent=self.card26)
        self.card26Progress.setGeometry(QtCore.QRect(18, 236, 246, 8))
        self.card26Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card26Progress.setProperty("value", 30)
        self.card26Progress.setTextVisible(False)
        self.card26Progress.setObjectName("card26Progress")
        self.card26More = QtWidgets.QLabel(parent=self.card26)
        self.card26More.setGeometry(QtCore.QRect(26, 240, 80, 16))
        self.card26More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card26More.setObjectName("card26More")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Môi trường & Động vật"))
        self.logoIcon.setText(_translate("MainWindow", "🕊"))
        self.logoTitle.setText(_translate("MainWindow", "Donarity"))
        self.logoSub.setText(_translate("MainWindow", "by group 10"))
        self.navHome.setText(_translate("MainWindow", "⌂ Trang chủ"))
        self.navStats.setText(_translate("MainWindow", "⌛ Thống kê"))
        self.navChatbot.setText(_translate("MainWindow", "◕Chatbot"))
        self.notifIcon.setText(_translate("MainWindow", "🔔"))
        self.notifBadge.setText(_translate("MainWindow", "0"))
        self.settingsIcon.setText(_translate("MainWindow", "⚙"))
        self.userIcon.setText(_translate("MainWindow", "◉"))
        self.backLabel.setText(_translate("MainWindow", "← Quay lại"))
        self.titleIcon.setText(_translate("MainWindow", "🌍"))
        self.mainTitle.setText(_translate("MainWindow", "Môi trường & Động vật"))
        self.searchEdit.setPlaceholderText(_translate("MainWindow", "Search for..."))
        self.searchIcon.setText(_translate("MainWindow", "⌕"))
        self.categoryCombo.setItemText(0, _translate("MainWindow", "All Categories"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.card21Title.setText(_translate("MainWindow", "Chống hạn mặn Miền Tây (Thủy Tiên)"))
        self.card21Date.setText(_translate("MainWindow", "Date:      2020-04-01"))
        self.card21Owner.setText(_translate("MainWindow", "Owner:   Trần Thị Thủy Tiên"))
        self.card21Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card21More.setText(_translate("MainWindow", "Xem thêm"))
        self.card22Title.setText(_translate("MainWindow", "Trồng rừng đại ngàn (Green Việt)"))
        self.card22Date.setText(_translate("MainWindow", "Date:      2021-10-04"))
        self.card22Owner.setText(_translate("MainWindow", "Owner:   Trần Hữu Vỹ"))
        self.card22Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card22More.setText(_translate("MainWindow", "Xem thêm"))
        self.card23Title.setText(_translate("MainWindow", "Nước sạch cho bản làng (UNICEF)"))
        self.card23Date.setText(_translate("MainWindow", "Date:      2022-01-01"))
        self.card23Owner.setText(_translate("MainWindow", "Owner:   Rana Flowers"))
        self.card23Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card23More.setText(_translate("MainWindow", "Xem thêm"))
        self.card24Title.setText(_translate("MainWindow", "Bảo tồn động vật hoang dã (WWF)"))
        self.card24Date.setText(_translate("MainWindow", "Date:      2023-01-01"))
        self.card24Owner.setText(_translate("MainWindow", "Owner:   Văn Ngọc Thịnh"))
        self.card24Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card24More.setText(_translate("MainWindow", "Xem thêm"))
        self.card25Title.setText(_translate("MainWindow", "Nước sạch cho vùng hạn mặn"))
        self.card25Date.setText(_translate("MainWindow", "Date:      2024-03-10"))
        self.card25Owner.setText(_translate("MainWindow", "Owner:   Trần Thị Thủy Tiên"))
        self.card25Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card25More.setText(_translate("MainWindow", "Xem thêm"))
        self.card26Title.setText(_translate("MainWindow", "Dự án Vì một Việt Nam xanh (Trồng cây)"))
        self.card26Date.setText(_translate("MainWindow", "Date:      2024-01-10"))
        self.card26Owner.setText(_translate("MainWindow", "Owner:   Trần Hữu Vỹ"))
        self.card26Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card26More.setText(_translate("MainWindow", "Xem thêm"))
