# Form implementation generated from reading ui file 'c:\Users\ADMIN\OneDrive\Documents\UEL.ktlt\BaiDuAn\profile.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 900))
        MainWindow.setStyleSheet("QMainWindow, QWidget {\n"
"    background: #FFF3F9;\n"
"    font-family: \"Segoe UI\";\n"
"    color: #222222;\n"
"}\n"
"\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QFrame {\n"
"    border: none;\n"
"    background: transparent;\n"
"}\n"
"\n"
"#logoTitle {\n"
"    color: #B84588;\n"
"    font-size: 26px;\n"
"    font-weight: 800;\n"
"}\n"
"\n"
"#logoSub {\n"
"    color: #8E8E8E;\n"
"    font-size: 10px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"#backLabel {\n"
"    color: #111111;\n"
"    font-size: 18px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"#sectionTitle {\n"
"    color: #222222;\n"
"    font-size: 32px;\n"
"    font-weight: 800;\n"
"}\n"
"\n"
"#profileCard {\n"
"    background: rgba(255, 243, 249, 180);\n"
"    border: 2px solid #F1B6C9;\n"
"    border-radius: 24px;\n"
"}\n"
"\n"
"#avatarBox {\n"
"    background: #D9DDDE;\n"
"    border: none;\n"
"}\n"
"\n"
"#avatarIcon {\n"
"    color: #A9ADB7;\n"
"    font-size: 110px;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"#cameraIcon {\n"
"    color: #1E1E1E;\n"
"    font-size: 18px;\n"
"    font-weight: 700;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sectionTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.sectionTitle.setGeometry(QtCore.QRect(430, 240, 340, 50))
        self.sectionTitle.setObjectName("sectionTitle")
        self.profileCard = QtWidgets.QFrame(parent=self.centralwidget)
        self.profileCard.setGeometry(QtCore.QRect(50, 300, 1085, 555))
        self.profileCard.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.profileCard.setObjectName("profileCard")
        self.labelUser_3 = QtWidgets.QLabel(parent=self.profileCard)
        self.labelUser_3.setGeometry(QtCore.QRect(80, 20, 51, 51))
        self.labelUser_3.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelUser_3.setObjectName("labelUser_3")
        self.profileCard_2 = QtWidgets.QFrame(parent=self.profileCard)
        self.profileCard_2.setGeometry(QtCore.QRect(430, 170, 1085, 555))
        self.profileCard_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.profileCard_2.setObjectName("profileCard_2")
        self.labelUser_8 = QtWidgets.QLabel(parent=self.profileCard_2)
        self.labelUser_8.setGeometry(QtCore.QRect(250, 0, 31, 31))
        self.labelUser_8.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelUser_8.setObjectName("labelUser_8")
        self.labelUser_9 = QtWidgets.QLabel(parent=self.profileCard_2)
        self.labelUser_9.setGeometry(QtCore.QRect(250, 130, 31, 31))
        self.labelUser_9.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelUser_9.setObjectName("labelUser_9")
        self.labelUser_4 = QtWidgets.QLabel(parent=self.profileCard)
        self.labelUser_4.setGeometry(QtCore.QRect(80, 170, 31, 31))
        self.labelUser_4.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelUser_4.setObjectName("labelUser_4")
        self.labelUser_5 = QtWidgets.QLabel(parent=self.profileCard)
        self.labelUser_5.setGeometry(QtCore.QRect(80, 300, 31, 31))
        self.labelUser_5.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelUser_5.setObjectName("labelUser_5")
        self.labelUser_6 = QtWidgets.QLabel(parent=self.profileCard)
        self.labelUser_6.setGeometry(QtCore.QRect(80, 430, 31, 31))
        self.labelUser_6.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelUser_6.setObjectName("labelUser_6")
        self.labelUser_7 = QtWidgets.QLabel(parent=self.profileCard)
        self.labelUser_7.setGeometry(QtCore.QRect(690, 40, 31, 31))
        self.labelUser_7.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelUser_7.setObjectName("labelUser_7")
        self.NutXacThuc = QtWidgets.QPushButton(parent=self.profileCard)
        self.NutXacThuc.setGeometry(QtCore.QRect(350, 500, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.NutXacThuc.setFont(font)
        self.NutXacThuc.setObjectName("NutXacThuc")
        self.labelUser = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelUser.setGeometry(QtCore.QRect(165, 338, 190, 28))
        self.labelUser.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelUser.setObjectName("labelUser")
        self.Ten = QtWidgets.QLabel(parent=self.centralwidget)
        self.Ten.setGeometry(QtCore.QRect(165, 378, 220, 30))
        self.Ten.setStyleSheet("font-size:19px; font-weight:800; color:#111111;")
        self.Ten.setObjectName("Ten")
        self.labelPhone = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelPhone.setGeometry(QtCore.QRect(165, 474, 190, 28))
        self.labelPhone.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelPhone.setObjectName("labelPhone")
        self.Sdt = QtWidgets.QLabel(parent=self.centralwidget)
        self.Sdt.setGeometry(QtCore.QRect(165, 514, 220, 30))
        self.Sdt.setStyleSheet("font-size:19px; font-weight:800; color:#111111;")
        self.Sdt.setObjectName("Sdt")
        self.labelEmail = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelEmail.setGeometry(QtCore.QRect(165, 602, 100, 28))
        self.labelEmail.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelEmail.setObjectName("labelEmail")
        self.Email = QtWidgets.QLabel(parent=self.centralwidget)
        self.Email.setGeometry(QtCore.QRect(165, 642, 430, 30))
        self.Email.setStyleSheet("font-size:19px; font-weight:800; color:#111111;")
        self.Email.setObjectName("Email")
        self.labelId = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelId.setGeometry(QtCore.QRect(165, 732, 120, 28))
        self.labelId.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelId.setObjectName("labelId")
        self.CCCD = QtWidgets.QLabel(parent=self.centralwidget)
        self.CCCD.setGeometry(QtCore.QRect(165, 772, 220, 30))
        self.CCCD.setStyleSheet("font-size:19px; font-weight:800; color:#111111;")
        self.CCCD.setObjectName("CCCD")
        self.labelGender = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelGender.setGeometry(QtCore.QRect(775, 338, 130, 28))
        self.labelGender.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelGender.setObjectName("labelGender")
        self.Gender = QtWidgets.QLabel(parent=self.centralwidget)
        self.Gender.setGeometry(QtCore.QRect(775, 378, 90, 30))
        self.Gender.setStyleSheet("font-size:19px; font-weight:800; color:#111111;")
        self.Gender.setObjectName("Gender")
        self.labelAddress = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelAddress.setGeometry(QtCore.QRect(770, 474, 100, 28))
        self.labelAddress.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelAddress.setObjectName("labelAddress")
        self.Address = QtWidgets.QLabel(parent=self.centralwidget)
        self.Address.setGeometry(QtCore.QRect(770, 514, 140, 30))
        self.Address.setStyleSheet("font-size:19px; font-weight:800; color:#111111;")
        self.Address.setObjectName("Address")
        self.labelType = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelType.setGeometry(QtCore.QRect(772, 602, 180, 28))
        self.labelType.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelType.setObjectName("labelType")
        self.Type = QtWidgets.QLabel(parent=self.centralwidget)
        self.Type.setGeometry(QtCore.QRect(772, 642, 250, 30))
        self.Type.setStyleSheet("font-size:19px; font-weight:800; color:#111111;")
        self.Type.setObjectName("Type")
        self.cloud1 = QtWidgets.QFrame(parent=self.centralwidget)
        self.cloud1.setGeometry(QtCore.QRect(820, 800, 130, 60))
        self.cloud1.setStyleSheet("background: rgba(255,255,255,220); border-radius: 30px;")
        self.cloud1.setObjectName("cloud1")
        self.cloud2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.cloud2.setGeometry(QtCore.QRect(900, 780, 170, 85))
        self.cloud2.setStyleSheet("background: rgba(255,255,255,230); border-radius: 42px;")
        self.cloud2.setObjectName("cloud2")
        self.cloud3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.cloud3.setGeometry(QtCore.QRect(995, 742, 230, 158))
        self.cloud3.setStyleSheet("background: rgba(255,255,255,235); border-radius: 79px;")
        self.cloud3.setObjectName("cloud3")
        self.cloud4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.cloud4.setGeometry(QtCore.QRect(1085, 800, 140, 100))
        self.cloud4.setStyleSheet("background: rgba(255,232,239,180); border-radius: 50px;")
        self.cloud4.setObjectName("cloud4")
        self.star1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.star1.setGeometry(QtCore.QRect(1020, 650, 24, 24))
        self.star1.setStyleSheet("color:#F4C1D4; font-size:20px; font-weight:800;")
        self.star1.setObjectName("star1")
        self.star2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.star2.setGeometry(QtCore.QRect(960, 740, 20, 20))
        self.star2.setStyleSheet("color:#F6CCD9; font-size:16px; font-weight:800;")
        self.star2.setObjectName("star2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 160, 47, 13))
        self.label.setText("")
        self.label.setObjectName("label")
        self.logo_subtitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.logo_subtitle.setGeometry(QtCore.QRect(138, 42, 80, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.logo_subtitle.setFont(font)
        self.logo_subtitle.setStyleSheet("QLabel{\n"
"    color: #8F7B87;\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.logo_subtitle.setObjectName("logo_subtitle")
        self.logo_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.logo_title.setGeometry(QtCore.QRect(57, 2, 170, 42))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.logo_title.setFont(font)
        self.logo_title.setStyleSheet("QLabel{\n"
"    color: #7D2B6E;\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.logo_title.setObjectName("logo_title")
        self.back = QtWidgets.QLabel(parent=self.centralwidget)
        self.back.setGeometry(QtCore.QRect(17, 62, 120, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.back.setFont(font)
        self.back.setObjectName("back")
        self.logo_icon = QtWidgets.QLabel(parent=self.centralwidget)
        self.logo_icon.setGeometry(QtCore.QRect(20, 10, 42, 34))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.logo_icon.setFont(font)
        self.logo_icon.setStyleSheet("QLabel{\n"
"    background: transparent;\n"
"    color: #7D2B6E;\n"
"    border: none;\n"
"}")
        self.logo_icon.setObjectName("logo_icon")
        self.sectionTitle_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.sectionTitle_2.setGeometry(QtCore.QRect(800, 490, 340, 50))
        self.sectionTitle_2.setObjectName("sectionTitle_2")
        self.sectionTitle_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.sectionTitle_3.setGeometry(QtCore.QRect(510, 190, 141, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.sectionTitle_3.setFont(font)
        self.sectionTitle_3.setObjectName("sectionTitle_3")
        self.avatarBox = QtWidgets.QFrame(parent=self.centralwidget)
        self.avatarBox.setGeometry(QtCore.QRect(780, 50, 350, 190))
        self.avatarBox.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.avatarBox.setObjectName("avatarBox")
        self.avatarIcon = QtWidgets.QLabel(parent=self.avatarBox)
        self.avatarIcon.setGeometry(QtCore.QRect(120, 30, 120, 130))
        self.avatarIcon.setObjectName("avatarIcon")
        self.avt = QtWidgets.QLabel(parent=self.avatarBox)
        self.avt.setGeometry(QtCore.QRect(310, 150, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.avt.setFont(font)
        self.avt.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.avt.setObjectName("avt")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Donarity - Cai dat"))
        self.sectionTitle.setText(_translate("MainWindow", "Thông tin cá nhân"))
        self.labelUser_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">🙍‍</span></p></body></html>"))
        self.labelUser_8.setText(_translate("MainWindow", "<html><head/><body><p>🕹</p></body></html>"))
        self.labelUser_9.setText(_translate("MainWindow", "<html><head/><body><p>🎫</p></body></html>"))
        self.labelUser_4.setText(_translate("MainWindow", "<html><head/><body><p>📞</p></body></html>"))
        self.labelUser_5.setText(_translate("MainWindow", "<html><head/><body><p>💌</p></body></html>"))
        self.labelUser_6.setText(_translate("MainWindow", "<html><head/><body><p>🎞</p></body></html>"))
        self.labelUser_7.setText(_translate("MainWindow", "<html><head/><body><p>🚺</p></body></html>"))
        self.NutXacThuc.setText(_translate("MainWindow", "Xác thực"))
        self.labelUser.setText(_translate("MainWindow", "Tên người dùng"))
        self.Ten.setText(_translate("MainWindow", "..."))
        self.labelPhone.setText(_translate("MainWindow", "Số điện thoại"))
        self.Sdt.setText(_translate("MainWindow", "..."))
        self.labelEmail.setText(_translate("MainWindow", "Email"))
        self.Email.setText(_translate("MainWindow", "..."))
        self.labelId.setText(_translate("MainWindow", "Căn cước"))
        self.CCCD.setText(_translate("MainWindow", "..."))
        self.labelGender.setText(_translate("MainWindow", "Giới tính"))
        self.Gender.setText(_translate("MainWindow", "..."))
        self.labelAddress.setText(_translate("MainWindow", "Địa chỉ"))
        self.Address.setText(_translate("MainWindow", "..."))
        self.labelType.setText(_translate("MainWindow", "Loại tài khoản"))
        self.Type.setText(_translate("MainWindow", "..."))
        self.star1.setText(_translate("MainWindow", "✦"))
        self.star2.setText(_translate("MainWindow", "✦"))
        self.logo_subtitle.setText(_translate("MainWindow", "by group 10"))
        self.logo_title.setText(_translate("MainWindow", "Donarity"))
        self.back.setText(_translate("MainWindow", "← Quay lại"))
        self.logo_icon.setText(_translate("MainWindow", "🕊"))
        self.sectionTitle_2.setText(_translate("MainWindow", "Thông tin cá nhân"))
        self.sectionTitle_3.setText(_translate("MainWindow", "CÀI ĐẶT"))
        self.avatarIcon.setText(_translate("MainWindow", "👤"))
        self.avt.setText(_translate("MainWindow", "<html><head/><body><p>📷</p></body></html>"))
