# Form implementation generated from reading ui file 'c:\Users\ADMIN\OneDrive\Documents\UEL.ktlt\BaiDuAn\giaodien\setting.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 760)
        MainWindow.setStyleSheet("QMainWindow, QWidget {\n"
"    background: #FFF3F9;\n"
"    font-family: \"Segoe UI\";\n"
"    color: #222222;\n"
"}\n"
"\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QFrame {\n"
"    border: none;\n"
"    background: transparent;\n"
"}\n"
"\n"
"#logoTitle {\n"
"    color: #B84588;\n"
"    font-size: 26px;\n"
"    font-weight: 800;\n"
"}\n"
"\n"
"#logoSub {\n"
"    color: #8E8E8E;\n"
"    font-size: 10px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"#backLabel {\n"
"    color: #111111;\n"
"    font-size: 18px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"#sectionTitle {\n"
"    color: #222222;\n"
"    font-size: 32px;\n"
"    font-weight: 800;\n"
"}\n"
"\n"
"#profileCard {\n"
"    background: rgba(255, 243, 249, 180);\n"
"    border: 2px solid #F1B6C9;\n"
"    border-radius: 24px;\n"
"}\n"
"\n"
"#avatarBox {\n"
"    background: #D9DDDE;\n"
"    border: none;\n"
"}\n"
"\n"
"#avatarIcon {\n"
"    color: #A9ADB7;\n"
"    font-size: 110px;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"#cameraIcon {\n"
"    color: #1E1E1E;\n"
"    font-size: 18px;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"/* ===== NAVBAR MỚI ===== */\n"
"QFrame#navFrame {\n"
"    background: #F5DCE6;\n"
"    border: none;\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"QLabel#logoImage {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QLabel#brandTitle {\n"
"    color: #9C4F74;\n"
"    font-size: 18pt;\n"
"    font-weight: 800;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel#brandSubtitle {\n"
"    color: #9D8A93;\n"
"    font-size: 8pt;\n"
"    font-weight: 500;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QPushButton#btnHome,\n"
"QPushButton#btnCreate,\n"
"QPushButton#btnFollow,\n"
"QPushButton#btnPublic {\n"
"    background: transparent;\n"
"    border: none;\n"
"    border-radius: 18px;\n"
"    padding: 10px 18px;\n"
"    color: #2C2328;\n"
"    font-size: 11pt;\n"
"    font-weight: 600;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton#btnHome:hover,\n"
"QPushButton#btnCreate:hover,\n"
"QPushButton#btnFollow:hover,\n"
"QPushButton#btnPublic:hover {\n"
"    background: #EEC9D8;\n"
"}\n"
"\n"
"QPushButton#btnHome:pressed,\n"
"QPushButton#btnCreate:pressed,\n"
"QPushButton#btnFollow:pressed,\n"
"QPushButton#btnPublic:pressed {\n"
"    background: #E2B5C7;\n"
"}\n"
"\n"
"QPushButton#btnHome {\n"
"    background: #C98AA5;\n"
"    color: white;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"QToolButton#btnNotify,\n"
"QToolButton#btnSetting,\n"
"QToolButton#btnProfile {\n"
"    background: transparent;\n"
"    border: none;\n"
"    border-radius: 18px;\n"
"    color: #2C2328;\n"
"    font-size: 16pt;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QToolButton#btnNotify:hover,\n"
"QToolButton#btnSetting:hover,\n"
"QToolButton#btnProfile:hover {\n"
"    background: #EEC9D8;\n"
"}\n"
"\n"
"QLabel#notifyBadge {\n"
"    background: #E74C3C;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    font-size: 8pt;\n"
"    font-weight: 700;\n"
"    padding: 0px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(135, 168, 47, 13))
        self.label.setText("")
        self.label.setObjectName("label")
        self.avatarBox = QtWidgets.QFrame(parent=self.centralwidget)
        self.avatarBox.setGeometry(QtCore.QRect(775, 89, 350, 171))
        self.avatarBox.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.avatarBox.setObjectName("avatarBox")
        self.avatarIcon = QtWidgets.QLabel(parent=self.avatarBox)
        self.avatarIcon.setGeometry(QtCore.QRect(120, 20, 120, 130))
        self.avatarIcon.setObjectName("avatarIcon")
        self.Gender = QtWidgets.QLabel(parent=self.centralwidget)
        self.Gender.setGeometry(QtCore.QRect(765, 368, 90, 30))
        self.Gender.setStyleSheet("font-size:19px; font-weight:800; color:#111111;")
        self.Gender.setObjectName("Gender")
        self.labelUser = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelUser.setGeometry(QtCore.QRect(155, 328, 190, 28))
        self.labelUser.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelUser.setObjectName("labelUser")
        self.Address = QtWidgets.QLabel(parent=self.centralwidget)
        self.Address.setGeometry(QtCore.QRect(760, 462, 140, 30))
        self.Address.setStyleSheet("font-size:19px; font-weight:800; color:#111111;")
        self.Address.setObjectName("Address")
        self.Sdt = QtWidgets.QLabel(parent=self.centralwidget)
        self.Sdt.setGeometry(QtCore.QRect(155, 442, 220, 30))
        self.Sdt.setStyleSheet("font-size:19px; font-weight:800; color:#111111;")
        self.Sdt.setObjectName("Sdt")
        self.labelType = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelType.setGeometry(QtCore.QRect(762, 520, 180, 28))
        self.labelType.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelType.setObjectName("labelType")
        self.labelPhone = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelPhone.setGeometry(QtCore.QRect(155, 402, 190, 28))
        self.labelPhone.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelPhone.setObjectName("labelPhone")
        self.labelEmail = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelEmail.setGeometry(QtCore.QRect(155, 490, 100, 28))
        self.labelEmail.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelEmail.setObjectName("labelEmail")
        self.Ten = QtWidgets.QLabel(parent=self.centralwidget)
        self.Ten.setGeometry(QtCore.QRect(155, 368, 220, 30))
        self.Ten.setStyleSheet("font-size:19px; font-weight:800; color:#111111;")
        self.Ten.setObjectName("Ten")
        self.labelId = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelId.setGeometry(QtCore.QRect(155, 582, 120, 28))
        self.labelId.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelId.setObjectName("labelId")
        self.CCCD = QtWidgets.QLabel(parent=self.centralwidget)
        self.CCCD.setGeometry(QtCore.QRect(155, 622, 220, 30))
        self.CCCD.setStyleSheet("font-size:19px; font-weight:800; color:#111111;")
        self.CCCD.setObjectName("CCCD")
        self.labelAddress = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelAddress.setGeometry(QtCore.QRect(760, 422, 100, 28))
        self.labelAddress.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelAddress.setObjectName("labelAddress")
        self.Type = QtWidgets.QLabel(parent=self.centralwidget)
        self.Type.setGeometry(QtCore.QRect(762, 560, 250, 30))
        self.Type.setStyleSheet("font-size:19px; font-weight:800; color:#111111;")
        self.Type.setObjectName("Type")
        self.profileCard = QtWidgets.QFrame(parent=self.centralwidget)
        self.profileCard.setGeometry(QtCore.QRect(40, 290, 1085, 411))
        self.profileCard.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.profileCard.setObjectName("profileCard")
        self.labelUser_17 = QtWidgets.QLabel(parent=self.profileCard)
        self.labelUser_17.setGeometry(QtCore.QRect(80, 20, 51, 51))
        self.labelUser_17.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelUser_17.setObjectName("labelUser_17")
        self.profileCard_4 = QtWidgets.QFrame(parent=self.profileCard)
        self.profileCard_4.setGeometry(QtCore.QRect(430, 170, 1085, 555))
        self.profileCard_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.profileCard_4.setObjectName("profileCard_4")
        self.labelUser_18 = QtWidgets.QLabel(parent=self.profileCard_4)
        self.labelUser_18.setGeometry(QtCore.QRect(250, -42, 31, 31))
        self.labelUser_18.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelUser_18.setObjectName("labelUser_18")
        self.labelUser_19 = QtWidgets.QLabel(parent=self.profileCard_4)
        self.labelUser_19.setGeometry(QtCore.QRect(250, 58, 31, 31))
        self.labelUser_19.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelUser_19.setObjectName("labelUser_19")
        self.star1_3 = QtWidgets.QLabel(parent=self.profileCard_4)
        self.star1_3.setGeometry(QtCore.QRect(590, 150, 24, 24))
        self.star1_3.setStyleSheet("color:#F4C1D4; font-size:20px; font-weight:800;")
        self.star1_3.setObjectName("star1_3")
        self.labelUser_20 = QtWidgets.QLabel(parent=self.profileCard)
        self.labelUser_20.setGeometry(QtCore.QRect(80, 108, 31, 31))
        self.labelUser_20.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelUser_20.setObjectName("labelUser_20")
        self.labelUser_21 = QtWidgets.QLabel(parent=self.profileCard)
        self.labelUser_21.setGeometry(QtCore.QRect(80, 198, 31, 31))
        self.labelUser_21.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelUser_21.setObjectName("labelUser_21")
        self.labelUser_22 = QtWidgets.QLabel(parent=self.profileCard)
        self.labelUser_22.setGeometry(QtCore.QRect(80, 290, 31, 31))
        self.labelUser_22.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelUser_22.setObjectName("labelUser_22")
        self.labelUser_23 = QtWidgets.QLabel(parent=self.profileCard)
        self.labelUser_23.setGeometry(QtCore.QRect(690, 40, 31, 31))
        self.labelUser_23.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelUser_23.setObjectName("labelUser_23")
        self.labelUser_24 = QtWidgets.QLabel(parent=self.profileCard)
        self.labelUser_24.setGeometry(QtCore.QRect(690, 130, 31, 31))
        self.labelUser_24.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelUser_24.setObjectName("labelUser_24")
        self.labelGender = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelGender.setGeometry(QtCore.QRect(765, 328, 130, 28))
        self.labelGender.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelGender.setObjectName("labelGender")
        self.Email = QtWidgets.QLabel(parent=self.centralwidget)
        self.Email.setGeometry(QtCore.QRect(155, 530, 430, 30))
        self.Email.setStyleSheet("font-size:19px; font-weight:800; color:#111111;")
        self.Email.setObjectName("Email")
        self.labelUser_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelUser_2.setGeometry(QtCore.QRect(460, 230, 241, 51))
        self.labelUser_2.setStyleSheet("font-size:19px; font-weight:500; color:#262626;")
        self.labelUser_2.setObjectName("labelUser_2")
        self.brandSubtitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.brandSubtitle.setGeometry(QtCore.QRect(50, 42, 182, 13))
        self.brandSubtitle.setObjectName("brandSubtitle")
        self.logoImage = QtWidgets.QLabel(parent=self.centralwidget)
        self.logoImage.setGeometry(QtCore.QRect(10, 13, 40, 40))
        self.logoImage.setMinimumSize(QtCore.QSize(40, 40))
        self.logoImage.setMaximumSize(QtCore.QSize(40, 40))
        self.logoImage.setObjectName("logoImage")
        self.brandTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.brandTitle.setGeometry(QtCore.QRect(50, 10, 182, 32))
        self.brandTitle.setObjectName("brandTitle")
        self.back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back.setGeometry(QtCore.QRect(20, 70, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.back.setFont(font)
        self.back.setObjectName("back")
        self.profileCard.raise_()
        self.label.raise_()
        self.avatarBox.raise_()
        self.Gender.raise_()
        self.labelUser.raise_()
        self.Address.raise_()
        self.Sdt.raise_()
        self.labelType.raise_()
        self.labelPhone.raise_()
        self.labelEmail.raise_()
        self.Ten.raise_()
        self.labelId.raise_()
        self.CCCD.raise_()
        self.labelAddress.raise_()
        self.Type.raise_()
        self.labelGender.raise_()
        self.Email.raise_()
        self.labelUser_2.raise_()
        self.brandSubtitle.raise_()
        self.logoImage.raise_()
        self.brandTitle.raise_()
        self.back.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Donarity - Cai dat"))
        self.avatarIcon.setText(_translate("MainWindow", "👤"))
        self.Gender.setText(_translate("MainWindow", "..."))
        self.labelUser.setText(_translate("MainWindow", "Tên người dùng"))
        self.Address.setText(_translate("MainWindow", "..."))
        self.Sdt.setText(_translate("MainWindow", "..."))
        self.labelType.setText(_translate("MainWindow", "Loại tài khoản"))
        self.labelPhone.setText(_translate("MainWindow", "Số điện thoại"))
        self.labelEmail.setText(_translate("MainWindow", "Email"))
        self.Ten.setText(_translate("MainWindow", "..."))
        self.labelId.setText(_translate("MainWindow", "Căn cước"))
        self.CCCD.setText(_translate("MainWindow", "..."))
        self.labelAddress.setText(_translate("MainWindow", "Địa chỉ"))
        self.Type.setText(_translate("MainWindow", "..."))
        self.labelUser_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">🙍‍</span></p></body></html>"))
        self.labelUser_18.setText(_translate("MainWindow", "<html><head/><body><p>🕹</p></body></html>"))
        self.labelUser_19.setText(_translate("MainWindow", "<html><head/><body><p>🎫</p></body></html>"))
        self.star1_3.setText(_translate("MainWindow", "✦"))
        self.labelUser_20.setText(_translate("MainWindow", "<html><head/><body><p>📞</p></body></html>"))
        self.labelUser_21.setText(_translate("MainWindow", "<html><head/><body><p>💌</p></body></html>"))
        self.labelUser_22.setText(_translate("MainWindow", "<html><head/><body><p>🎞</p></body></html>"))
        self.labelUser_23.setText(_translate("MainWindow", "<html><head/><body><p>🚺</p></body></html>"))
        self.labelUser_24.setText(_translate("MainWindow", "<html><head/><body><p>🏠</p></body></html>"))
        self.labelGender.setText(_translate("MainWindow", "Giới tính"))
        self.Email.setText(_translate("MainWindow", "..."))
        self.labelUser_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">Thông tin cá nhân</span></p></body></html>"))
        self.brandSubtitle.setText(_translate("MainWindow", "by group 10"))
        self.logoImage.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; color:#9c4f74;\">🕊</span></p></body></html>"))
        self.brandTitle.setText(_translate("MainWindow", "Donarity"))
        self.back.setText(_translate("MainWindow", "Quay lại"))
