# Form implementation generated from reading ui file 'C:\Users\ADMIN\PycharmProjects\DoAnKTLT\successful_campaign.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 760)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 760))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 760))
        MainWindow.setStyleSheet("QMainWindow, QWidget{\n"
"background:#FFF3F9;\n"
"font-family:\"Segoe UI\";\n"
"}\n"
"\n"
"QFrame#topBar{\n"
"background:#F4D8E3;\n"
"border:none;\n"
"}\n"
"\n"
"QLabel#logoText{\n"
"font-size:18px;\n"
"font-weight:700;\n"
"color:#7A4E6A;\n"
"}\n"
"\n"
"QLabel#menu1, QLabel#menu2, QLabel#menu3, QLabel#menu4{\n"
"font-size:14px;\n"
"font-weight:600;\n"
"color:#2F2A2E;\n"
"padding:6px 10px;\n"
"}\n"
"\n"
"QLabel#menu2{\n"
"background:#E8BFD0;\n"
"border-radius:14px;\n"
"padding:8px 14px;\n"
"}\n"
"\n"
"QLabel#bellIcon, QLabel#userIcon{\n"
"font-size:20px;\n"
"color:#2F2A2E;\n"
"}\n"
"\n"
"QLabel#titleLabel{\n"
"font-size:32px;\n"
"font-weight:700;\n"
"color:#6C4A63;\n"
"background:transparent;\n"
"}\n"
"\n"
"QLabel#descLabel{\n"
"font-size:16px;\n"
"color:#444444;\n"
"background:transparent;\n"
"}\n"
"\n"
"QFrame#contentFrame{\n"
"background:#FFFFFF;\n"
"border:none;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton#backButton{\n"
"background:transparent;\n"
"border:none;\n"
"font-size:14px;\n"
"font-weight:600;\n"
"color:#333333;\n"
"text-align:left;\n"
"padding-left:6px;\n"
"}\n"
"\n"
"QPushButton#backButton:hover{\n"
"color:#6C4A63;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(14)
        self.mainLayout.setObjectName("mainLayout")
        self.topBar = QtWidgets.QFrame(parent=self.centralwidget)
        self.topBar.setMinimumSize(QtCore.QSize(0, 54))
        self.topBar.setMaximumSize(QtCore.QSize(16777215, 54))
        self.topBar.setObjectName("topBar")
        self.topBarLayout = QtWidgets.QHBoxLayout(self.topBar)
        self.topBarLayout.setContentsMargins(16, 0, 16, 0)
        self.topBarLayout.setSpacing(18)
        self.topBarLayout.setObjectName("topBarLayout")
        self.logoText = QtWidgets.QLabel(parent=self.topBar)
        self.logoText.setObjectName("logoText")
        self.topBarLayout.addWidget(self.logoText)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.topBarLayout.addItem(spacerItem)
        self.menu1 = QtWidgets.QLabel(parent=self.topBar)
        self.menu1.setObjectName("menu1")
        self.topBarLayout.addWidget(self.menu1)
        self.menu2 = QtWidgets.QLabel(parent=self.topBar)
        self.menu2.setObjectName("menu2")
        self.topBarLayout.addWidget(self.menu2)
        self.menu3 = QtWidgets.QLabel(parent=self.topBar)
        self.menu3.setObjectName("menu3")
        self.topBarLayout.addWidget(self.menu3)
        self.menu4 = QtWidgets.QLabel(parent=self.topBar)
        self.menu4.setObjectName("menu4")
        self.topBarLayout.addWidget(self.menu4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.topBarLayout.addItem(spacerItem1)
        self.bellIcon = QtWidgets.QLabel(parent=self.topBar)
        self.bellIcon.setObjectName("bellIcon")
        self.topBarLayout.addWidget(self.bellIcon)
        self.userIcon = QtWidgets.QLabel(parent=self.topBar)
        self.userIcon.setObjectName("userIcon")
        self.topBarLayout.addWidget(self.userIcon)
        self.mainLayout.addWidget(self.topBar)
        self.backLayout = QtWidgets.QHBoxLayout()
        self.backLayout.setContentsMargins(12, 0, 0, 0)
        self.backLayout.setObjectName("backLayout")
        self.backButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.backButton.setMinimumSize(QtCore.QSize(100, 28))
        self.backButton.setObjectName("backButton")
        self.backLayout.addWidget(self.backButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.backLayout.addItem(spacerItem2)
        self.mainLayout.addLayout(self.backLayout)
        self.contentOuterLayout = QtWidgets.QHBoxLayout()
        self.contentOuterLayout.setContentsMargins(42, 10, 42, 32)
        self.contentOuterLayout.setObjectName("contentOuterLayout")
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.contentOuterLayout.addItem(spacerItem3)
        self.contentFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.contentFrame.setMinimumSize(QtCore.QSize(1040, 580))
        self.contentFrame.setMaximumSize(QtCore.QSize(1040, 580))
        self.contentFrame.setObjectName("contentFrame")
        self.contentLayout = QtWidgets.QVBoxLayout(self.contentFrame)
        self.contentLayout.setContentsMargins(40, 34, 40, 24)
        self.contentLayout.setSpacing(18)
        self.contentLayout.setObjectName("contentLayout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.contentLayout.addItem(spacerItem4)
        self.checkIcon = QtWidgets.QLabel(parent=self.contentFrame)
        self.checkIcon.setMinimumSize(QtCore.QSize(110, 110))
        self.checkIcon.setMaximumSize(QtCore.QSize(110, 110))
        self.checkIcon.setText("")
        self.checkIcon.setPixmap(QtGui.QPixmap("check_success.png"))
        self.checkIcon.setScaledContents(True)
        self.checkIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.checkIcon.setObjectName("checkIcon")
        self.contentLayout.addWidget(self.checkIcon, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.titleLabel = QtWidgets.QLabel(parent=self.contentFrame)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.contentLayout.addWidget(self.titleLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.descLabel = QtWidgets.QLabel(parent=self.contentFrame)
        self.descLabel.setMinimumSize(QtCore.QSize(720, 80))
        self.descLabel.setMaximumSize(QtCore.QSize(800, 100))
        self.descLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.descLabel.setWordWrap(True)
        self.descLabel.setObjectName("descLabel")
        self.contentLayout.addWidget(self.descLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem5 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.contentLayout.addItem(spacerItem5)
        self.coinImage = QtWidgets.QLabel(parent=self.contentFrame)
        self.coinImage.setMinimumSize(QtCore.QSize(250, 170))
        self.coinImage.setMaximumSize(QtCore.QSize(250, 170))
        self.coinImage.setText("")
        self.coinImage.setPixmap(QtGui.QPixmap("donation_box.png"))
        self.coinImage.setScaledContents(True)
        self.coinImage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.coinImage.setObjectName("coinImage")
        self.contentLayout.addWidget(self.coinImage, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignBottom)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.contentLayout.addItem(spacerItem6)
        self.contentOuterLayout.addWidget(self.contentFrame)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.contentOuterLayout.addItem(spacerItem7)
        self.mainLayout.addLayout(self.contentOuterLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Donarity - Tạo chiến dịch thành công"))
        self.logoText.setText(_translate("MainWindow", "💗 Donarity"))
        self.menu1.setText(_translate("MainWindow", "🏠 Trang chủ"))
        self.menu2.setText(_translate("MainWindow", "➕ Tạo chiến dịch"))
        self.menu3.setText(_translate("MainWindow", "📁 Theo dõi chiến dịch"))
        self.menu4.setText(_translate("MainWindow", "🌐 Công khai"))
        self.bellIcon.setText(_translate("MainWindow", "🔔"))
        self.userIcon.setText(_translate("MainWindow", "👤"))
        self.backButton.setText(_translate("MainWindow", "← Quay lại"))
        self.titleLabel.setText(_translate("MainWindow", "Tạo chiến dịch thành công!"))
        self.descLabel.setText(_translate("MainWindow", "Chiến dịch của bạn đã được xác nhận thành công và sẵn sàng hoạt động.\n"
"\n"
"Cảm ơn vì đã hành động tử tế để lan tỏa yêu thương!"))
