# Form implementation generated from reading ui file 'C:\Users\ADMIN\PycharmProjects\DoAnKTLT\done\thong_bao.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 760)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 760))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 760))
        MainWindow.setStyleSheet("QMainWindow, QWidget {\n"
"    background: #FDF2F7;\n"
"    font-family: \"Segoe UI\";\n"
"    color: #2F2A2E;\n"
"}\n"
"\n"
"QWidget#centralwidget {\n"
"    background: #FDF2F7;\n"
"}\n"
"\n"
"QLabel#logoIcon {\n"
"    background: transparent;\n"
"    color: #963F75;\n"
"    font-size: 26pt;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"QLabel#logoText {\n"
"    color: #963F75;\n"
"    font-size: 18pt;\n"
"    font-weight: 800;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel#logoSubText {\n"
"    color: #9A7D8F;\n"
"    font-size: 8pt;\n"
"    font-weight: 600;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QPushButton#backButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #1F1B1D;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"    text-align: left;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QPushButton#backButton:hover {\n"
"    color: #7B4B66;\n"
"}\n"
"\n"
"QLabel#pageTitle {\n"
"    background: transparent;\n"
"    color: #2E2A2C;\n"
"    font-size: 24pt;\n"
"    font-weight: 800;\n"
"}\n"
"\n"
"QFrame#noticeFrame {\n"
"    background: transparent;\n"
"    border: 2px solid #F2B7C9;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QLabel#emptyLabel {\n"
"    background: transparent;\n"
"    color: #2D2A2B;\n"
"    font-size: 14pt;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QLabel#cloudDecor {\n"
"    background: transparent;\n"
"    color: #F6D3DF;\n"
"    font-size: 80pt;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"QLabel#spark1, QLabel#spark2, QLabel#spark3 {\n"
"    background: transparent;\n"
"    color: #F3B3C7;\n"
"    font-size: 12pt;\n"
"    font-weight: 700;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logoGroup = QtWidgets.QWidget(parent=self.centralwidget)
        self.logoGroup.setGeometry(QtCore.QRect(24, 8, 210, 58))
        self.logoGroup.setObjectName("logoGroup")
        self.logoIcon = QtWidgets.QLabel(parent=self.logoGroup)
        self.logoIcon.setGeometry(QtCore.QRect(0, 2, 54, 50))
        self.logoIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoIcon.setObjectName("logoIcon")
        self.logoText = QtWidgets.QLabel(parent=self.logoGroup)
        self.logoText.setGeometry(QtCore.QRect(52, 5, 125, 28))
        self.logoText.setObjectName("logoText")
        self.logoSubText = QtWidgets.QLabel(parent=self.logoGroup)
        self.logoSubText.setGeometry(QtCore.QRect(55, 30, 72, 16))
        self.logoSubText.setObjectName("logoSubText")
        self.backButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(44, 80, 100, 24))
        self.backButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.backButton.setObjectName("backButton")
        self.pageTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.pageTitle.setGeometry(QtCore.QRect(0, 102, 1200, 44))
        self.pageTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.pageTitle.setObjectName("pageTitle")
        self.noticeFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.noticeFrame.setGeometry(QtCore.QRect(87, 152, 995, 470))
        self.noticeFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.noticeFrame.setObjectName("noticeFrame")
        self.emptyLabel = QtWidgets.QLabel(parent=self.noticeFrame)
        self.emptyLabel.setGeometry(QtCore.QRect(0, 22, 995, 28))
        self.emptyLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.emptyLabel.setObjectName("emptyLabel")
        self.cloudDecor = QtWidgets.QLabel(parent=self.centralwidget)
        self.cloudDecor.setGeometry(QtCore.QRect(930, 560, 230, 150))
        self.cloudDecor.setObjectName("cloudDecor")
        self.spark1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.spark1.setGeometry(QtCore.QRect(975, 560, 22, 22))
        self.spark1.setObjectName("spark1")
        self.spark2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.spark2.setGeometry(QtCore.QRect(1048, 548, 18, 18))
        self.spark2.setObjectName("spark2")
        self.spark3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.spark3.setGeometry(QtCore.QRect(1088, 586, 18, 18))
        self.spark3.setObjectName("spark3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Donarity - Thông báo"))
        self.logoIcon.setText(_translate("MainWindow", "🕊"))
        self.logoText.setText(_translate("MainWindow", "Donarity"))
        self.logoSubText.setText(_translate("MainWindow", "by group 10"))
        self.backButton.setText(_translate("MainWindow", "← Quay lại"))
        self.pageTitle.setText(_translate("MainWindow", "Thông báo"))
        self.emptyLabel.setText(_translate("MainWindow", "Bạn không có thông báo nào"))
        self.cloudDecor.setText(_translate("MainWindow", "☁☁☁"))
        self.spark1.setText(_translate("MainWindow", "✦"))
        self.spark2.setText(_translate("MainWindow", "✦"))
        self.spark3.setText(_translate("MainWindow", "✦"))
