# Form implementation generated from reading ui file 'TreEm-NguoiYeuThe/treem_nguoiyeuthe.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(752, 1397)
        MainWindow.setMinimumSize(QtCore.QSize(752, 1397))
        MainWindow.setStyleSheet("QMainWindow, QWidget {\n"
"    background: #FFF6FB;\n"
"    font-family: \"Arial\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1200, 1397))
        self.scrollArea.setMinimumSize(QtCore.QSize(1200, 760))
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    border: none;\n"
"    background: #FFF6FB;\n"
"}\n"
"QScrollBar:vertical {\n"
"    background: #F8E8F0;\n"
"    width: 12px;\n"
"    border-radius: 6px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #D9AFC7;\n"
"    min-height: 40px;\n"
"    border-radius: 6px;\n"
"}\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: transparent;\n"
"}")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 752, 1675))
        self.scrollAreaWidgetContents.setStyleSheet("background: #FFF6FB;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.topBar = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.topBar.setGeometry(QtCore.QRect(0, 0, 752, 40))
        self.topBar.setStyleSheet("QFrame{\n"
"    background:#F9DDE7;\n"
"    border:none;\n"
"    border-radius:0px;\n"
"}")
        self.topBar.setObjectName("topBar")
        self.logoIcon = QtWidgets.QLabel(parent=self.topBar)
        self.logoIcon.setGeometry(QtCore.QRect(26, 5, 26, 26))
        self.logoIcon.setStyleSheet("QLabel{\n"
"    font-size:18px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.logoIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoIcon.setObjectName("logoIcon")
        self.logoTitle = QtWidgets.QLabel(parent=self.topBar)
        self.logoTitle.setGeometry(QtCore.QRect(50, 3, 92, 20))
        self.logoTitle.setStyleSheet("QLabel{\n"
"    color:#7E3A79;\n"
"    font-size:14px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.logoTitle.setObjectName("logoTitle")
        self.logoSub = QtWidgets.QLabel(parent=self.topBar)
        self.logoSub.setGeometry(QtCore.QRect(52, 20, 62, 12))
        self.logoSub.setStyleSheet("QLabel{\n"
"    color:#7A6D75;\n"
"    font-size:7px;\n"
"    font-weight:600;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.logoSub.setObjectName("logoSub")
        self.navHome = QtWidgets.QLabel(parent=self.topBar)
        self.navHome.setGeometry(QtCore.QRect(160, 9, 84, 18))
        self.navHome.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:9px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.navHome.setObjectName("navHome")
        self.navStats = QtWidgets.QLabel(parent=self.topBar)
        self.navStats.setGeometry(QtCore.QRect(263, 9, 80, 18))
        self.navStats.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:9px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.navStats.setObjectName("navStats")
        self.navChatbot = QtWidgets.QLabel(parent=self.topBar)
        self.navChatbot.setGeometry(QtCore.QRect(335, 9, 80, 18))
        self.navChatbot.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:9px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.navChatbot.setObjectName("navChatbot")
        self.notifIcon = QtWidgets.QLabel(parent=self.topBar)
        self.notifIcon.setGeometry(QtCore.QRect(664, 8, 18, 18))
        self.notifIcon.setStyleSheet("QLabel{\n"
"    font-size:13px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.notifIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.notifIcon.setObjectName("notifIcon")
        self.notifBadge = QtWidgets.QLabel(parent=self.topBar)
        self.notifBadge.setGeometry(QtCore.QRect(676, 6, 12, 12))
        self.notifBadge.setStyleSheet("QLabel{\n"
"    background:#E53935;\n"
"    color:white;\n"
"    border-radius:6px;\n"
"    font-size:7px;\n"
"    font-weight:800;\n"
"}")
        self.notifBadge.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.notifBadge.setObjectName("notifBadge")
        self.settingsIcon = QtWidgets.QLabel(parent=self.topBar)
        self.settingsIcon.setGeometry(QtCore.QRect(694, 8, 16, 18))
        self.settingsIcon.setStyleSheet("QLabel{\n"
"    font-size:13px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.settingsIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.settingsIcon.setObjectName("settingsIcon")
        self.userIcon = QtWidgets.QLabel(parent=self.topBar)
        self.userIcon.setGeometry(QtCore.QRect(716, 6, 18, 22))
        self.userIcon.setStyleSheet("QLabel{\n"
"    color:#2A2A2A;\n"
"    font-size:18px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.userIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.userIcon.setObjectName("userIcon")
        self.backLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.backLabel.setGeometry(QtCore.QRect(0, 50, 100, 18))
        self.backLabel.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:10px;\n"
"    font-weight:600;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.backLabel.setObjectName("backLabel")
        self.titleIcon = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.titleIcon.setGeometry(QtCore.QRect(18, 82, 36, 36))
        self.titleIcon.setStyleSheet("QLabel{\n"
"    font-size:24px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.titleIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleIcon.setObjectName("titleIcon")
        self.mainTitle = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.mainTitle.setGeometry(QtCore.QRect(66, 78, 380, 44))
        self.mainTitle.setStyleSheet("QLabel{\n"
"    color:#8A4E82;\n"
"    font-size:28px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.mainTitle.setObjectName("mainTitle")
        self.searchEdit = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.searchEdit.setGeometry(QtCore.QRect(10, 144, 496, 32))
        self.searchEdit.setStyleSheet("QLineEdit{\n"
"    background:white;\n"
"    border:1px solid #CFCFCF;\n"
"    padding-left:30px;\n"
"    color:#222;\n"
"    font-size:10px;\n"
"}")
        self.searchEdit.setObjectName("searchEdit")
        self.searchIcon = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.searchIcon.setGeometry(QtCore.QRect(22, 151, 16, 16))
        self.searchIcon.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:13px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.searchIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.searchIcon.setObjectName("searchIcon")
        self.categoryCombo = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.categoryCombo.setGeometry(QtCore.QRect(505, 144, 112, 32))
        self.categoryCombo.setStyleSheet("QComboBox{\n"
"    background:white;\n"
"    border:1px solid #CFCFCF;\n"
"    padding-left:8px;\n"
"    color:#222;\n"
"    font-size:10px;\n"
"}")
        self.categoryCombo.setObjectName("categoryCombo")
        self.categoryCombo.addItem("")
        self.searchButton = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.searchButton.setGeometry(QtCore.QRect(632, 144, 68, 32))
        self.searchButton.setStyleSheet("QPushButton{\n"
"    background:#FFF6FB;\n"
"    border:1px solid #7F4D7D;\n"
"    color:#222;\n"
"    font-size:10px;\n"
"    font-weight:700;\n"
"}")
        self.searchButton.setObjectName("searchButton")
        self.card7 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card7.setGeometry(QtCore.QRect(38, 217, 307, 257))
        self.card7.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card7.setObjectName("card7")
        self.card7Image = QtWidgets.QLabel(parent=self.card7)
        self.card7Image.setGeometry(QtCore.QRect(1, 1, 305, 128))
        self.card7Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card7Image.setPixmap(QtGui.QPixmap("TreEm-NguoiYeuThe\\campaign7.png"))
        self.card7Image.setScaledContents(True)
        self.card7Image.setObjectName("card7Image")
        self.card7Title = QtWidgets.QLabel(parent=self.card7)
        self.card7Title.setGeometry(QtCore.QRect(12, 138, 282, 40))
        self.card7Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card7Title.setWordWrap(True)
        self.card7Title.setObjectName("card7Title")
        self.card7Date = QtWidgets.QLabel(parent=self.card7)
        self.card7Date.setGeometry(QtCore.QRect(12, 177, 145, 16))
        self.card7Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card7Date.setObjectName("card7Date")
        self.card7Owner = QtWidgets.QLabel(parent=self.card7)
        self.card7Owner.setGeometry(QtCore.QRect(12, 193, 160, 16))
        self.card7Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card7Owner.setObjectName("card7Owner")
        self.card7Money = QtWidgets.QLabel(parent=self.card7)
        self.card7Money.setGeometry(QtCore.QRect(14, 215, 210, 20))
        self.card7Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card7Money.setObjectName("card7Money")
        self.card7Progress = QtWidgets.QProgressBar(parent=self.card7)
        self.card7Progress.setGeometry(QtCore.QRect(15, 237, 247, 8))
        self.card7Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card7Progress.setProperty("value", 30)
        self.card7Progress.setTextVisible(False)
        self.card7Progress.setObjectName("card7Progress")
        self.card7More = QtWidgets.QLabel(parent=self.card7)
        self.card7More.setGeometry(QtCore.QRect(16, 243, 80, 16))
        self.card7More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card7More.setObjectName("card7More")
        self.card8 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card8.setGeometry(QtCore.QRect(381, 217, 307, 257))
        self.card8.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card8.setObjectName("card8")
        self.card8Image = QtWidgets.QLabel(parent=self.card8)
        self.card8Image.setGeometry(QtCore.QRect(1, 1, 305, 128))
        self.card8Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card8Image.setPixmap(QtGui.QPixmap("TreEm-NguoiYeuThe\\campaign8.png"))
        self.card8Image.setScaledContents(True)
        self.card8Image.setObjectName("card8Image")
        self.card8Title = QtWidgets.QLabel(parent=self.card8)
        self.card8Title.setGeometry(QtCore.QRect(12, 138, 282, 36))
        self.card8Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card8Title.setWordWrap(True)
        self.card8Title.setObjectName("card8Title")
        self.card8Date = QtWidgets.QLabel(parent=self.card8)
        self.card8Date.setGeometry(QtCore.QRect(12, 177, 145, 16))
        self.card8Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card8Date.setObjectName("card8Date")
        self.card8Owner = QtWidgets.QLabel(parent=self.card8)
        self.card8Owner.setGeometry(QtCore.QRect(12, 193, 160, 16))
        self.card8Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card8Owner.setObjectName("card8Owner")
        self.card8Money = QtWidgets.QLabel(parent=self.card8)
        self.card8Money.setGeometry(QtCore.QRect(14, 215, 210, 20))
        self.card8Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card8Money.setObjectName("card8Money")
        self.card8Progress = QtWidgets.QProgressBar(parent=self.card8)
        self.card8Progress.setGeometry(QtCore.QRect(15, 237, 247, 8))
        self.card8Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card8Progress.setProperty("value", 30)
        self.card8Progress.setTextVisible(False)
        self.card8Progress.setObjectName("card8Progress")
        self.card8More = QtWidgets.QLabel(parent=self.card8)
        self.card8More.setGeometry(QtCore.QRect(16, 243, 80, 16))
        self.card8More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card8More.setObjectName("card8More")
        self.card9 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card9.setGeometry(QtCore.QRect(38, 512, 307, 257))
        self.card9.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card9.setObjectName("card9")
        self.card9Image = QtWidgets.QLabel(parent=self.card9)
        self.card9Image.setGeometry(QtCore.QRect(1, 1, 305, 128))
        self.card9Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card9Image.setPixmap(QtGui.QPixmap("TreEm-NguoiYeuThe\\campaign9.png"))
        self.card9Image.setScaledContents(True)
        self.card9Image.setObjectName("card9Image")
        self.card9Title = QtWidgets.QLabel(parent=self.card9)
        self.card9Title.setGeometry(QtCore.QRect(12, 138, 282, 42))
        self.card9Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card9Title.setWordWrap(True)
        self.card9Title.setObjectName("card9Title")
        self.card9Date = QtWidgets.QLabel(parent=self.card9)
        self.card9Date.setGeometry(QtCore.QRect(12, 177, 145, 16))
        self.card9Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card9Date.setObjectName("card9Date")
        self.card9Owner = QtWidgets.QLabel(parent=self.card9)
        self.card9Owner.setGeometry(QtCore.QRect(12, 193, 170, 16))
        self.card9Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card9Owner.setObjectName("card9Owner")
        self.card9Money = QtWidgets.QLabel(parent=self.card9)
        self.card9Money.setGeometry(QtCore.QRect(14, 215, 210, 20))
        self.card9Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card9Money.setObjectName("card9Money")
        self.card9Progress = QtWidgets.QProgressBar(parent=self.card9)
        self.card9Progress.setGeometry(QtCore.QRect(15, 237, 247, 8))
        self.card9Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card9Progress.setProperty("value", 30)
        self.card9Progress.setTextVisible(False)
        self.card9Progress.setObjectName("card9Progress")
        self.card9More = QtWidgets.QLabel(parent=self.card9)
        self.card9More.setGeometry(QtCore.QRect(16, 243, 80, 16))
        self.card9More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card9More.setObjectName("card9More")
        self.card10 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card10.setGeometry(QtCore.QRect(381, 512, 307, 257))
        self.card10.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card10.setObjectName("card10")
        self.card10Image = QtWidgets.QLabel(parent=self.card10)
        self.card10Image.setGeometry(QtCore.QRect(1, 1, 305, 128))
        self.card10Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card10Image.setPixmap(QtGui.QPixmap("TreEm-NguoiYeuThe\\campaign10.png"))
        self.card10Image.setScaledContents(True)
        self.card10Image.setObjectName("card10Image")
        self.card10Title = QtWidgets.QLabel(parent=self.card10)
        self.card10Title.setGeometry(QtCore.QRect(12, 138, 282, 42))
        self.card10Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card10Title.setWordWrap(True)
        self.card10Title.setObjectName("card10Title")
        self.card10Date = QtWidgets.QLabel(parent=self.card10)
        self.card10Date.setGeometry(QtCore.QRect(12, 177, 145, 16))
        self.card10Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card10Date.setObjectName("card10Date")
        self.card10Owner = QtWidgets.QLabel(parent=self.card10)
        self.card10Owner.setGeometry(QtCore.QRect(12, 193, 190, 16))
        self.card10Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card10Owner.setObjectName("card10Owner")
        self.card10Money = QtWidgets.QLabel(parent=self.card10)
        self.card10Money.setGeometry(QtCore.QRect(14, 215, 210, 20))
        self.card10Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card10Money.setObjectName("card10Money")
        self.card10Progress = QtWidgets.QProgressBar(parent=self.card10)
        self.card10Progress.setGeometry(QtCore.QRect(15, 237, 247, 8))
        self.card10Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card10Progress.setProperty("value", 30)
        self.card10Progress.setTextVisible(False)
        self.card10Progress.setObjectName("card10Progress")
        self.card10More = QtWidgets.QLabel(parent=self.card10)
        self.card10More.setGeometry(QtCore.QRect(16, 243, 80, 16))
        self.card10More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card10More.setObjectName("card10More")
        self.card11 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card11.setGeometry(QtCore.QRect(38, 811, 307, 257))
        self.card11.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card11.setObjectName("card11")
        self.card11Image = QtWidgets.QLabel(parent=self.card11)
        self.card11Image.setGeometry(QtCore.QRect(1, 1, 305, 128))
        self.card11Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card11Image.setPixmap(QtGui.QPixmap("TreEm-NguoiYeuThe\\campaign11.png"))
        self.card11Image.setScaledContents(True)
        self.card11Image.setObjectName("card11Image")
        self.card11Title = QtWidgets.QLabel(parent=self.card11)
        self.card11Title.setGeometry(QtCore.QRect(12, 138, 282, 42))
        self.card11Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card11Title.setWordWrap(True)
        self.card11Title.setObjectName("card11Title")
        self.card11Date = QtWidgets.QLabel(parent=self.card11)
        self.card11Date.setGeometry(QtCore.QRect(12, 177, 145, 16))
        self.card11Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card11Date.setObjectName("card11Date")
        self.card11Owner = QtWidgets.QLabel(parent=self.card11)
        self.card11Owner.setGeometry(QtCore.QRect(12, 193, 190, 16))
        self.card11Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card11Owner.setObjectName("card11Owner")
        self.card11Money = QtWidgets.QLabel(parent=self.card11)
        self.card11Money.setGeometry(QtCore.QRect(14, 215, 210, 20))
        self.card11Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card11Money.setObjectName("card11Money")
        self.card11Progress = QtWidgets.QProgressBar(parent=self.card11)
        self.card11Progress.setGeometry(QtCore.QRect(15, 237, 247, 8))
        self.card11Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card11Progress.setProperty("value", 30)
        self.card11Progress.setTextVisible(False)
        self.card11Progress.setObjectName("card11Progress")
        self.card11More = QtWidgets.QLabel(parent=self.card11)
        self.card11More.setGeometry(QtCore.QRect(16, 243, 80, 16))
        self.card11More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card11More.setObjectName("card11More")
        self.card12 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card12.setGeometry(QtCore.QRect(381, 811, 307, 257))
        self.card12.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card12.setObjectName("card12")
        self.card12Image = QtWidgets.QLabel(parent=self.card12)
        self.card12Image.setGeometry(QtCore.QRect(1, 1, 305, 128))
        self.card12Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card12Image.setPixmap(QtGui.QPixmap("TreEm-NguoiYeuThe\\campaign12.png"))
        self.card12Image.setScaledContents(True)
        self.card12Image.setObjectName("card12Image")
        self.card12Title = QtWidgets.QLabel(parent=self.card12)
        self.card12Title.setGeometry(QtCore.QRect(12, 138, 282, 42))
        self.card12Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card12Title.setWordWrap(True)
        self.card12Title.setObjectName("card12Title")
        self.card12Date = QtWidgets.QLabel(parent=self.card12)
        self.card12Date.setGeometry(QtCore.QRect(12, 177, 145, 16))
        self.card12Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card12Date.setObjectName("card12Date")
        self.card12Owner = QtWidgets.QLabel(parent=self.card12)
        self.card12Owner.setGeometry(QtCore.QRect(12, 193, 190, 16))
        self.card12Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card12Owner.setObjectName("card12Owner")
        self.card12Money = QtWidgets.QLabel(parent=self.card12)
        self.card12Money.setGeometry(QtCore.QRect(14, 215, 210, 20))
        self.card12Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card12Money.setObjectName("card12Money")
        self.card12Progress = QtWidgets.QProgressBar(parent=self.card12)
        self.card12Progress.setGeometry(QtCore.QRect(15, 237, 247, 8))
        self.card12Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card12Progress.setProperty("value", 30)
        self.card12Progress.setTextVisible(False)
        self.card12Progress.setObjectName("card12Progress")
        self.card12More = QtWidgets.QLabel(parent=self.card12)
        self.card12More.setGeometry(QtCore.QRect(16, 243, 80, 16))
        self.card12More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card12More.setObjectName("card12More")
        self.card13 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card13.setGeometry(QtCore.QRect(38, 1110, 307, 257))
        self.card13.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card13.setObjectName("card13")
        self.card13Image = QtWidgets.QLabel(parent=self.card13)
        self.card13Image.setGeometry(QtCore.QRect(1, 1, 305, 128))
        self.card13Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card13Image.setPixmap(QtGui.QPixmap("TreEm-NguoiYeuThe\\campaign13.png"))
        self.card13Image.setScaledContents(True)
        self.card13Image.setObjectName("card13Image")
        self.card13Title = QtWidgets.QLabel(parent=self.card13)
        self.card13Title.setGeometry(QtCore.QRect(12, 138, 282, 42))
        self.card13Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card13Title.setWordWrap(True)
        self.card13Title.setObjectName("card13Title")
        self.card13Date = QtWidgets.QLabel(parent=self.card13)
        self.card13Date.setGeometry(QtCore.QRect(12, 177, 145, 16))
        self.card13Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card13Date.setObjectName("card13Date")
        self.card13Owner = QtWidgets.QLabel(parent=self.card13)
        self.card13Owner.setGeometry(QtCore.QRect(12, 193, 180, 16))
        self.card13Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card13Owner.setObjectName("card13Owner")
        self.card13Money = QtWidgets.QLabel(parent=self.card13)
        self.card13Money.setGeometry(QtCore.QRect(14, 215, 210, 20))
        self.card13Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card13Money.setObjectName("card13Money")
        self.card13Progress = QtWidgets.QProgressBar(parent=self.card13)
        self.card13Progress.setGeometry(QtCore.QRect(15, 237, 247, 8))
        self.card13Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card13Progress.setProperty("value", 30)
        self.card13Progress.setTextVisible(False)
        self.card13Progress.setObjectName("card13Progress")
        self.card13More = QtWidgets.QLabel(parent=self.card13)
        self.card13More.setGeometry(QtCore.QRect(16, 243, 80, 16))
        self.card13More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card13More.setObjectName("card13More")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Trẻ em & Người yếu thế"))
        self.logoIcon.setText(_translate("MainWindow", "🕊"))
        self.logoTitle.setText(_translate("MainWindow", "Donarity"))
        self.logoSub.setText(_translate("MainWindow", "by group 10"))
        self.navHome.setText(_translate("MainWindow", "⌂ Trang chủ"))
        self.navStats.setText(_translate("MainWindow", "⌛ Thống kê"))
        self.navChatbot.setText(_translate("MainWindow", "◕ chatbot"))
        self.notifIcon.setText(_translate("MainWindow", "🔔"))
        self.notifBadge.setText(_translate("MainWindow", "0"))
        self.settingsIcon.setText(_translate("MainWindow", "⚙"))
        self.userIcon.setText(_translate("MainWindow", "◉"))
        self.backLabel.setText(_translate("MainWindow", "← Quay lại"))
        self.titleIcon.setText(_translate("MainWindow", "🧒"))
        self.mainTitle.setText(_translate("MainWindow", "Trẻ em & Người yếu thế"))
        self.searchEdit.setPlaceholderText(_translate("MainWindow", "Search for..."))
        self.searchIcon.setText(_translate("MainWindow", "⌕"))
        self.categoryCombo.setItemText(0, _translate("MainWindow", "All Categories"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.card7Title.setText(_translate("MainWindow", "Quỹ Trò nghèo vùng cao (Cơm có thịt)"))
        self.card7Date.setText(_translate("MainWindow", "Date:      2014-02-25"))
        self.card7Owner.setText(_translate("MainWindow", "Owner:   Trần Đăng Tuấn"))
        self.card7Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card7More.setText(_translate("MainWindow", "Xem thêm"))
        self.card8Title.setText(_translate("MainWindow", "Dự án Nuôi Em"))
        self.card8Date.setText(_translate("MainWindow", "Date:      2019-06-04"))
        self.card8Owner.setText(_translate("MainWindow", "Owner:   Hoàng Hoa Trung"))
        self.card8Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card8More.setText(_translate("MainWindow", "Xem thêm"))
        self.card9Title.setText(_translate("MainWindow", "Blue Dragon (Giải cứu trẻ em đường phố)"))
        self.card9Date.setText(_translate("MainWindow", "Date:      2003-06-02"))
        self.card9Owner.setText(_translate("MainWindow", "Owner:   Michael Brosowski"))
        self.card9Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card9More.setText(_translate("MainWindow", "Xem thêm"))
        self.card10Title.setText(_translate("MainWindow", "Mái ấm Thiên Ân (Dạy trẻ khiếm thị)"))
        self.card10Date.setText(_translate("MainWindow", "Date:      1994-07-15"))
        self.card10Owner.setText(_translate("MainWindow", "Owner:   Nguyễn Thị Kim Oanh"))
        self.card10Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card10More.setText(_translate("MainWindow", "Xem thêm"))
        self.card11Title.setText(_translate("MainWindow", "Save the Children (Bảo vệ trẻ em)"))
        self.card11Date.setText(_translate("MainWindow", "Date:      2022-02-14"))
        self.card11Owner.setText(_translate("MainWindow", "Owner:   Lê Thị Thanh Hương"))
        self.card11Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card11More.setText(_translate("MainWindow", "Xem thêm"))
        self.card12Title.setText(_translate("MainWindow", "Ngôi nhà bình yên (Bảo vệ phụ nữ)"))
        self.card12Date.setText(_translate("MainWindow", "Date:      2021-10-30"))
        self.card12Owner.setText(_translate("MainWindow", "Owner:   Dương Thị Ngọc Linh"))
        self.card12Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card12More.setText(_translate("MainWindow", "Xem thêm"))
        self.card13Title.setText(_translate("MainWindow", "Hỗ trợ can thiệp sớm cho trẻ tự kỷ"))
        self.card13Date.setText(_translate("MainWindow", "Date:      2022-04-02"))
        self.card13Owner.setText(_translate("MainWindow", "Owner:   Bạch Quốc Khánh"))
        self.card13Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card13More.setText(_translate("MainWindow", "Xem thêm"))
