# Form implementation generated from reading ui file 'Donate/xacminh4.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 900))
        MainWindow.setStyleSheet("QMainWindow, QWidget {\n"
"    background: #FFF3F9;\n"
"    font-family: \"Segoe UI\";\n"
"    color: #2F2A2E;\n"
"}\n"
"\n"
"QFrame#topBar {\n"
"    background: #F4D8E3;\n"
"    border: none;\n"
"}\n"
"\n"
"QLabel#logoIcon {\n"
"    color: #A64B80;\n"
"    font-size: 22px;\n"
"    font-weight: 700;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel#logoText {\n"
"    color: #9B4B78;\n"
"    font-size: 21px;\n"
"    font-weight: 800;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel#logoSub {\n"
"    color: #A78595;\n"
"    font-size: 11px;\n"
"    font-weight: 500;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QPushButton#navHome {\n"
"    background: #E7BDD0;\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    color: #1E1B20;\n"
"    font-size: 16px;\n"
"    font-weight: 700;\n"
"    padding-left: 14px;\n"
"    padding-right: 14px;\n"
"}\n"
"\n"
"QPushButton#navHome:hover {\n"
"    background: #E1B3C8;\n"
"}\n"
"\n"
"QPushButton#navStats,\n"
"QPushButton#navChat,\n"
"QPushButton#navPublic {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #1E1B20;\n"
"    font-size: 16px;\n"
"    font-weight: 700;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton#navStats:hover,\n"
"QPushButton#navChat:hover,\n"
"QPushButton#navPublic:hover {\n"
"    color: #9B4B78;\n"
"}\n"
"\n"
"QLabel#topBell,\n"
"QLabel#topSetting,\n"
"QLabel#topUser {\n"
"    background: transparent;\n"
"    color: #4A3D49;\n"
"    font-size: 22px;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"QPushButton#backBtn {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #1E1B20;\n"
"    font-size: 18px;\n"
"    font-weight: 700;\n"
"    text-align: left;\n"
"}\n"
"\n"
"QFrame#mainCard, QFrame#donateCard {\n"
"    background: #FFF3F9;\n"
"    border: 4px solid #EDB4CB;\n"
"    border-radius: 24px;\n"
"}\n"
"\n"
"QLabel#campaignTitle {\n"
"    color: #764872;\n"
"    font-size: 24px;\n"
"    font-weight: 900;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel#campaignDesc {\n"
"    color: #1E1B20;\n"
"    font-size: 16px;\n"
"    font-weight: 500;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel#amountLabel, QLabel#percentLabel {\n"
"    color: #764872;\n"
"    font-size: 22px;\n"
"    font-weight: 900;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QFrame#progressBg {\n"
"    background: #E8D2DD;\n"
"    border: none;\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"QFrame#progressFill {\n"
"    background: #E39BC8;\n"
"    border: none;\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"QFrame#lineUnderProgress, QFrame#verticalLine {\n"
"    background: #EDB4CB;\n"
"    border: none;\n"
"}\n"
"\n"
"QLabel#activitiesTitle,\n"
"QLabel#scopeTitle,\n"
"QLabel#dateTitle,\n"
"QLabel#ownerTitle {\n"
"    color: #1E1B20;\n"
"    font-size: 18px;\n"
"    font-weight: 900;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel#activitiesText,\n"
"QLabel#scopeText,\n"
"QLabel#dateText,\n"
"QLabel#idLabel,\n"
"QLabel#genderLabel,\n"
"QLabel#nameLabel,\n"
"QLabel#phoneLabel,\n"
"QLabel#cccdLabel,\n"
"QLabel#addressLabel,\n"
"QLabel#emailLabel,\n"
"QLabel#idValue,\n"
"QLabel#genderValue,\n"
"QLabel#nameValue,\n"
"QLabel#phoneValue,\n"
"QLabel#cccdValue,\n"
"QLabel#addressValue,\n"
"QLabel#emailValue {\n"
"    color: #1E1B20;\n"
"    font-size: 15px;\n"
"    font-weight: 500;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel#avatarLabel {\n"
"    background: #F2F2F2;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QLabel#donateTitle {\n"
"    color: #764872;\n"
"    font-size: 24px;\n"
"    font-weight: 900;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel#maGiaoDichLabel {\n"
"    color: #1E1B20;\n"
"    font-size: 16px;\n"
"    font-weight: 500;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLineEdit#codeEdit {\n"
"    background: #FFFFFF;\n"
"    border: 2px solid #A78397;\n"
"    border-radius: 22px;\n"
"    padding-left: 18px;\n"
"    padding-right: 18px;\n"
"    color: #5B5660;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton#sendBtn {\n"
"    background: #E39BC8;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    color: #7A456B;\n"
"    font-size: 16px;\n"
"    font-weight: 800;\n"
"}\n"
"\n"
"QPushButton#sendBtn:hover {\n"
"    background: #D98CBD;\n"
"}\n"
"\n"
"QLabel#qrLabel {\n"
"    background: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.topBar = QtWidgets.QFrame(parent=self.centralwidget)
        self.topBar.setGeometry(QtCore.QRect(25, 10, 1150, 56))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.topBar.setFont(font)
        self.topBar.setObjectName("topBar")
        self.logoIcon = QtWidgets.QLabel(parent=self.topBar)
        self.logoIcon.setGeometry(QtCore.QRect(18, 9, 30, 34))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.logoIcon.setFont(font)
        self.logoIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoIcon.setObjectName("logoIcon")
        self.logoText = QtWidgets.QLabel(parent=self.topBar)
        self.logoText.setGeometry(QtCore.QRect(55, 10, 112, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(99)
        self.logoText.setFont(font)
        self.logoText.setObjectName("logoText")
        self.logoSub = QtWidgets.QLabel(parent=self.topBar)
        self.logoSub.setGeometry(QtCore.QRect(166, 18, 78, 18))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.logoSub.setFont(font)
        self.logoSub.setObjectName("logoSub")
        self.navHome = QtWidgets.QPushButton(parent=self.topBar)
        self.navHome.setGeometry(QtCore.QRect(288, 8, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.navHome.setFont(font)
        self.navHome.setObjectName("navHome")
        self.navStats = QtWidgets.QPushButton(parent=self.topBar)
        self.navStats.setGeometry(QtCore.QRect(492, 9, 126, 38))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.navStats.setFont(font)
        self.navStats.setObjectName("navStats")
        self.navChat = QtWidgets.QPushButton(parent=self.topBar)
        self.navChat.setGeometry(QtCore.QRect(642, 9, 132, 38))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.navChat.setFont(font)
        self.navChat.setObjectName("navChat")
        self.navPublic = QtWidgets.QPushButton(parent=self.topBar)
        self.navPublic.setGeometry(QtCore.QRect(788, 9, 145, 38))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.navPublic.setFont(font)
        self.navPublic.setObjectName("navPublic")
        self.topBell = QtWidgets.QLabel(parent=self.topBar)
        self.topBell.setGeometry(QtCore.QRect(997, 8, 34, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.topBell.setFont(font)
        self.topBell.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.topBell.setObjectName("topBell")
        self.topSetting = QtWidgets.QLabel(parent=self.topBar)
        self.topSetting.setGeometry(QtCore.QRect(1046, 8, 34, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.topSetting.setFont(font)
        self.topSetting.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.topSetting.setObjectName("topSetting")
        self.topUser = QtWidgets.QLabel(parent=self.topBar)
        self.topUser.setGeometry(QtCore.QRect(1098, 7, 36, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.topUser.setFont(font)
        self.topUser.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.topUser.setObjectName("topUser")
        self.backBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.backBtn.setGeometry(QtCore.QRect(30, 70, 140, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.backBtn.setFont(font)
        self.backBtn.setObjectName("backBtn")
        self.mainCard = QtWidgets.QFrame(parent=self.centralwidget)
        self.mainCard.setGeometry(QtCore.QRect(25, 110, 1150, 431))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.mainCard.setFont(font)
        self.mainCard.setObjectName("mainCard")
        self.campaignTitle = QtWidgets.QLabel(parent=self.mainCard)
        self.campaignTitle.setGeometry(QtCore.QRect(24, 10, 900, 42))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(99)
        self.campaignTitle.setFont(font)
        self.campaignTitle.setWordWrap(True)
        self.campaignTitle.setObjectName("campaignTitle")
        self.campaignDesc = QtWidgets.QLabel(parent=self.mainCard)
        self.campaignDesc.setGeometry(QtCore.QRect(24, 50, 1098, 44))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.campaignDesc.setFont(font)
        self.campaignDesc.setWordWrap(True)
        self.campaignDesc.setObjectName("campaignDesc")
        self.amountLabel = QtWidgets.QLabel(parent=self.mainCard)
        self.amountLabel.setGeometry(QtCore.QRect(54, 100, 420, 38))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(99)
        self.amountLabel.setFont(font)
        self.amountLabel.setObjectName("amountLabel")
        self.percentLabel = QtWidgets.QLabel(parent=self.mainCard)
        self.percentLabel.setGeometry(QtCore.QRect(1040, 100, 80, 38))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(99)
        self.percentLabel.setFont(font)
        self.percentLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.percentLabel.setObjectName("percentLabel")
        self.progressBg = QtWidgets.QFrame(parent=self.mainCard)
        self.progressBg.setGeometry(QtCore.QRect(35, 140, 1085, 32))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.progressBg.setFont(font)
        self.progressBg.setObjectName("progressBg")
        self.progressFill = QtWidgets.QFrame(parent=self.progressBg)
        self.progressFill.setGeometry(QtCore.QRect(0, 0, 145, 32))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.progressFill.setFont(font)
        self.progressFill.setObjectName("progressFill")
        self.lineUnderProgress = QtWidgets.QFrame(parent=self.mainCard)
        self.lineUnderProgress.setGeometry(QtCore.QRect(30, 190, 1102, 5))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.lineUnderProgress.setFont(font)
        self.lineUnderProgress.setObjectName("lineUnderProgress")
        self.activitiesTitle = QtWidgets.QLabel(parent=self.mainCard)
        self.activitiesTitle.setGeometry(QtCore.QRect(24, 200, 130, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(99)
        self.activitiesTitle.setFont(font)
        self.activitiesTitle.setObjectName("activitiesTitle")
        self.activitiesText = QtWidgets.QLabel(parent=self.mainCard)
        self.activitiesText.setGeometry(QtCore.QRect(24, 230, 420, 66))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.activitiesText.setFont(font)
        self.activitiesText.setWordWrap(True)
        self.activitiesText.setObjectName("activitiesText")
        self.scopeTitle = QtWidgets.QLabel(parent=self.mainCard)
        self.scopeTitle.setGeometry(QtCore.QRect(24, 300, 100, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(99)
        self.scopeTitle.setFont(font)
        self.scopeTitle.setObjectName("scopeTitle")
        self.scopeText = QtWidgets.QLabel(parent=self.mainCard)
        self.scopeText.setGeometry(QtCore.QRect(30, 330, 180, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.scopeText.setFont(font)
        self.scopeText.setObjectName("scopeText")
        self.dateTitle = QtWidgets.QLabel(parent=self.mainCard)
        self.dateTitle.setGeometry(QtCore.QRect(24, 350, 145, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(99)
        self.dateTitle.setFont(font)
        self.dateTitle.setObjectName("dateTitle")
        self.dateText = QtWidgets.QLabel(parent=self.mainCard)
        self.dateText.setGeometry(QtCore.QRect(30, 380, 160, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.dateText.setFont(font)
        self.dateText.setObjectName("dateText")
        self.verticalLine = QtWidgets.QFrame(parent=self.mainCard)
        self.verticalLine.setGeometry(QtCore.QRect(480, 220, 4, 170))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.verticalLine.setFont(font)
        self.verticalLine.setObjectName("verticalLine")
        self.ownerTitle = QtWidgets.QLabel(parent=self.mainCard)
        self.ownerTitle.setGeometry(QtCore.QRect(505, 210, 170, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(99)
        self.ownerTitle.setFont(font)
        self.ownerTitle.setObjectName("ownerTitle")
        self.idLabel = QtWidgets.QLabel(parent=self.mainCard)
        self.idLabel.setGeometry(QtCore.QRect(505, 240, 90, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.idLabel.setFont(font)
        self.idLabel.setObjectName("idLabel")
        self.idValue = QtWidgets.QLabel(parent=self.mainCard)
        self.idValue.setGeometry(QtCore.QRect(635, 240, 120, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.idValue.setFont(font)
        self.idValue.setObjectName("idValue")
        self.genderLabel = QtWidgets.QLabel(parent=self.mainCard)
        self.genderLabel.setGeometry(QtCore.QRect(760, 250, 80, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.genderLabel.setFont(font)
        self.genderLabel.setObjectName("genderLabel")
        self.genderValue = QtWidgets.QLabel(parent=self.mainCard)
        self.genderValue.setGeometry(QtCore.QRect(850, 250, 46, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.genderValue.setFont(font)
        self.genderValue.setObjectName("genderValue")
        self.nameLabel = QtWidgets.QLabel(parent=self.mainCard)
        self.nameLabel.setGeometry(QtCore.QRect(505, 270, 100, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.nameValue = QtWidgets.QLabel(parent=self.mainCard)
        self.nameValue.setGeometry(QtCore.QRect(635, 270, 200, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.nameValue.setFont(font)
        self.nameValue.setObjectName("nameValue")
        self.phoneLabel = QtWidgets.QLabel(parent=self.mainCard)
        self.phoneLabel.setGeometry(QtCore.QRect(505, 300, 110, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.phoneLabel.setFont(font)
        self.phoneLabel.setObjectName("phoneLabel")
        self.phoneValue = QtWidgets.QLabel(parent=self.mainCard)
        self.phoneValue.setGeometry(QtCore.QRect(635, 300, 130, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.phoneValue.setFont(font)
        self.phoneValue.setObjectName("phoneValue")
        self.cccdLabel = QtWidgets.QLabel(parent=self.mainCard)
        self.cccdLabel.setGeometry(QtCore.QRect(505, 330, 95, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.cccdLabel.setFont(font)
        self.cccdLabel.setObjectName("cccdLabel")
        self.cccdValue = QtWidgets.QLabel(parent=self.mainCard)
        self.cccdValue.setGeometry(QtCore.QRect(635, 330, 170, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.cccdValue.setFont(font)
        self.cccdValue.setObjectName("cccdValue")
        self.addressLabel = QtWidgets.QLabel(parent=self.mainCard)
        self.addressLabel.setGeometry(QtCore.QRect(505, 360, 80, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.addressLabel.setFont(font)
        self.addressLabel.setObjectName("addressLabel")
        self.addressValue = QtWidgets.QLabel(parent=self.mainCard)
        self.addressValue.setGeometry(QtCore.QRect(635, 360, 150, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.addressValue.setFont(font)
        self.addressValue.setObjectName("addressValue")
        self.emailLabel = QtWidgets.QLabel(parent=self.mainCard)
        self.emailLabel.setGeometry(QtCore.QRect(510, 390, 54, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.emailLabel.setFont(font)
        self.emailLabel.setObjectName("emailLabel")
        self.emailValue = QtWidgets.QLabel(parent=self.mainCard)
        self.emailValue.setGeometry(QtCore.QRect(630, 380, 180, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.emailValue.setFont(font)
        self.emailValue.setWordWrap(True)
        self.emailValue.setObjectName("emailValue")
        self.avatarLabel = QtWidgets.QLabel(parent=self.mainCard)
        self.avatarLabel.setGeometry(QtCore.QRect(969, 229, 151, 171))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.avatarLabel.setFont(font)
        self.avatarLabel.setText("")
        self.avatarLabel.setPixmap(QtGui.QPixmap("Donate\\avt4.png"))
        self.avatarLabel.setScaledContents(True)
        self.avatarLabel.setObjectName("avatarLabel")
        self.donateCard = QtWidgets.QFrame(parent=self.centralwidget)
        self.donateCard.setGeometry(QtCore.QRect(25, 550, 470, 161))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.donateCard.setFont(font)
        self.donateCard.setObjectName("donateCard")
        self.donateTitle = QtWidgets.QLabel(parent=self.donateCard)
        self.donateTitle.setGeometry(QtCore.QRect(140, 10, 190, 42))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(99)
        self.donateTitle.setFont(font)
        self.donateTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.donateTitle.setObjectName("donateTitle")
        self.verifyIcon = QtWidgets.QLabel(parent=self.donateCard)
        self.verifyIcon.setGeometry(QtCore.QRect(78, 80, 60, 60))
        self.verifyIcon.setText("")
        self.verifyIcon.setPixmap(QtGui.QPixmap("Donate\\hourglass.png"))
        self.verifyIcon.setScaledContents(True)
        self.verifyIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.verifyIcon.setObjectName("verifyIcon")
        self.navStats_2 = QtWidgets.QPushButton(parent=self.donateCard)
        self.navStats_2.setGeometry(QtCore.QRect(80, 60, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.navStats_2.setFont(font)
        self.navStats_2.setObjectName("navStats_2")
        self.dateTitle_2 = QtWidgets.QLabel(parent=self.donateCard)
        self.dateTitle_2.setGeometry(QtCore.QRect(210, 70, 221, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dateTitle_2.setFont(font)
        self.dateTitle_2.setObjectName("dateTitle_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Donarity - Theo dõi chiến dịch"))
        self.logoIcon.setText(_translate("MainWindow", "🕊"))
        self.logoText.setText(_translate("MainWindow", "Donarity"))
        self.logoSub.setText(_translate("MainWindow", "by group 10"))
        self.navHome.setText(_translate("MainWindow", "🏠  Trang chủ"))
        self.navStats.setText(_translate("MainWindow", "⏳  Thống kê"))
        self.navChat.setText(_translate("MainWindow", "🗨  Chatbot"))
        self.navPublic.setText(_translate("MainWindow", "👁  Công khai"))
        self.topBell.setText(_translate("MainWindow", "🔔"))
        self.topSetting.setText(_translate("MainWindow", "⚙"))
        self.topUser.setText(_translate("MainWindow", "👤"))
        self.backBtn.setText(_translate("MainWindow", "← Quay lại"))
        self.campaignTitle.setText(_translate("MainWindow", "Chiến dịch Hiến máu nhân đạo Quốc gia"))
        self.campaignDesc.setText(_translate("MainWindow", "Vận động cộng đồng tham gia hiến máu tình nguyện để cứu người, đảm bảo nguồn máu dự trữ cho các bệnh viện."))
        self.amountLabel.setText(_translate("MainWindow", "1000000000/10000000000"))
        self.percentLabel.setText(_translate("MainWindow", "6.67%"))
        self.activitiesTitle.setText(_translate("MainWindow", "Hoạt động:"))
        self.activitiesText.setText(_translate("MainWindow", "Tổ chức ngày hội hiến máu (Lễ hội Xuân Hồng)\n"
"Tuyên truyền và vận động hiến máu\n"
"Quản lý và hỗ trợ người hiến máu tình nguyện"))
        self.scopeTitle.setText(_translate("MainWindow", "Phạm vi:"))
        self.scopeText.setText(_translate("MainWindow", "Toàn quốc"))
        self.dateTitle.setText(_translate("MainWindow", "Ngày thành lập:"))
        self.dateText.setText(_translate("MainWindow", "2018-11-12"))
        self.ownerTitle.setText(_translate("MainWindow", "Chủ chiến dịch:"))
        self.idLabel.setText(_translate("MainWindow", "ID:"))
        self.idValue.setText(_translate("MainWindow", "CC0008"))
        self.genderLabel.setText(_translate("MainWindow", "Giới tính:"))
        self.genderValue.setText(_translate("MainWindow", "Nam"))
        self.nameLabel.setText(_translate("MainWindow", "Họ và tên:"))
        self.nameValue.setText(_translate("MainWindow", "Bạch Quốc Khánh"))
        self.phoneLabel.setText(_translate("MainWindow", "Số điện thoại:"))
        self.phoneValue.setText(_translate("MainWindow", "0944000111"))
        self.cccdLabel.setText(_translate("MainWindow", "Số CCCD:"))
        self.cccdValue.setText(_translate("MainWindow", "001065003333"))
        self.addressLabel.setText(_translate("MainWindow", "Địa chỉ:"))
        self.addressValue.setText(_translate("MainWindow", "Hà Nội"))
        self.emailLabel.setText(_translate("MainWindow", "Email:"))
        self.emailValue.setText(_translate("MainWindow", "khanhbq@nihbt.org.vn"))
        self.donateTitle.setText(_translate("MainWindow", "Quyên góp"))
        self.navStats_2.setText(_translate("MainWindow", "⏳  "))
        self.dateTitle_2.setText(_translate("MainWindow", "Đang xác minh..."))
