# Form implementation generated from reading ui file 'Yte-SucKhoe/yte_suckhoe.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(752, 1228)
        MainWindow.setMinimumSize(QtCore.QSize(752, 1228))
        MainWindow.setStyleSheet("QMainWindow, QWidget {\n"
"    background: #FFF6FB;\n"
"    font-family: \"Arial\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1200, 1228))
        self.scrollArea.setMinimumSize(QtCore.QSize(1200, 760))
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    border: none;\n"
"    background: #FFF6FB;\n"
"}\n"
"QScrollBar:vertical {\n"
"    background: #F8E8F0;\n"
"    width: 12px;\n"
"    border-radius: 6px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #D9AFC7;\n"
"    min-height: 40px;\n"
"    border-radius: 6px;\n"
"}\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: transparent;\n"
"}")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 752, 1550))
        self.scrollAreaWidgetContents.setStyleSheet("background: #FFF6FB;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.topBar = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.topBar.setGeometry(QtCore.QRect(0, 0, 752, 40))
        self.topBar.setStyleSheet("QFrame{\n"
"    background:#F9DDE7;\n"
"    border:none;\n"
"    border-radius:0px;\n"
"}")
        self.topBar.setObjectName("topBar")
        self.logoIcon = QtWidgets.QLabel(parent=self.topBar)
        self.logoIcon.setGeometry(QtCore.QRect(26, 5, 26, 26))
        self.logoIcon.setStyleSheet("QLabel{\n"
"    font-size:18px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.logoIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoIcon.setObjectName("logoIcon")
        self.logoTitle = QtWidgets.QLabel(parent=self.topBar)
        self.logoTitle.setGeometry(QtCore.QRect(50, 3, 92, 20))
        self.logoTitle.setStyleSheet("QLabel{\n"
"    color:#7E3A79;\n"
"    font-size:14px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.logoTitle.setObjectName("logoTitle")
        self.logoSub = QtWidgets.QLabel(parent=self.topBar)
        self.logoSub.setGeometry(QtCore.QRect(52, 20, 62, 12))
        self.logoSub.setStyleSheet("QLabel{\n"
"    color:#7A6D75;\n"
"    font-size:7px;\n"
"    font-weight:600;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.logoSub.setObjectName("logoSub")
        self.navHome = QtWidgets.QLabel(parent=self.topBar)
        self.navHome.setGeometry(QtCore.QRect(200, 9, 90, 18))
        self.navHome.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:10px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.navHome.setObjectName("navHome")
        self.navStats = QtWidgets.QLabel(parent=self.topBar)
        self.navStats.setGeometry(QtCore.QRect(292, 9, 92, 18))
        self.navStats.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:10px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.navStats.setObjectName("navStats")
        self.navChatbot = QtWidgets.QLabel(parent=self.topBar)
        self.navChatbot.setGeometry(QtCore.QRect(384, 9, 90, 18))
        self.navChatbot.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:10px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.navChatbot.setObjectName("navChatbot")
        self.notifIcon = QtWidgets.QLabel(parent=self.topBar)
        self.notifIcon.setGeometry(QtCore.QRect(672, 8, 18, 18))
        self.notifIcon.setStyleSheet("QLabel{\n"
"    font-size:13px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.notifIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.notifIcon.setObjectName("notifIcon")
        self.notifBadge = QtWidgets.QLabel(parent=self.topBar)
        self.notifBadge.setGeometry(QtCore.QRect(684, 6, 12, 12))
        self.notifBadge.setStyleSheet("QLabel{\n"
"    background:#E53935;\n"
"    color:white;\n"
"    border-radius:6px;\n"
"    font-size:7px;\n"
"    font-weight:800;\n"
"}")
        self.notifBadge.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.notifBadge.setObjectName("notifBadge")
        self.settingsIcon = QtWidgets.QLabel(parent=self.topBar)
        self.settingsIcon.setGeometry(QtCore.QRect(703, 8, 16, 18))
        self.settingsIcon.setStyleSheet("QLabel{\n"
"    font-size:13px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.settingsIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.settingsIcon.setObjectName("settingsIcon")
        self.userIcon = QtWidgets.QLabel(parent=self.topBar)
        self.userIcon.setGeometry(QtCore.QRect(726, 6, 20, 22))
        self.userIcon.setStyleSheet("QLabel{\n"
"    color:#2A2A2A;\n"
"    font-size:18px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.userIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.userIcon.setObjectName("userIcon")
        self.backLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.backLabel.setGeometry(QtCore.QRect(8, 50, 100, 18))
        self.backLabel.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:10px;\n"
"    font-weight:600;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.backLabel.setObjectName("backLabel")
        self.titleIcon = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.titleIcon.setGeometry(QtCore.QRect(28, 84, 42, 42))
        self.titleIcon.setStyleSheet("QLabel{\n"
"    font-size:28px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.titleIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleIcon.setObjectName("titleIcon")
        self.mainTitle = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.mainTitle.setGeometry(QtCore.QRect(78, 80, 320, 46))
        self.mainTitle.setStyleSheet("QLabel{\n"
"    color:#7F4D7D;\n"
"    font-size:28px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.mainTitle.setObjectName("mainTitle")
        self.searchEdit = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.searchEdit.setGeometry(QtCore.QRect(22, 144, 496, 32))
        self.searchEdit.setStyleSheet("QLineEdit{\n"
"    background:white;\n"
"    border:1px solid #CFCFCF;\n"
"    padding-left:30px;\n"
"    color:#222;\n"
"    font-size:10px;\n"
"}")
        self.searchEdit.setObjectName("searchEdit")
        self.searchIcon = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.searchIcon.setGeometry(QtCore.QRect(33, 151, 16, 16))
        self.searchIcon.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:13px;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.searchIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.searchIcon.setObjectName("searchIcon")
        self.categoryCombo = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.categoryCombo.setGeometry(QtCore.QRect(518, 144, 112, 32))
        self.categoryCombo.setStyleSheet("QComboBox{\n"
"    background:white;\n"
"    border:1px solid #CFCFCF;\n"
"    padding-left:8px;\n"
"    color:#222;\n"
"    font-size:10px;\n"
"}")
        self.categoryCombo.setObjectName("categoryCombo")
        self.categoryCombo.addItem("")
        self.searchButton = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.searchButton.setGeometry(QtCore.QRect(645, 144, 68, 32))
        self.searchButton.setStyleSheet("QPushButton{\n"
"    background:#FFF6FB;\n"
"    border:1px solid #7F4D7D;\n"
"    color:#222;\n"
"    font-size:10px;\n"
"    font-weight:700;\n"
"}")
        self.searchButton.setObjectName("searchButton")
        self.card1 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card1.setGeometry(QtCore.QRect(53, 219, 307, 261))
        self.card1.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card1.setObjectName("card1")
        self.card1Image = QtWidgets.QLabel(parent=self.card1)
        self.card1Image.setGeometry(QtCore.QRect(0, 0, 311, 131))
        self.card1Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card1Image.setPixmap(QtGui.QPixmap("Yte-SucKhoe\\campaign1.png"))
        self.card1Image.setScaledContents(True)
        self.card1Image.setObjectName("card1Image")
        self.card1Title = QtWidgets.QLabel(parent=self.card1)
        self.card1Title.setGeometry(QtCore.QRect(8, 138, 289, 42))
        self.card1Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card1Title.setWordWrap(True)
        self.card1Title.setObjectName("card1Title")
        self.card1Date = QtWidgets.QLabel(parent=self.card1)
        self.card1Date.setGeometry(QtCore.QRect(12, 178, 150, 16))
        self.card1Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card1Date.setObjectName("card1Date")
        self.card1Owner = QtWidgets.QLabel(parent=self.card1)
        self.card1Owner.setGeometry(QtCore.QRect(12, 194, 160, 16))
        self.card1Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card1Owner.setObjectName("card1Owner")
        self.card1Money = QtWidgets.QLabel(parent=self.card1)
        self.card1Money.setGeometry(QtCore.QRect(14, 214, 210, 20))
        self.card1Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card1Money.setObjectName("card1Money")
        self.card1Progress = QtWidgets.QProgressBar(parent=self.card1)
        self.card1Progress.setGeometry(QtCore.QRect(15, 235, 250, 8))
        self.card1Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card1Progress.setProperty("value", 30)
        self.card1Progress.setTextVisible(False)
        self.card1Progress.setObjectName("card1Progress")
        self.card1More = QtWidgets.QLabel(parent=self.card1)
        self.card1More.setGeometry(QtCore.QRect(15, 243, 80, 16))
        self.card1More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card1More.setObjectName("card1More")
        self.card2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card2.setGeometry(QtCore.QRect(396, 221, 307, 261))
        self.card2.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card2.setObjectName("card2")
        self.card2Image = QtWidgets.QLabel(parent=self.card2)
        self.card2Image.setGeometry(QtCore.QRect(1, 1, 305, 128))
        self.card2Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card2Image.setPixmap(QtGui.QPixmap("Yte-SucKhoe\\campaign2.png"))
        self.card2Image.setScaledContents(True)
        self.card2Image.setObjectName("card2Image")
        self.card2Title = QtWidgets.QLabel(parent=self.card2)
        self.card2Title.setGeometry(QtCore.QRect(8, 136, 290, 48))
        self.card2Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card2Title.setWordWrap(True)
        self.card2Title.setObjectName("card2Title")
        self.card2Date = QtWidgets.QLabel(parent=self.card2)
        self.card2Date.setGeometry(QtCore.QRect(12, 178, 150, 16))
        self.card2Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card2Date.setObjectName("card2Date")
        self.card2Owner = QtWidgets.QLabel(parent=self.card2)
        self.card2Owner.setGeometry(QtCore.QRect(12, 194, 190, 16))
        self.card2Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card2Owner.setObjectName("card2Owner")
        self.card2Money = QtWidgets.QLabel(parent=self.card2)
        self.card2Money.setGeometry(QtCore.QRect(14, 214, 210, 20))
        self.card2Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card2Money.setObjectName("card2Money")
        self.card2Progress = QtWidgets.QProgressBar(parent=self.card2)
        self.card2Progress.setGeometry(QtCore.QRect(15, 235, 250, 8))
        self.card2Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card2Progress.setProperty("value", 30)
        self.card2Progress.setTextVisible(False)
        self.card2Progress.setObjectName("card2Progress")
        self.card2More = QtWidgets.QLabel(parent=self.card2)
        self.card2More.setGeometry(QtCore.QRect(15, 243, 80, 16))
        self.card2More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card2More.setObjectName("card2More")
        self.card3 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card3.setGeometry(QtCore.QRect(48, 523, 307, 261))
        self.card3.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card3.setObjectName("card3")
        self.card3Image = QtWidgets.QLabel(parent=self.card3)
        self.card3Image.setGeometry(QtCore.QRect(1, 1, 305, 128))
        self.card3Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card3Image.setPixmap(QtGui.QPixmap("Yte-SucKhoe\\campaign3.png"))
        self.card3Image.setScaledContents(True)
        self.card3Image.setObjectName("card3Image")
        self.card3Title = QtWidgets.QLabel(parent=self.card3)
        self.card3Title.setGeometry(QtCore.QRect(8, 136, 311, 48))
        self.card3Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card3Title.setWordWrap(True)
        self.card3Title.setObjectName("card3Title")
        self.card3Date = QtWidgets.QLabel(parent=self.card3)
        self.card3Date.setGeometry(QtCore.QRect(12, 178, 150, 16))
        self.card3Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card3Date.setObjectName("card3Date")
        self.card3Owner = QtWidgets.QLabel(parent=self.card3)
        self.card3Owner.setGeometry(QtCore.QRect(12, 194, 190, 16))
        self.card3Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card3Owner.setObjectName("card3Owner")
        self.card3Money = QtWidgets.QLabel(parent=self.card3)
        self.card3Money.setGeometry(QtCore.QRect(14, 214, 210, 20))
        self.card3Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card3Money.setObjectName("card3Money")
        self.card3Progress = QtWidgets.QProgressBar(parent=self.card3)
        self.card3Progress.setGeometry(QtCore.QRect(15, 235, 250, 8))
        self.card3Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card3Progress.setProperty("value", 30)
        self.card3Progress.setTextVisible(False)
        self.card3Progress.setObjectName("card3Progress")
        self.card3More = QtWidgets.QLabel(parent=self.card3)
        self.card3More.setGeometry(QtCore.QRect(15, 243, 80, 16))
        self.card3More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card3More.setObjectName("card3More")
        self.card4 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card4.setGeometry(QtCore.QRect(396, 523, 307, 261))
        self.card4.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card4.setObjectName("card4")
        self.card4Image = QtWidgets.QLabel(parent=self.card4)
        self.card4Image.setGeometry(QtCore.QRect(1, 1, 305, 128))
        self.card4Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card4Image.setPixmap(QtGui.QPixmap("Yte-SucKhoe\\campaign4.png"))
        self.card4Image.setScaledContents(True)
        self.card4Image.setObjectName("card4Image")
        self.card4Title = QtWidgets.QLabel(parent=self.card4)
        self.card4Title.setGeometry(QtCore.QRect(8, 136, 290, 48))
        self.card4Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card4Title.setWordWrap(True)
        self.card4Title.setObjectName("card4Title")
        self.card4Date = QtWidgets.QLabel(parent=self.card4)
        self.card4Date.setGeometry(QtCore.QRect(12, 178, 150, 16))
        self.card4Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card4Date.setObjectName("card4Date")
        self.card4Owner = QtWidgets.QLabel(parent=self.card4)
        self.card4Owner.setGeometry(QtCore.QRect(12, 194, 170, 16))
        self.card4Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card4Owner.setObjectName("card4Owner")
        self.card4Money = QtWidgets.QLabel(parent=self.card4)
        self.card4Money.setGeometry(QtCore.QRect(14, 214, 210, 20))
        self.card4Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card4Money.setObjectName("card4Money")
        self.card4Progress = QtWidgets.QProgressBar(parent=self.card4)
        self.card4Progress.setGeometry(QtCore.QRect(15, 235, 250, 8))
        self.card4Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card4Progress.setProperty("value", 30)
        self.card4Progress.setTextVisible(False)
        self.card4Progress.setObjectName("card4Progress")
        self.card4More = QtWidgets.QLabel(parent=self.card4)
        self.card4More.setGeometry(QtCore.QRect(15, 243, 80, 16))
        self.card4More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card4More.setObjectName("card4More")
        self.card5 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card5.setGeometry(QtCore.QRect(45, 821, 307, 261))
        self.card5.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card5.setObjectName("card5")
        self.card5Image = QtWidgets.QLabel(parent=self.card5)
        self.card5Image.setGeometry(QtCore.QRect(1, 1, 305, 128))
        self.card5Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card5Image.setPixmap(QtGui.QPixmap("Yte-SucKhoe\\campaign5.png"))
        self.card5Image.setScaledContents(True)
        self.card5Image.setObjectName("card5Image")
        self.card5Title = QtWidgets.QLabel(parent=self.card5)
        self.card5Title.setGeometry(QtCore.QRect(8, 136, 290, 48))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(99)
        self.card5Title.setFont(font)
        self.card5Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card5Title.setWordWrap(True)
        self.card5Title.setObjectName("card5Title")
        self.card5Date = QtWidgets.QLabel(parent=self.card5)
        self.card5Date.setGeometry(QtCore.QRect(12, 178, 150, 16))
        self.card5Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card5Date.setObjectName("card5Date")
        self.card5Owner = QtWidgets.QLabel(parent=self.card5)
        self.card5Owner.setGeometry(QtCore.QRect(12, 194, 180, 16))
        self.card5Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card5Owner.setObjectName("card5Owner")
        self.card5Money = QtWidgets.QLabel(parent=self.card5)
        self.card5Money.setGeometry(QtCore.QRect(14, 214, 210, 20))
        self.card5Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card5Money.setObjectName("card5Money")
        self.card5Progress = QtWidgets.QProgressBar(parent=self.card5)
        self.card5Progress.setGeometry(QtCore.QRect(15, 235, 250, 8))
        self.card5Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card5Progress.setProperty("value", 30)
        self.card5Progress.setTextVisible(False)
        self.card5Progress.setObjectName("card5Progress")
        self.card5More = QtWidgets.QLabel(parent=self.card5)
        self.card5More.setGeometry(QtCore.QRect(15, 243, 80, 16))
        self.card5More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card5More.setObjectName("card5More")
        self.card6 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.card6.setGeometry(QtCore.QRect(391, 821, 307, 261))
        self.card6.setStyleSheet("QFrame{\n"
"    background:#FFF9FC;\n"
"    border:1px solid #D0A8BD;\n"
"    border-radius:20px;\n"
"}")
        self.card6.setObjectName("card6")
        self.card6Image = QtWidgets.QLabel(parent=self.card6)
        self.card6Image.setGeometry(QtCore.QRect(1, 1, 305, 128))
        self.card6Image.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    border-top-left-radius:19px;\n"
"    border-top-right-radius:19px;\n"
"    background:#E7E7E7;\n"
"}")
        self.card6Image.setPixmap(QtGui.QPixmap("Yte-SucKhoe\\campaign6.png"))
        self.card6Image.setScaledContents(True)
        self.card6Image.setObjectName("card6Image")
        self.card6Title = QtWidgets.QLabel(parent=self.card6)
        self.card6Title.setGeometry(QtCore.QRect(8, 136, 290, 48))
        self.card6Title.setStyleSheet("QLabel{\n"
"    color:#78496F;\n"
"    font-size:11px;\n"
"    font-weight:800;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card6Title.setWordWrap(True)
        self.card6Title.setObjectName("card6Title")
        self.card6Date = QtWidgets.QLabel(parent=self.card6)
        self.card6Date.setGeometry(QtCore.QRect(12, 178, 150, 16))
        self.card6Date.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card6Date.setObjectName("card6Date")
        self.card6Owner = QtWidgets.QLabel(parent=self.card6)
        self.card6Owner.setGeometry(QtCore.QRect(12, 194, 170, 16))
        self.card6Owner.setStyleSheet("QLabel{\n"
"    color:#222;\n"
"    font-size:8px;\n"
"    font-weight:500;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card6Owner.setObjectName("card6Owner")
        self.card6Money = QtWidgets.QLabel(parent=self.card6)
        self.card6Money.setGeometry(QtCore.QRect(14, 214, 210, 20))
        self.card6Money.setStyleSheet("QLabel{\n"
"    color:#7C4A73;\n"
"    font-size:10px;\n"
"    font-weight:900;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card6Money.setObjectName("card6Money")
        self.card6Progress = QtWidgets.QProgressBar(parent=self.card6)
        self.card6Progress.setGeometry(QtCore.QRect(15, 235, 250, 8))
        self.card6Progress.setStyleSheet("QProgressBar{\n"
"    background:#F6DCE8;\n"
"    border:none;\n"
"    border-radius:4px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background:#F2AED0;\n"
"    border-radius:4px;\n"
"}")
        self.card6Progress.setProperty("value", 30)
        self.card6Progress.setTextVisible(False)
        self.card6Progress.setObjectName("card6Progress")
        self.card6More = QtWidgets.QLabel(parent=self.card6)
        self.card6More.setGeometry(QtCore.QRect(15, 243, 80, 16))
        self.card6More.setStyleSheet("QLabel{\n"
"    color:#9A5C8B;\n"
"    font-size:8px;\n"
"    font-weight:700;\n"
"    background:transparent;\n"
"    border:none;\n"
"}")
        self.card6More.setObjectName("card6More")
        self.topBar.raise_()
        self.backLabel.raise_()
        self.titleIcon.raise_()
        self.mainTitle.raise_()
        self.searchEdit.raise_()
        self.searchIcon.raise_()
        self.categoryCombo.raise_()
        self.searchButton.raise_()
        self.card2.raise_()
        self.card3.raise_()
        self.card4.raise_()
        self.card5.raise_()
        self.card6.raise_()
        self.card1.raise_()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Y tế & Sức khỏe"))
        self.logoIcon.setText(_translate("MainWindow", "🕊"))
        self.logoTitle.setText(_translate("MainWindow", "Donarity"))
        self.logoSub.setText(_translate("MainWindow", "by group 10"))
        self.navHome.setText(_translate("MainWindow", "⌂ Trang chủ"))
        self.navStats.setText(_translate("MainWindow", "⌛ Thống kê"))
        self.navChatbot.setText(_translate("MainWindow", "◕ Chatbot"))
        self.notifIcon.setText(_translate("MainWindow", "🔔"))
        self.notifBadge.setText(_translate("MainWindow", "0"))
        self.settingsIcon.setText(_translate("MainWindow", "⚙"))
        self.userIcon.setText(_translate("MainWindow", "◉"))
        self.backLabel.setText(_translate("MainWindow", "← Quay lại"))
        self.titleIcon.setText(_translate("MainWindow", "💝"))
        self.mainTitle.setText(_translate("MainWindow", "Y tế & Sức khỏe"))
        self.searchEdit.setPlaceholderText(_translate("MainWindow", "Search for..."))
        self.searchIcon.setText(_translate("MainWindow", "⌕"))
        self.categoryCombo.setItemText(0, _translate("MainWindow", "All Categories"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.card1Title.setText(_translate("MainWindow", "Quỹ Nhịp Tim Việt Nam (Vết sẹo cuộc đời)"))
        self.card1Date.setText(_translate("MainWindow", "Date:      2006-11-21"))
        self.card1Owner.setText(_translate("MainWindow", "Owner:   Rad Kivette"))
        self.card1Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card1More.setText(_translate("MainWindow", "Xem thêm"))
        self.card2Title.setText(_translate("MainWindow", "Operation Smile Viet Nam (Phẫu thuật nụ cười)"))
        self.card2Date.setText(_translate("MainWindow", "Date:      1989-02-06"))
        self.card2Owner.setText(_translate("MainWindow", "Owner:   Nguyễn Việt Phương"))
        self.card2Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card2More.setText(_translate("MainWindow", "Xem thêm"))
        self.card3Title.setText(_translate("MainWindow", "Quỹ Ngày mai tươi sáng (Hỗ trợ bệnh nhi ung thư)"))
        self.card3Date.setText(_translate("MainWindow", "Date:      2011-08-18"))
        self.card3Owner.setText(_translate("MainWindow", "Owner:   Nguyễn Thị Xuyến"))
        self.card3Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card3More.setText(_translate("MainWindow", "Xem thêm"))
        self.card4Title.setText(_translate("MainWindow", "Ánh sáng cho người nghèo (Mổ mắt miễn phí)"))
        self.card4Date.setText(_translate("MainWindow", "Date:      2020-08-15"))
        self.card4Owner.setText(_translate("MainWindow", "Owner:   Trần Thành Long"))
        self.card4Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card4More.setText(_translate("MainWindow", "Xem thêm"))
        self.card5Title.setText(_translate("MainWindow", "Dự án Cải thiện Dinh dưỡng Trẻ em nghèo"))
        self.card5Date.setText(_translate("MainWindow", "Date:      2021-05-10"))
        self.card5Owner.setText(_translate("MainWindow", "Owner:   Trần Thị Như Trang"))
        self.card5Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card5More.setText(_translate("MainWindow", "Xem thêm"))
        self.card6Title.setText(_translate("MainWindow", "Phẫu thuật Xương thủy tinh cho trẻ"))
        self.card6Date.setText(_translate("MainWindow", "Date:      2022-11-20"))
        self.card6Owner.setText(_translate("MainWindow", "Owner:   Trần Thành Long"))
        self.card6Money.setText(_translate("MainWindow", "1000000000/15000000000"))
        self.card6More.setText(_translate("MainWindow", "Xem thêm"))
